!
! auto-generated by op2.py
!

MODULE GETQ_CHRISTIENSEN_BC_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getq_christiensen_bc
SUBROUTINE getq_christiensen_bc(ielel,scratch,iel,indtype1,indtype2, &
&                               indtype3,indtype4,iside)
    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(OUT) :: scratch
    INTEGER(KIND=ink), INTENT(INOUT) :: iside
    INTEGER(KIND=ink), INTENT(IN) :: indtype1, indtype2, &
&                                    indtype3, indtype4
    INTEGER(KIND=ink), DIMENSION(N_SHAPE), INTENT(IN) :: ielel
    INTEGER(KIND=ink) :: in1,in2,ins,ic1,ic2,iel
    INTEGER(kind=ink), DIMENSION(4) :: indtype


    indtype(1) = indtype1
    indtype(2) = indtype2
    indtype(3) = indtype3
    indtype(4) = indtype4

    ins=iside+2_ink
    in1=ielel(iside)
    in2=ielel(ins)
    IF (in1.EQ.iel) THEN
      ic1=iside
      ic2=MOD(iside,N_SHAPE)+1_ink
      IF (((indtype(ic1).LT.0_ink).AND.(indtype(ic2).LT.0_ink)).AND.&
&          (in2.NE.iel)) THEN
        scratch(1)=1.0_rlk
        scratch(3)=1.0_rlk
      ELSE
        scratch(1)=0.0_rlk
        scratch(3)=0.0_rlk
      ENDIF
    ENDIF
    IF (in2.EQ.iel) THEN
      ic1=ins
      ic2=MOD(ins,N_SHAPE)+1_ink
      IF (((indtype(ic1).LT.0_ink).AND.(indtype(ic2).LT.0_ink)).AND.&
&          (in1.NE.iel)) THEN
        scratch(2)=1.0_rlk
        scratch(4)=1.0_rlk
      ELSE
        scratch(2)=0.0_rlk
        scratch(4)=0.0_rlk
      ENDIF
    ENDIF

  END SUBROUTINE getq_christiensen_bc


SUBROUTINE op_wrap_getq_christiensen_bc( &
  & opDat4Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat8Local, &
  & opDat4Map, &
  & opDat4MapDim, &
  & bottom,top)
  implicit none
  integer(4) opDat4Local(1,*)
  integer(4) opDat1Local(4,*)
  real(8) opDat2Local(4,*)
  integer(4) opDat3Local(1,*)
  integer(4) opDat8Local(1)
  INTEGER(kind=4) opDat4Map(*)
  INTEGER(kind=4) opDat4MapDim
  INTEGER(kind=4) bottom,top,i1
  INTEGER(kind=4) map4idx, map5idx, map6idx, map7idx

  DO i1 = bottom, top-1, 1
    map4idx = opDat4Map(1 + i1 * opDat4MapDim + 0)+1
    map5idx = opDat4Map(1 + i1 * opDat4MapDim + 1)+1
    map6idx = opDat4Map(1 + i1 * opDat4MapDim + 2)+1
    map7idx = opDat4Map(1 + i1 * opDat4MapDim + 3)+1
! kernel call
  CALL getq_christiensen_bc( &
    & opDat1Local(1,i1+1), &
    & opDat2Local(1,i1+1), &
    & opDat3Local(1,i1+1), &
    & opDat4Local(1,map4idx), &
    & opDat4Local(1,map5idx), &
    & opDat4Local(1,map6idx), &
    & opDat4Local(1,map7idx), &
    & opDat8Local(1) &
    & )
  END DO
END SUBROUTINE
SUBROUTINE getq_christiensen_bc_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6, &
  & opArg7, &
  & opArg8 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4
  type ( op_arg ) , INTENT(IN) :: opArg5
  type ( op_arg ) , INTENT(IN) :: opArg6
  type ( op_arg ) , INTENT(IN) :: opArg7
  type ( op_arg ) , INTENT(IN) :: opArg8

  type ( op_arg ) , DIMENSION(8) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
  REAL(kind=8) :: startTime
  REAL(kind=8) :: endTime
  INTEGER(kind=4) :: returnSetKernelTiming
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat4Map
  INTEGER(kind=4) :: opDat4MapDim
  integer(4), POINTER, DIMENSION(:) :: opDat4Local
  INTEGER(kind=4) :: opDat4Cardinality

  integer(4), POINTER, DIMENSION(:) :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat2Local
  INTEGER(kind=4) :: opDat2Cardinality

  integer(4), POINTER, DIMENSION(:) :: opDat3Local
  INTEGER(kind=4) :: opDat3Cardinality

  integer(4), POINTER, DIMENSION(:) :: opDat8Local

  INTEGER(kind=4) :: i1
  REAL(kind=4) :: dataTransfer

  numberOfOpDats = 8

  opArgArray(1) = opArg1
  opArgArray(2) = opArg2
  opArgArray(3) = opArg3
  opArgArray(4) = opArg4
  opArgArray(5) = opArg5
  opArgArray(6) = opArg6
  opArgArray(7) = opArg7
  opArgArray(8) = opArg8

  returnSetKernelTiming = setKernelTime(25 , userSubroutine//C_NULL_CHAR, &
  & 0.d0, 0.00000_4,0.00000_4, 0)
  call op_timers_core(startTime)

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  opSetCore => set%setPtr

  opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
  opDat4MapDim = getMapDimFromOpArg(opArg4)
  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
  CALL c_f_pointer(opArg4%data,opDat4Local,(/opDat4Cardinality/))
  CALL c_f_pointer(opArg4%map_data,opDat4Map,(/opSetCore%size*opDat4MapDim/))
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg3%data,opDat3Local,(/opDat3Cardinality/))
  CALL c_f_pointer(opArg8%data,opDat8Local, (/opArg8%dim/))


  CALL op_wrap_getq_christiensen_bc( &
  & opDat4Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat8Local, &
  & opDat4Map, &
  & opDat4MapDim, &
  & 0, opSetCore%core_size)
  CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  CALL op_wrap_getq_christiensen_bc( &
  & opDat4Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat8Local, &
  & opDat4Map, &
  & opDat4MapDim, &
  & opSetCore%core_size, n_upper)
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF


  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  dataTransfer = 0.0
  dataTransfer = dataTransfer + opArg4%size * MIN(n_upper,getSetSizeFromOpArg(opArg4))
  dataTransfer = dataTransfer + opArg1%size * MIN(n_upper,getSetSizeFromOpArg(opArg1))
  dataTransfer = dataTransfer + opArg2%size * MIN(n_upper,getSetSizeFromOpArg(opArg2))
  dataTransfer = dataTransfer + opArg3%size * MIN(n_upper,getSetSizeFromOpArg(opArg3))
  dataTransfer = dataTransfer + opArg8%size
  dataTransfer = dataTransfer + n_upper * opDat4MapDim * 4.d0
  returnSetKernelTiming = setKernelTime(25 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, dataTransfer, 0.00000_4, 1)
END SUBROUTINE
END MODULE