!
! auto-generated by op2.py
!

MODULE GETQ_CHRISTIENSEN_BC_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! getq_christiensen_bcvariable declarations

INTEGER(kind=4) :: opDat4_stride_OP2CONSTANT
!$acc declare create(opDat4_stride_OP2CONSTANT)
INTEGER(kind=4) :: direct_stride_OP2CONSTANT
!$acc declare create(direct_stride_OP2CONSTANT)

#define OP2_SOA(var,dim,stride) var((dim-1)*stride+1)

CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getq_christiensen_bc
SUBROUTINE getq_christiensen_bc_gpu(ielel,scratch,iel,indtype1,indtype2, &
&                               indtype3,indtype4,iside)
!$acc routine seq
    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(OUT) :: scratch
    INTEGER(KIND=ink), INTENT(INOUT) :: iside
    INTEGER(KIND=ink), INTENT(IN) :: indtype1, indtype2, &
&                                    indtype3, indtype4
    INTEGER(KIND=ink), DIMENSION(N_SHAPE), INTENT(IN) :: ielel
    INTEGER(KIND=ink) :: in1,in2,ins,ic1,ic2,iel
    INTEGER(kind=ink), DIMENSION(4) :: indtype


    indtype(1) = indtype1
    indtype(2) = indtype2
    indtype(3) = indtype3
    indtype(4) = indtype4

    ins=iside+2_ink
    in1=OP2_SOA(ielel,iside, direct_stride_OP2CONSTANT)
    in2=OP2_SOA(ielel,ins, direct_stride_OP2CONSTANT)
    IF (in1.EQ.iel) THEN
      ic1=iside
      ic2=MOD(iside,N_SHAPE)+1_ink
      IF (((indtype(ic1).LT.0_ink).AND.(indtype(ic2).LT.0_ink)).AND.&
&          (in2.NE.iel)) THEN
        OP2_SOA(scratch,1, direct_stride_OP2CONSTANT)=1.0_rlk
        OP2_SOA(scratch,3, direct_stride_OP2CONSTANT)=1.0_rlk
      ELSE
        OP2_SOA(scratch,1, direct_stride_OP2CONSTANT)=0.0_rlk
        OP2_SOA(scratch,3, direct_stride_OP2CONSTANT)=0.0_rlk
      ENDIF
    ENDIF
    IF (in2.EQ.iel) THEN
      ic1=ins
      ic2=MOD(ins,N_SHAPE)+1_ink
      IF (((indtype(ic1).LT.0_ink).AND.(indtype(ic2).LT.0_ink)).AND.&
&          (in1.NE.iel)) THEN
        OP2_SOA(scratch,2, direct_stride_OP2CONSTANT)=1.0_rlk
        OP2_SOA(scratch,4, direct_stride_OP2CONSTANT)=1.0_rlk
      ELSE
        OP2_SOA(scratch,2, direct_stride_OP2CONSTANT)=0.0_rlk
        OP2_SOA(scratch,4, direct_stride_OP2CONSTANT)=0.0_rlk
      ENDIF
    ENDIF

  END SUBROUTINE getq_christiensen_bc_gpu


SUBROUTINE op_wrap_getq_christiensen_bc( &
& opDat4Local, &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat8Local, &
& opDat4Map, &
& opDat4MapDim, &
& col_reord, set_size, &
& bottom,top)
implicit none
integer(4) opDat4Local(1,*)
integer(4) opDat1Local(*)
real(8) opDat2Local(*)
integer(4) opDat3Local(1,*)
integer(4) opDat8Local(1)
INTEGER(kind=4) opDat4Map(*)
INTEGER(kind=4) opDat4MapDim
INTEGER(kind=4) col_reord(*)
INTEGER(kind=4) set_size

INTEGER(kind=4) bottom,top,i1,i2
INTEGER(kind=4) map4idx, map5idx, map6idx, map7idx


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat4Local) &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat2Local) &
!$acc& deviceptr(opDat3Local) &
!$acc& deviceptr(opDat4Map) &
!$acc& deviceptr(col_reord) private(i1) &
!$acc& private(map4idx) &
!$acc& private(map5idx) &
!$acc& private(map6idx) &
!$acc& private(map7idx) 
DO i2 = bottom, top-1, 1
  i1 = col_reord(i2+1)
  map4idx = opDat4Map(1 + i1 + set_size * 0)+1
  map5idx = opDat4Map(1 + i1 + set_size * 1)+1
  map6idx = opDat4Map(1 + i1 + set_size * 2)+1
  map7idx = opDat4Map(1 + i1 + set_size * 3)+1
! kernel call
  CALL getq_christiensen_bc_gpu( &
  & opDat1Local(i1+1), &
  & opDat2Local(i1+1), &
  & opDat3Local(1,i1+1), &
  & opDat4Local(1,map4idx), &
  & opDat4Local(1,map5idx), &
  & opDat4Local(1,map6idx), &
  & opDat4Local(1,map7idx), &
  & opDat8Local(1) &
  & )
END DO

END SUBROUTINE
SUBROUTINE getq_christiensen_bc_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7, &
& opArg8 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7
type ( op_arg ) , INTENT(IN) :: opArg8

type ( op_arg ) , DIMENSION(8) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat4Map
INTEGER(kind=4) :: opDat4MapDim
integer(4), POINTER, DIMENSION(:) :: opDat4Local
INTEGER(kind=4) :: opDat4Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat3Local
INTEGER(kind=4) :: opDat3Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat8Local
INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: exec_size
LOGICAL :: firstTime_getq_christiensen_bc = .TRUE.
type ( c_ptr )  :: planRet_getq_christiensen_bc
type ( op_plan ) , POINTER :: actualPlan_getq_christiensen_bc
INTEGER(kind=4), POINTER, DIMENSION(:) :: col_reord_getq_christiensen_bc
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_getq_christiensen_bc
INTEGER(kind=4), DIMENSION(1:8) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 8

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7
opArgArray(8) = opArg8

returnSetKernelTiming = setKernelTime(25 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
IF ((calledTimes.EQ.0).OR.(opDat4_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg4))) THEN
  opDat4_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg4)
  !$acc update device(opDat4_stride_OP2CONSTANT)
END IF
IF ((calledTimes.EQ.0).OR.(direct_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg1))) THEN
  direct_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg1)
  !$acc update device(direct_stride_OP2CONSTANT)
END IF
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

indirectionDescriptorArray(1) = -1
indirectionDescriptorArray(2) = -1
indirectionDescriptorArray(3) = -1
indirectionDescriptorArray(4) = 0
indirectionDescriptorArray(5) = 0
indirectionDescriptorArray(6) = 0
indirectionDescriptorArray(7) = 0
indirectionDescriptorArray(8) = -1

exec_size = opSetCore%size + opSetCore%exec_size
numberOfIndirectOpDats = 1

planRet_getq_christiensen_bc = FortranPlanCaller( &
& userSubroutine//C_NULL_CHAR, &
& set%setCPtr, &
& partitionSize, &
& numberOfOpDats, &
& opArgArray, &
& numberOfIndirectOpDats, &
& indirectionDescriptorArray,4)

CALL c_f_pointer(planRet_getq_christiensen_bc,actualPlan_getq_christiensen_bc)
CALL c_f_pointer(actualPlan_getq_christiensen_bc%col_reord,col_reord_getq_christiensen_bc,(/exec_size/))
CALL c_f_pointer(actualPlan_getq_christiensen_bc%color2_offsets,offset_getq_christiensen_bc,(/actualPlan_getq_christiensen_bc%ncolors+1/))
opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
opDat4MapDim = getMapDimFromOpArg(opArg4)
opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
CALL c_f_pointer(opArg4%data_d,opDat4Local,(/opDat4Cardinality/))
CALL c_f_pointer(opArg4%map_data_d,opDat4Map,(/exec_size*opDat4MapDim/))
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg2%data_d,opDat2Local,(/opDat2Cardinality/))
CALL c_f_pointer(opArg3%data_d,opDat3Local,(/opDat3Cardinality/))
CALL c_f_pointer(opArg8%data,opDat8Local, (/opArg8%dim/))



DO i1 = 0, actualPlan_getq_christiensen_bc%ncolors-1, 1
  IF (i1 .EQ. 1) THEN
    CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
  END IF

  offset_b = offset_getq_christiensen_bc(i1 + 1)
  nelem = offset_getq_christiensen_bc(i1 + 1 + 1)
  CALL op_wrap_getq_christiensen_bc( &
  & opDat4Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat8Local(1), &
  & opDat4Map, &
  & opDat4MapDim, &
  & col_reord_getq_christiensen_bc, exec_size, offset_b, nelem )
END DO
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

returnSetKernelTiming = setKernelTime(25 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, actualPlan_getq_christiensen_bc%transfer,actualPlan_getq_christiensen_bc%transfer2, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE