#
# !Crown Copyright 2014 AWE.
# !
# ! This file is part of Bookleaf.
# !
# ! Bookleaf is free software: you can redistribute it and/or modify it under
# ! the terms of the GNU General Public License as published by the
# ! Free Software Foundation, either version 3 of the License, or (at your option)
# ! any later version.
# !
# ! Bookleaf is distributed in the hope that it will be useful, but
# ! WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# ! FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# ! details.
# !
# ! You should have received a copy of the GNU General Public License along with
# ! Bookleaf. If not, see http://www.gnu.org/licenses/.
#
#
# Object list

ifeq ($(OPTARGET),meshgen)
else
ifndef OPTARGET
OBJ += gethg.o       \
       gethg_kernels.o        \
       getq.o        \
       getq_kernels.o \
       getsp_kernels.o \
       getsp.o
else
OBJ += gethg_op.o       \
       getq_op.o        \
       getsp_op.o
ifeq ($(OPTARGET),genseq)
OBJ += $(shell find . -maxdepth 1 -name "*_seqkernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
endif
ifeq ($(OPTARGET),openmp)
OBJ =
OBJ += $(shell find . -maxdepth 1 -name "*_kernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
endif
ifeq ($(OPTARGET),cuda)
OBJ += $(shell find . -maxdepth 1 -name "*_gpukernel.CUF" | sed s/\\.CUF/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
endif
ifeq ($(OPTARGET),mpi)
OBJ =
OBJ += $(shell find . -maxdepth 1 -name "*_seqkernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
endif
ifeq ($(OPTARGET),mpi_openmp)
OBJ =
OBJ += $(shell find . -maxdepth 1 -name "*_kernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
endif
ifeq ($(OPTARGET),mpi_cuda)
OBJ += $(shell find . -maxdepth 1 -name "*_gpukernel.CUF" | sed s/\\.CUF/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
endif
endif
endif