!
! auto-generated by op2.py
!

MODULE ALE_ADVECTORS_SUMFLUX_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_advectors_sumflux
SUBROUTINE ale_advectors_sumflux(rFlux,rFlux1,rFlux2,rFlux3,rFlux4,rTotFlux,iElSd,iElEl,iel,i1)
    USE kinds_mod,ONLY: rlk, ink
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: rFlux,rFlux1,rFlux2,rFlux3,rFlux4
    REAL(KIND=rlk), INTENT(OUT) :: rTotFlux
    INTEGER(KIND=ink), DIMENSION(N_SHAPE), INTENT(IN) :: iElSd,iElEl
    INTEGER(KIND=ink), INTENT(IN) :: iel
    INTEGER(KIND=ink) :: i1

    INTEGER(KIND=ink) :: i2,j1,j2,ie1,ie2
    REAL(KIND=rlk) :: w1,w2

    i2 = i1+2_ink
    iE1=iElEl(i1)
    iE2=iElEl(i2)
    j1=iElSd(i1)
    j2=iElSd(i2)
    IF (i1.EQ.1_ink) THEN
      w1=rFlux1(j1)
      w2=rFlux3(j2)
    ELSEIF (i1.EQ.2_ink) THEN
      w1=rFlux2(j1)
      w2=rFlux4(j2)
    ENDIF

    IF (iE1.EQ.iEl) w1=0.0_rlk
    IF (iE2.EQ.iEl) w2=0.0_rlk
    rTotFlux=rTotFlux-rFlux(i1)-rFlux(i2)+w1+w2
  END SUBROUTINE ale_advectors_sumflux


SUBROUTINE op_wrap_ale_advectors_sumflux( &
& opDat2Local, &
& opDat1Local, &
& opDat6Local, &
& opDat7Local, &
& opDat8Local, &
& opDat9Local, &
& opDat10Local, &
& opDat2Map, &
& opDat2MapDim, &
& bottom,top)
real(8) opDat2Local(4,*)
real(8) opDat1Local(4,*)
real(8) opDat6Local(1,*)
integer(4) opDat7Local(4,*)
integer(4) opDat8Local(4,*)
integer(4) opDat9Local(1,*)
integer(4) opDat10Local(1)
INTEGER(kind=4) opDat2Map(*)
INTEGER(kind=4) opDat2MapDim
INTEGER(kind=4) bottom,top,i1
INTEGER(kind=4) map2idx, map3idx, map4idx, map5idx

DO i1 = bottom, top-1, 1
  map2idx = opDat2Map(1 + i1 * opDat2MapDim + 0)+1
  map3idx = opDat2Map(1 + i1 * opDat2MapDim + 1)+1
  map4idx = opDat2Map(1 + i1 * opDat2MapDim + 2)+1
  map5idx = opDat2Map(1 + i1 * opDat2MapDim + 3)+1
! kernel call
CALL ale_advectors_sumflux( &
  & opDat1Local(1,i1+1), &
  & opDat2Local(1,map2idx), &
  & opDat2Local(1,map3idx), &
  & opDat2Local(1,map4idx), &
  & opDat2Local(1,map5idx), &
  & opDat6Local(1,i1+1), &
  & opDat7Local(1,i1+1), &
  & opDat8Local(1,i1+1), &
  & opDat9Local(1,i1+1), &
  & opDat10Local(1) &
  & )
END DO
END SUBROUTINE
SUBROUTINE ale_advectors_sumflux_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7, &
& opArg8, &
& opArg9, &
& opArg10 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7
type ( op_arg ) , INTENT(IN) :: opArg8
type ( op_arg ) , INTENT(IN) :: opArg9
type ( op_arg ) , INTENT(IN) :: opArg10

type ( op_arg ) , DIMENSION(10) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat2Map
INTEGER(kind=4) :: opDat2MapDim
real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat6Local
INTEGER(kind=4) :: opDat6Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat7Local
INTEGER(kind=4) :: opDat7Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat8Local
INTEGER(kind=4) :: opDat8Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat9Local
INTEGER(kind=4) :: opDat9Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat10Local
INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
LOGICAL :: firstTime_ale_advectors_sumflux = .TRUE.
type ( c_ptr )  :: planRet_ale_advectors_sumflux
type ( op_plan ) , POINTER :: actualPlan_ale_advectors_sumflux
INTEGER(kind=4), POINTER, DIMENSION(:) :: ncolblk_ale_advectors_sumflux
INTEGER(kind=4), POINTER, DIMENSION(:) :: blkmap_ale_advectors_sumflux
INTEGER(kind=4), POINTER, DIMENSION(:) :: nelems_ale_advectors_sumflux
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_ale_advectors_sumflux
INTEGER(kind=4), DIMENSION(1:10) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: blockOffset
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 10

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7
opArgArray(8) = opArg8
opArgArray(9) = opArg9
opArgArray(10) = opArg10

returnSetKernelTiming = setKernelTime(15 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  partitionSize = 0

  numberOfThreads = omp_get_max_threads()
  indirectionDescriptorArray(1) = -1
  indirectionDescriptorArray(2) = 0
  indirectionDescriptorArray(3) = 0
  indirectionDescriptorArray(4) = 0
  indirectionDescriptorArray(5) = 0
  indirectionDescriptorArray(6) = -1
  indirectionDescriptorArray(7) = -1
  indirectionDescriptorArray(8) = -1
  indirectionDescriptorArray(9) = -1
  indirectionDescriptorArray(10) = -1

  numberOfIndirectOpDats = 1

  planRet_ale_advectors_sumflux = FortranPlanCaller( &
  & userSubroutine//C_NULL_CHAR, &
  & set%setCPtr, &
  & partitionSize, &
  & numberOfOpDats, &
  & opArgArray, &
  & numberOfIndirectOpDats, &
  & indirectionDescriptorArray,2)

  CALL c_f_pointer(planRet_ale_advectors_sumflux,actualPlan_ale_advectors_sumflux)
  CALL c_f_pointer(actualPlan_ale_advectors_sumflux%ncolblk,ncolblk_ale_advectors_sumflux,(/actualPlan_ale_advectors_sumflux%ncolors_core/))
  CALL c_f_pointer(actualPlan_ale_advectors_sumflux%blkmap,blkmap_ale_advectors_sumflux,(/actualPlan_ale_advectors_sumflux%nblocks/))
  CALL c_f_pointer(actualPlan_ale_advectors_sumflux%offset,offset_ale_advectors_sumflux,(/actualPlan_ale_advectors_sumflux%nblocks/))
  CALL c_f_pointer(actualPlan_ale_advectors_sumflux%nelems,nelems_ale_advectors_sumflux,(/actualPlan_ale_advectors_sumflux%nblocks/))

  opSetCore => set%setPtr

  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat2MapDim = getMapDimFromOpArg(opArg2)
  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
  opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
  opDat8Cardinality = opArg8%dim * getSetSizeFromOpArg(opArg8)
  opDat9Cardinality = opArg9%dim * getSetSizeFromOpArg(opArg9)
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg2%map_data,opDat2Map,(/opSetCore%size*opDat2MapDim/))
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg6%data,opDat6Local,(/opDat6Cardinality/))
  CALL c_f_pointer(opArg7%data,opDat7Local,(/opDat7Cardinality/))
  CALL c_f_pointer(opArg8%data,opDat8Local,(/opDat8Cardinality/))
  CALL c_f_pointer(opArg9%data,opDat9Local,(/opDat9Cardinality/))
  CALL c_f_pointer(opArg10%data,opDat10Local, (/opArg10%dim/))


  blockOffset = 0

  DO i1 = 0, actualPlan_ale_advectors_sumflux%ncolors-1, 1
    IF (i1 .EQ. actualPlan_ale_advectors_sumflux%ncolors_core) THEN
      CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
    END IF

    nblocks = ncolblk_ale_advectors_sumflux(i1 + 1)
    !$OMP PARALLEL DO private (threadID, blockID, nelem, offset_b)
    DO i2 = 0, nblocks-1, 1
      threadID = omp_get_thread_num()
      blockID = blkmap_ale_advectors_sumflux(i2+blockOffset+1)
      nelem = nelems_ale_advectors_sumflux(blockID+1)
      offset_b = offset_ale_advectors_sumflux(blockID+1)
      CALL op_wrap_ale_advectors_sumflux( &
      & opDat2Local, &
      & opDat1Local, &
      & opDat6Local, &
      & opDat7Local, &
      & opDat8Local, &
      & opDat9Local, &
      & opDat10Local, &
      & opDat2Map, &
      & opDat2MapDim, &
      & offset_b, offset_b+nelem)
    END DO
    !$OMP END PARALLEL DO
    blockOffset = blockOffset + nblocks
  END DO
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(15 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, actualPlan_ale_advectors_sumflux%transfer,actualPlan_ale_advectors_sumflux%transfer2, 1)
END SUBROUTINE
END MODULE