!
! auto-generated by op2.py
!

MODULE ALE_ADVECT_PREVOLMASS_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! ale_advect_prevolmassvariable declarations

INTEGER(kind=4) :: opDat5_stride_OP2CONSTANT
!$acc declare create(opDat5_stride_OP2CONSTANT)
INTEGER(kind=4) :: direct_stride_OP2CONSTANT
!$acc declare create(direct_stride_OP2CONSTANT)

#define OP2_SOA(var,dim,stride) var((dim-1)*stride+1)

CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_advect_prevolmass
SUBROUTINE ale_advect_prevolmass_gpu(elv0ndm1,elv1,cnm0,cnm1, &
    &      ndv00,ndv10,ndm00,ndv01,ndv11,ndm01,ndv02,ndv12,ndm02,ndv03,ndv13,ndm03)
!$acc routine seq

    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: elv0ndm1,elv1
    REAL(KIND=rlk), INTENT(INOUT) :: ndv00,ndv10,ndm00,ndv01,ndv11,ndm01,ndv02,ndv12,ndm02,ndv03,ndv13,ndm03
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(OUT) :: cnm0
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: cnm1
    REAL(KIND=rlk) :: w1,w2,w3

    w1=0.25_rlk*elv0ndm1
    w2=0.25_rlk*elv1
    !1st
    w3=cnm1(1)
    cnm0(1)=w3
    ndv00=ndv00+w1
    ndv10=ndv10+w2
    ndm00=ndm00+w3
    !2nd
    w3=cnm1(2)
    cnm0(2)=w3
    ndv01=ndv01+w1
    ndv11=ndv11+w2
    ndm01=ndm01+w3
    !3rd
    w3=cnm1(3)
    cnm0(3)=w3
    ndv02=ndv02+w1
    ndv12=ndv12+w2
    ndm02=ndm02+w3
    !4th
    w3=cnm1(4)
    cnm0(4)=w3
    ndv03=ndv03+w1
    ndv13=ndv13+w2
    ndm03=ndm03+w3

  END SUBROUTINE ale_advect_prevolmass_gpu


SUBROUTINE op_wrap_ale_advect_prevolmass( &
& opDat5Local, &
& opDat6Local, &
& opDat7Local, &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat4Local, &
& opDat5Map, &
& opDat5MapDim, &
& col_reord, set_size, &
& bottom,top)
implicit none
real(8) opDat5Local(1,*)
real(8) opDat6Local(1,*)
real(8) opDat7Local(1,*)
real(8) opDat1Local(1,*)
real(8) opDat2Local(1,*)
real(8) opDat3Local(*)
real(8) opDat4Local(*)
INTEGER(kind=4) opDat5Map(*)
INTEGER(kind=4) opDat5MapDim
INTEGER(kind=4) col_reord(*)
INTEGER(kind=4) set_size

INTEGER(kind=4) bottom,top,i1,i2
INTEGER(kind=4) map5idx, map8idx, map11idx, map14idx


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat5Local) &
!$acc& deviceptr(opDat6Local) &
!$acc& deviceptr(opDat7Local) &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat2Local) &
!$acc& deviceptr(opDat3Local) &
!$acc& deviceptr(opDat4Local) &
!$acc& deviceptr(opDat5Map) &
!$acc& deviceptr(col_reord) private(i1) &
!$acc& private(map5idx) &
!$acc& private(map8idx) &
!$acc& private(map11idx) &
!$acc& private(map14idx) 
DO i2 = bottom, top-1, 1
  i1 = col_reord(i2+1)
  map5idx = opDat5Map(1 + i1 + set_size * 0)+1
  map8idx = opDat5Map(1 + i1 + set_size * 1)+1
  map11idx = opDat5Map(1 + i1 + set_size * 2)+1
  map14idx = opDat5Map(1 + i1 + set_size * 3)+1
! kernel call
  CALL ale_advect_prevolmass_gpu( &
  & opDat1Local(1,i1+1), &
  & opDat2Local(1,i1+1), &
  & opDat3Local(i1+1), &
  & opDat4Local(i1+1), &
  & opDat5Local(1,map5idx), &
  & opDat6Local(1,map5idx), &
  & opDat7Local(1,map5idx), &
  & opDat5Local(1,map8idx), &
  & opDat6Local(1,map8idx), &
  & opDat7Local(1,map8idx), &
  & opDat5Local(1,map11idx), &
  & opDat6Local(1,map11idx), &
  & opDat7Local(1,map11idx), &
  & opDat5Local(1,map14idx), &
  & opDat6Local(1,map14idx), &
  & opDat7Local(1,map14idx) &
  & )
END DO

END SUBROUTINE
SUBROUTINE ale_advect_prevolmass_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7, &
& opArg8, &
& opArg9, &
& opArg10, &
& opArg11, &
& opArg12, &
& opArg13, &
& opArg14, &
& opArg15, &
& opArg16 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7
type ( op_arg ) , INTENT(IN) :: opArg8
type ( op_arg ) , INTENT(IN) :: opArg9
type ( op_arg ) , INTENT(IN) :: opArg10
type ( op_arg ) , INTENT(IN) :: opArg11
type ( op_arg ) , INTENT(IN) :: opArg12
type ( op_arg ) , INTENT(IN) :: opArg13
type ( op_arg ) , INTENT(IN) :: opArg14
type ( op_arg ) , INTENT(IN) :: opArg15
type ( op_arg ) , INTENT(IN) :: opArg16

type ( op_arg ) , DIMENSION(16) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat5Map
INTEGER(kind=4) :: opDat5MapDim
real(8), POINTER, DIMENSION(:) :: opDat5Local
INTEGER(kind=4) :: opDat5Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat6Map
INTEGER(kind=4) :: opDat6MapDim
real(8), POINTER, DIMENSION(:) :: opDat6Local
INTEGER(kind=4) :: opDat6Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat7Map
INTEGER(kind=4) :: opDat7MapDim
real(8), POINTER, DIMENSION(:) :: opDat7Local
INTEGER(kind=4) :: opDat7Cardinality

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat3Local
INTEGER(kind=4) :: opDat3Cardinality

real(8), POINTER, DIMENSION(:) :: opDat4Local
INTEGER(kind=4) :: opDat4Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: exec_size
LOGICAL :: firstTime_ale_advect_prevolmass = .TRUE.
type ( c_ptr )  :: planRet_ale_advect_prevolmass
type ( op_plan ) , POINTER :: actualPlan_ale_advect_prevolmass
INTEGER(kind=4), POINTER, DIMENSION(:) :: col_reord_ale_advect_prevolmass
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_ale_advect_prevolmass
INTEGER(kind=4), DIMENSION(1:16) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 16

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7
opArgArray(8) = opArg8
opArgArray(9) = opArg9
opArgArray(10) = opArg10
opArgArray(11) = opArg11
opArgArray(12) = opArg12
opArgArray(13) = opArg13
opArgArray(14) = opArg14
opArgArray(15) = opArg15
opArgArray(16) = opArg16

returnSetKernelTiming = setKernelTime(2 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
IF ((calledTimes.EQ.0).OR.(opDat5_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg5))) THEN
  opDat5_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg5)
  !$acc update device(opDat5_stride_OP2CONSTANT)
END IF
IF ((calledTimes.EQ.0).OR.(direct_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg3))) THEN
  direct_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg3)
  !$acc update device(direct_stride_OP2CONSTANT)
END IF
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

indirectionDescriptorArray(1) = -1
indirectionDescriptorArray(2) = -1
indirectionDescriptorArray(3) = -1
indirectionDescriptorArray(4) = -1
indirectionDescriptorArray(5) = 0
indirectionDescriptorArray(6) = 1
indirectionDescriptorArray(7) = 2
indirectionDescriptorArray(8) = 0
indirectionDescriptorArray(9) = 1
indirectionDescriptorArray(10) = 2
indirectionDescriptorArray(11) = 0
indirectionDescriptorArray(12) = 1
indirectionDescriptorArray(13) = 2
indirectionDescriptorArray(14) = 0
indirectionDescriptorArray(15) = 1
indirectionDescriptorArray(16) = 2

exec_size = opSetCore%size + opSetCore%exec_size
numberOfIndirectOpDats = 3

planRet_ale_advect_prevolmass = FortranPlanCaller( &
& userSubroutine//C_NULL_CHAR, &
& set%setCPtr, &
& partitionSize, &
& numberOfOpDats, &
& opArgArray, &
& numberOfIndirectOpDats, &
& indirectionDescriptorArray,4)

CALL c_f_pointer(planRet_ale_advect_prevolmass,actualPlan_ale_advect_prevolmass)
CALL c_f_pointer(actualPlan_ale_advect_prevolmass%col_reord,col_reord_ale_advect_prevolmass,(/exec_size/))
CALL c_f_pointer(actualPlan_ale_advect_prevolmass%color2_offsets,offset_ale_advect_prevolmass,(/actualPlan_ale_advect_prevolmass%ncolors+1/))
opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
opDat5MapDim = getMapDimFromOpArg(opArg5)
opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
opDat6MapDim = getMapDimFromOpArg(opArg6)
opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
opDat7MapDim = getMapDimFromOpArg(opArg7)
opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
CALL c_f_pointer(opArg5%data_d,opDat5Local,(/opDat5Cardinality/))
CALL c_f_pointer(opArg5%map_data_d,opDat5Map,(/exec_size*opDat5MapDim/))
CALL c_f_pointer(opArg6%data_d,opDat6Local,(/opDat6Cardinality/))
CALL c_f_pointer(opArg6%map_data_d,opDat6Map,(/exec_size*opDat6MapDim/))
CALL c_f_pointer(opArg7%data_d,opDat7Local,(/opDat7Cardinality/))
CALL c_f_pointer(opArg7%map_data_d,opDat7Map,(/exec_size*opDat7MapDim/))
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg2%data_d,opDat2Local,(/opDat2Cardinality/))
CALL c_f_pointer(opArg3%data_d,opDat3Local,(/opDat3Cardinality/))
CALL c_f_pointer(opArg4%data_d,opDat4Local,(/opDat4Cardinality/))



DO i1 = 0, actualPlan_ale_advect_prevolmass%ncolors-1, 1
  IF (i1 .EQ. 1) THEN
    CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
  END IF

  offset_b = offset_ale_advect_prevolmass(i1 + 1)
  nelem = offset_ale_advect_prevolmass(i1 + 1 + 1)
  CALL op_wrap_ale_advect_prevolmass( &
  & opDat5Local, &
  & opDat6Local, &
  & opDat7Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat4Local, &
  & opDat5Map, &
  & opDat5MapDim, &
  & col_reord_ale_advect_prevolmass, exec_size, offset_b, nelem )
END DO
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

returnSetKernelTiming = setKernelTime(2 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, actualPlan_ale_advect_prevolmass%transfer,actualPlan_ale_advect_prevolmass%transfer2, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE