!
! auto-generated by op2.py
!

MODULE ALE_GETFVOL_VOL_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_getfvol_vol
SUBROUTINE ale_getfvol_vol(ndx01,ndx02,ndx03,ndx04, &
    & ndy01,ndy02,ndy03,ndy04,ndx11,ndx12,ndx13,ndx14, &
    & ndy11,ndy12,ndy13,ndy14,rdelv,cut)
    USE kinds_mod,ONLY: rlk,ink
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: ndx01,ndx02,ndx03,ndx04, &
    & ndy01,ndy02,ndy03,ndy04,ndx11,ndx12,ndx13,ndx14, &
    & ndy11,ndy12,ndy13,ndy14
    REAL(KIND=rlk) :: cut
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(OUT) :: rDelv
    INTEGER(KIND=ink) jj
    REAL(KIND=rlk) :: x1,x2,x3,x4,y1,y2,y3,y4,a1,a3,b1,b3

    !1.
    jj=1_ink
    x1=ndx01
    x2=ndx02
    y1=ndy01
    y2=ndy02
    x3=ndx12
    x4=ndx11
    y3=ndy12
    y4=ndy11
    a1=0.25_rlk*(-x1+x2+x3-x4)
    a3=0.25_rlk*(-x1-x2+x3+x4)
    b1=0.25_rlk*(-y1+y2+y3-y4)
    b3=0.25_rlk*(-y1-y2+y3+y4)
    rdelv(jj)=4.0_rlk*(a1*b3-a3*b1)
    IF (rdelv(jj).LT.cut) rdelv(jj)=0.0_rlk
    !2.
    jj=2_ink
    x1=ndx02
    x2=ndx03
    y1=ndy02
    y2=ndy03
    x3=ndx13
    x4=ndx12
    y3=ndy13
    y4=ndy12
    a1=0.25_rlk*(-x1+x2+x3-x4)
    a3=0.25_rlk*(-x1-x2+x3+x4)
    b1=0.25_rlk*(-y1+y2+y3-y4)
    b3=0.25_rlk*(-y1-y2+y3+y4)
    rdelv(jj)=4.0_rlk*(a1*b3-a3*b1)
    IF (rdelv(jj).LT.cut) rdelv(jj)=0.0_rlk
    !3.
    jj=3_ink
    x1=ndx03
    x2=ndx04
    y1=ndy03
    y2=ndy04
    x3=ndx14
    x4=ndx13
    y3=ndy14
    y4=ndy13
    a1=0.25_rlk*(-x1+x2+x3-x4)
    a3=0.25_rlk*(-x1-x2+x3+x4)
    b1=0.25_rlk*(-y1+y2+y3-y4)
    b3=0.25_rlk*(-y1-y2+y3+y4)
    rdelv(jj)=4.0_rlk*(a1*b3-a3*b1)
    IF (rdelv(jj).LT.cut) rdelv(jj)=0.0_rlk
    !4.
    jj=4_ink
    x1=ndx04
    x2=ndx01
    y1=ndy04
    y2=ndy01
    x3=ndx11
    x4=ndx14
    y3=ndy11
    y4=ndy14
    a1=0.25_rlk*(-x1+x2+x3-x4)
    a3=0.25_rlk*(-x1-x2+x3+x4)
    b1=0.25_rlk*(-y1+y2+y3-y4)
    b3=0.25_rlk*(-y1-y2+y3+y4)
    rdelv(jj)=4.0_rlk*(a1*b3-a3*b1)
    IF (rdelv(jj).LT.cut) rdelv(jj)=0.0_rlk

  END SUBROUTINE ale_getfvol_vol


SUBROUTINE op_wrap_ale_getfvol_vol( &
& opDat1Local, &
& opDat5Local, &
& opDat9Local, &
& opDat13Local, &
& opDat17Local, &
& opDat18Local, &
& opDat1Map, &
& opDat1MapDim, &
& bottom,top)
real(8) opDat1Local(1,*)
real(8) opDat5Local(1,*)
real(8) opDat9Local(1,*)
real(8) opDat13Local(1,*)
real(8) opDat17Local(4,*)
real(8) opDat18Local(1)
INTEGER(kind=4) opDat1Map(*)
INTEGER(kind=4) opDat1MapDim
INTEGER(kind=4) bottom,top,i1
INTEGER(kind=4) map1idx, map2idx, map3idx, map4idx

DO i1 = bottom, top-1, 1
  map1idx = opDat1Map(1 + i1 * opDat1MapDim + 0)+1
  map2idx = opDat1Map(1 + i1 * opDat1MapDim + 1)+1
  map3idx = opDat1Map(1 + i1 * opDat1MapDim + 2)+1
  map4idx = opDat1Map(1 + i1 * opDat1MapDim + 3)+1
! kernel call
CALL ale_getfvol_vol( &
  & opDat1Local(1,map1idx), &
  & opDat1Local(1,map2idx), &
  & opDat1Local(1,map3idx), &
  & opDat1Local(1,map4idx), &
  & opDat5Local(1,map1idx), &
  & opDat5Local(1,map2idx), &
  & opDat5Local(1,map3idx), &
  & opDat5Local(1,map4idx), &
  & opDat9Local(1,map1idx), &
  & opDat9Local(1,map2idx), &
  & opDat9Local(1,map3idx), &
  & opDat9Local(1,map4idx), &
  & opDat13Local(1,map1idx), &
  & opDat13Local(1,map2idx), &
  & opDat13Local(1,map3idx), &
  & opDat13Local(1,map4idx), &
  & opDat17Local(1,i1+1), &
  & opDat18Local(1) &
  & )
END DO
END SUBROUTINE
SUBROUTINE ale_getfvol_vol_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7, &
& opArg8, &
& opArg9, &
& opArg10, &
& opArg11, &
& opArg12, &
& opArg13, &
& opArg14, &
& opArg15, &
& opArg16, &
& opArg17, &
& opArg18 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7
type ( op_arg ) , INTENT(IN) :: opArg8
type ( op_arg ) , INTENT(IN) :: opArg9
type ( op_arg ) , INTENT(IN) :: opArg10
type ( op_arg ) , INTENT(IN) :: opArg11
type ( op_arg ) , INTENT(IN) :: opArg12
type ( op_arg ) , INTENT(IN) :: opArg13
type ( op_arg ) , INTENT(IN) :: opArg14
type ( op_arg ) , INTENT(IN) :: opArg15
type ( op_arg ) , INTENT(IN) :: opArg16
type ( op_arg ) , INTENT(IN) :: opArg17
type ( op_arg ) , INTENT(IN) :: opArg18

type ( op_arg ) , DIMENSION(18) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat1Map
INTEGER(kind=4) :: opDat1MapDim
real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat5Map
INTEGER(kind=4) :: opDat5MapDim
real(8), POINTER, DIMENSION(:) :: opDat5Local
INTEGER(kind=4) :: opDat5Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat9Map
INTEGER(kind=4) :: opDat9MapDim
real(8), POINTER, DIMENSION(:) :: opDat9Local
INTEGER(kind=4) :: opDat9Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat13Map
INTEGER(kind=4) :: opDat13MapDim
real(8), POINTER, DIMENSION(:) :: opDat13Local
INTEGER(kind=4) :: opDat13Cardinality

real(8), POINTER, DIMENSION(:) :: opDat17Local
INTEGER(kind=4) :: opDat17Cardinality

real(8), POINTER, DIMENSION(:) :: opDat18Local
INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
LOGICAL :: firstTime_ale_getfvol_vol = .TRUE.
type ( c_ptr )  :: planRet_ale_getfvol_vol
type ( op_plan ) , POINTER :: actualPlan_ale_getfvol_vol
INTEGER(kind=4), POINTER, DIMENSION(:) :: ncolblk_ale_getfvol_vol
INTEGER(kind=4), POINTER, DIMENSION(:) :: blkmap_ale_getfvol_vol
INTEGER(kind=4), POINTER, DIMENSION(:) :: nelems_ale_getfvol_vol
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_ale_getfvol_vol
INTEGER(kind=4), DIMENSION(1:18) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: blockOffset
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 18

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7
opArgArray(8) = opArg8
opArgArray(9) = opArg9
opArgArray(10) = opArg10
opArgArray(11) = opArg11
opArgArray(12) = opArg12
opArgArray(13) = opArg13
opArgArray(14) = opArg14
opArgArray(15) = opArg15
opArgArray(16) = opArg16
opArgArray(17) = opArg17
opArgArray(18) = opArg18

returnSetKernelTiming = setKernelTime(18 , userSubroutine//C_NULL_CHAR, &
& 0.0_8, 0.00000_4,0.00000_4, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  partitionSize = 0

  numberOfThreads = omp_get_max_threads()
  indirectionDescriptorArray(1) = 0
  indirectionDescriptorArray(2) = 0
  indirectionDescriptorArray(3) = 0
  indirectionDescriptorArray(4) = 0
  indirectionDescriptorArray(5) = 1
  indirectionDescriptorArray(6) = 1
  indirectionDescriptorArray(7) = 1
  indirectionDescriptorArray(8) = 1
  indirectionDescriptorArray(9) = 2
  indirectionDescriptorArray(10) = 2
  indirectionDescriptorArray(11) = 2
  indirectionDescriptorArray(12) = 2
  indirectionDescriptorArray(13) = 3
  indirectionDescriptorArray(14) = 3
  indirectionDescriptorArray(15) = 3
  indirectionDescriptorArray(16) = 3
  indirectionDescriptorArray(17) = -1
  indirectionDescriptorArray(18) = -1

  numberOfIndirectOpDats = 4

  planRet_ale_getfvol_vol = FortranPlanCaller( &
  & userSubroutine//C_NULL_CHAR, &
  & set%setCPtr, &
  & partitionSize, &
  & numberOfOpDats, &
  & opArgArray, &
  & numberOfIndirectOpDats, &
  & indirectionDescriptorArray,2)

  CALL c_f_pointer(planRet_ale_getfvol_vol,actualPlan_ale_getfvol_vol)
  CALL c_f_pointer(actualPlan_ale_getfvol_vol%ncolblk, &
&    ncolblk_ale_getfvol_vol,(/actualPlan_ale_getfvol_vol%ncolors_core/))
  CALL c_f_pointer(actualPlan_ale_getfvol_vol%blkmap, &
&    blkmap_ale_getfvol_vol,(/actualPlan_ale_getfvol_vol%nblocks/))
  CALL c_f_pointer(actualPlan_ale_getfvol_vol%offset,&
&    offset_ale_getfvol_vol,(/actualPlan_ale_getfvol_vol%nblocks/))
  CALL c_f_pointer(actualPlan_ale_getfvol_vol%nelems,&
&    nelems_ale_getfvol_vol,(/actualPlan_ale_getfvol_vol%nblocks/))

  opSetCore => set%setPtr

  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat1MapDim = getMapDimFromOpArg(opArg1)
  opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
  opDat5MapDim = getMapDimFromOpArg(opArg5)
  opDat9Cardinality = opArg9%dim * getSetSizeFromOpArg(opArg9)
  opDat9MapDim = getMapDimFromOpArg(opArg9)
  opDat13Cardinality = opArg13%dim * getSetSizeFromOpArg(opArg13)
  opDat13MapDim = getMapDimFromOpArg(opArg13)
  opDat17Cardinality = opArg17%dim * getSetSizeFromOpArg(opArg17)
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg1%map_data,opDat1Map,(/opSetCore%size*opDat1MapDim/))
  CALL c_f_pointer(opArg5%data,opDat5Local,(/opDat5Cardinality/))
  CALL c_f_pointer(opArg5%map_data,opDat5Map,(/opSetCore%size*opDat5MapDim/))
  CALL c_f_pointer(opArg9%data,opDat9Local,(/opDat9Cardinality/))
  CALL c_f_pointer(opArg9%map_data,opDat9Map,(/opSetCore%size*opDat9MapDim/))
  CALL c_f_pointer(opArg13%data,opDat13Local,(/opDat13Cardinality/))
  CALL c_f_pointer(opArg13%map_data,opDat13Map,(/opSetCore%size*opDat13MapDim/))
  CALL c_f_pointer(opArg17%data,opDat17Local,(/opDat17Cardinality/))
  CALL c_f_pointer(opArg18%data,opDat18Local, (/opArg18%dim/))


  blockOffset = 0

  DO i1 = 0, actualPlan_ale_getfvol_vol%ncolors-1, 1
    IF (i1 .EQ. actualPlan_ale_getfvol_vol%ncolors_core) THEN
      CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
    END IF

    nblocks = ncolblk_ale_getfvol_vol(i1 + 1)
    !$OMP PARALLEL DO private (threadID, blockID, nelem, offset_b)
    DO i2 = 0, nblocks-1, 1
      threadID = omp_get_thread_num()
      blockID = blkmap_ale_getfvol_vol(i2+blockOffset+1)
      nelem = nelems_ale_getfvol_vol(blockID+1)
      offset_b = offset_ale_getfvol_vol(blockID+1)
      CALL op_wrap_ale_getfvol_vol( &
      & opDat1Local, &
      & opDat5Local, &
      & opDat9Local, &
      & opDat13Local, &
      & opDat17Local, &
      & opDat18Local, &
      & opDat1Map, &
      & opDat1MapDim, &
      & offset_b, offset_b+nelem)
    END DO
    !$OMP END PARALLEL DO
    blockOffset = blockOffset + nblocks
  END DO
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(18 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, actualPlan_ale_getfvol_vol%transfer,actualPlan_ale_getfvol_vol%transfer2, 1)
END SUBROUTINE
END MODULE