!
! auto-generated by op2.py
!

MODULE ALE_ADVECT_POSTMASS_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! ale_advect_postmassvariable declarations

INTEGER(kind=4) :: opDat3_stride_OP2CONSTANT
!$acc declare create(opDat3_stride_OP2CONSTANT)
INTEGER(kind=4) :: direct_stride_OP2CONSTANT
!$acc declare create(direct_stride_OP2CONSTANT)

#define OP2_SOA(var,dim,stride) var((dim-1)*stride+1)

CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_advect_postmass
SUBROUTINE ale_advect_postmass_gpu(cnm1,flux, &
&             elv0ndm11,elv0ndm12,elv0ndm13,elv0ndm14)
!$acc routine seq
    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: flux
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(INOUT) :: cnm1
    REAL(KIND=rlk), INTENT(INOUT) :: elv0ndm11,elv0ndm12,elv0ndm13,elv0ndm14

    cnm1(1)=cnm1(1)+flux(1)
    cnm1(2)=cnm1(2)+flux(2)
    cnm1(3)=cnm1(3)+flux(3)
    cnm1(4)=cnm1(4)+flux(4)
    elv0ndm11=elv0ndm11+flux(1)
    elv0ndm12=elv0ndm12+flux(2)
    elv0ndm13=elv0ndm13+flux(3)
    elv0ndm14=elv0ndm14+flux(4)

  END SUBROUTINE ale_advect_postmass_gpu


SUBROUTINE op_wrap_ale_advect_postmass( &
& opDat3Local, &
& opDat1Local, &
& opDat2Local, &
& opDat3Map, &
& opDat3MapDim, &
& col_reord, set_size, &
& bottom,top)
implicit none
real(8) opDat3Local(1,*)
real(8) opDat1Local(*)
real(8) opDat2Local(*)
INTEGER(kind=4) opDat3Map(*)
INTEGER(kind=4) opDat3MapDim
INTEGER(kind=4) col_reord(*)
INTEGER(kind=4) set_size

INTEGER(kind=4) bottom,top,i1,i2
INTEGER(kind=4) map3idx, map4idx, map5idx, map6idx


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat3Local) &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat2Local) &
!$acc& deviceptr(opDat3Map) &
!$acc& deviceptr(col_reord) private(i1) &
!$acc& private(map3idx) &
!$acc& private(map4idx) &
!$acc& private(map5idx) &
!$acc& private(map6idx) 
DO i2 = bottom, top-1, 1
  i1 = col_reord(i2+1)
  map3idx = opDat3Map(1 + i1 + set_size * 0)+1
  map4idx = opDat3Map(1 + i1 + set_size * 1)+1
  map5idx = opDat3Map(1 + i1 + set_size * 2)+1
  map6idx = opDat3Map(1 + i1 + set_size * 3)+1
! kernel call
  CALL ale_advect_postmass_gpu( &
  & opDat1Local(i1+1), &
  & opDat2Local(i1+1), &
  & opDat3Local(1,map3idx), &
  & opDat3Local(1,map4idx), &
  & opDat3Local(1,map5idx), &
  & opDat3Local(1,map6idx) &
  & )
END DO

END SUBROUTINE
SUBROUTINE ale_advect_postmass_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6

type ( op_arg ) , DIMENSION(6) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat3Map
INTEGER(kind=4) :: opDat3MapDim
real(8), POINTER, DIMENSION(:) :: opDat3Local
INTEGER(kind=4) :: opDat3Cardinality

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: exec_size
LOGICAL :: firstTime_ale_advect_postmass = .TRUE.
type ( c_ptr )  :: planRet_ale_advect_postmass
type ( op_plan ) , POINTER :: actualPlan_ale_advect_postmass
INTEGER(kind=4), POINTER, DIMENSION(:) :: col_reord_ale_advect_postmass
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_ale_advect_postmass
INTEGER(kind=4), DIMENSION(1:6) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 6

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6

returnSetKernelTiming = setKernelTime(6 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
IF ((calledTimes.EQ.0).OR.(opDat3_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg3))) THEN
  opDat3_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg3)
  !$acc update device(opDat3_stride_OP2CONSTANT)
END IF
IF ((calledTimes.EQ.0).OR.(direct_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg1))) THEN
  direct_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg1)
  !$acc update device(direct_stride_OP2CONSTANT)
END IF
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

indirectionDescriptorArray(1) = -1
indirectionDescriptorArray(2) = -1
indirectionDescriptorArray(3) = 0
indirectionDescriptorArray(4) = 0
indirectionDescriptorArray(5) = 0
indirectionDescriptorArray(6) = 0

exec_size = opSetCore%size + opSetCore%exec_size
numberOfIndirectOpDats = 1

planRet_ale_advect_postmass = FortranPlanCaller( &
& userSubroutine//C_NULL_CHAR, &
& set%setCPtr, &
& partitionSize, &
& numberOfOpDats, &
& opArgArray, &
& numberOfIndirectOpDats, &
& indirectionDescriptorArray,4)

CALL c_f_pointer(planRet_ale_advect_postmass,actualPlan_ale_advect_postmass)
CALL c_f_pointer(actualPlan_ale_advect_postmass%col_reord,col_reord_ale_advect_postmass,(/exec_size/))
CALL c_f_pointer(actualPlan_ale_advect_postmass%color2_offsets,offset_ale_advect_postmass,(/actualPlan_ale_advect_postmass%ncolors+1/))
opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
opDat3MapDim = getMapDimFromOpArg(opArg3)
opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
CALL c_f_pointer(opArg3%data_d,opDat3Local,(/opDat3Cardinality/))
CALL c_f_pointer(opArg3%map_data_d,opDat3Map,(/exec_size*opDat3MapDim/))
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg2%data_d,opDat2Local,(/opDat2Cardinality/))



DO i1 = 0, actualPlan_ale_advect_postmass%ncolors-1, 1
  IF (i1 .EQ. 1) THEN
    CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
  END IF

  offset_b = offset_ale_advect_postmass(i1 + 1)
  nelem = offset_ale_advect_postmass(i1 + 1 + 1)
  CALL op_wrap_ale_advect_postmass( &
  & opDat3Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Map, &
  & opDat3MapDim, &
  & col_reord_ale_advect_postmass, exec_size, offset_b, nelem )
END DO
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

returnSetKernelTiming = setKernelTime(6 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, actualPlan_ale_advect_postmass%transfer,actualPlan_ale_advect_postmass%transfer2, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE