!
! auto-generated by op2.py
!

MODULE ALE_UPDATE_RHO_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! ale_update_rhovariable declarations



CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_update_rho
SUBROUTINE ale_update_rho_gpu(rho,elmass,elvol)
!$acc routine seq
      USE kinds_mod,ONLY: rlk

      implicit none
      REAL(KIND=rlk), INTENT(IN) :: elmass,elvol
      REAL(KIND=rlk), INTENT(OUT) :: rho

      rho=elmass/elvol
    END SUBROUTINE ale_update_rho_gpu


SUBROUTINE op_wrap_ale_update_rho( &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& bottom,top)
implicit none
real(8) opDat1Local(1,*)
real(8) opDat2Local(1,*)
real(8) opDat3Local(1,*)

INTEGER(kind=4) bottom,top,i1,i2


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat2Local) &
!$acc& deviceptr(opDat3Local) 
DO i1 = bottom, top-1, 1
! kernel call
  CALL ale_update_rho_gpu( &
  & opDat1Local(1,i1+1), &
  & opDat2Local(1,i1+1), &
  & opDat3Local(1,i1+1) &
  & )
END DO

END SUBROUTINE
SUBROUTINE ale_update_rho_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3

type ( op_arg ) , DIMENSION(3) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat3Local
INTEGER(kind=4) :: opDat3Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: sliceStart
INTEGER(kind=4) :: sliceEnd
REAL(kind=4) :: dataTransfer


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 3

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3

returnSetKernelTiming = setKernelTime(20 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg2%data_d,opDat2Local,(/opDat2Cardinality/))
CALL c_f_pointer(opArg3%data_d,opDat3Local,(/opDat3Cardinality/))


sliceStart = 0
sliceEnd = opSetCore%size
CALL op_wrap_ale_update_rho( &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& sliceStart, sliceEnd)
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

dataTransfer = 0.0
dataTransfer = dataTransfer + opArg1%size * getSetSizeFromOpArg(opArg1)
dataTransfer = dataTransfer + opArg2%size * getSetSizeFromOpArg(opArg2)
dataTransfer = dataTransfer + opArg3%size * getSetSizeFromOpArg(opArg3)
returnSetKernelTiming = setKernelTime(20 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, dataTransfer, 0.00000_4, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE