!
! auto-generated by op2.py
!

MODULE ALE_ADVECT_VOLMASS_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! ale_advect_volmassvariable declarations

INTEGER(kind=4) :: opDat2_stride_OP2CONSTANT
!$acc declare create(opDat2_stride_OP2CONSTANT)
INTEGER(kind=4) :: direct_stride_OP2CONSTANT
!$acc declare create(direct_stride_OP2CONSTANT)

#define OP2_SOA(var,dim,stride) var((dim-1)*stride+1)

CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_advect_volmass
SUBROUTINE ale_advect_volmass_gpu(delv,delv1,delv2,delv3, delv4, &
&       delm,delm1,delm2,delm3,delm4,dndv,dndm,flux,ielsd,ielel,iel,i1)
!$acc routine seq
    USE kinds_mod,ONLY: rlk, ink
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: delv,delv1,delv2,delv3, delv4, &
&       delm,delm1,delm2,delm3,delm4
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(INOUT) :: flux
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(OUT) :: dndv,dndm
    INTEGER(KIND=ink), DIMENSION(N_SHAPE), INTENT(IN) :: ielel,ielsd
    INTEGER(KIND=ink), INTENT(IN) :: iel
    INTEGER(KIND=ink) :: i1

    INTEGER(KIND=ink) :: i2,ie1,ie2,is1,is2
    REAL(KIND=rlk)  :: w1,w2,w3,w4

    i2 = i1+2_ink

    ie1=OP2_SOA(ielel,i1, direct_stride_OP2CONSTANT)
    ie2=OP2_SOA(ielel,i2, direct_stride_OP2CONSTANT)
    is1=OP2_SOA(ielsd,i1, direct_stride_OP2CONSTANT)
    is2=OP2_SOA(ielsd,i2, direct_stride_OP2CONSTANT)
    IF (i1.EQ.1) THEN !i1 may only be 1 or 2, so that i2<=4
      w1=OP2_SOA(delv1,is1, opDat2_stride_OP2CONSTANT)
      w2=OP2_SOA(delv3,is2, opDat2_stride_OP2CONSTANT)
      w3=OP2_SOA(delm1,is1, opDat2_stride_OP2CONSTANT)
      w4=OP2_SOA(delm3,is2, opDat2_stride_OP2CONSTANT)
    ELSEIF (i1.EQ.2) THEN
      w1=OP2_SOA(delv2,is1, opDat2_stride_OP2CONSTANT)
      w2=OP2_SOA(delv4,is2, opDat2_stride_OP2CONSTANT)
      w3=OP2_SOA(delm2,is1, opDat2_stride_OP2CONSTANT)
      w4=OP2_SOA(delm4,is2, opDat2_stride_OP2CONSTANT)
    ENDIF

    IF (ie1.EQ.iel) THEN !i.e. boundary
      w1=0.0_rlk
      w3=0.0_rlk
    ENDIF
    IF (ie2.EQ.iel) THEN !i.e. boundary
      w2=0.0_rlk
      w4=0.0_rlk
    ENDIF
    w1=w1-OP2_SOA(delv,i1, direct_stride_OP2CONSTANT)
    w2=w2-OP2_SOA(delv,i2, direct_stride_OP2CONSTANT)
    w1=0.25_rlk*(w1-w2)
    OP2_SOA(dndv,i1, direct_stride_OP2CONSTANT)=w1
    OP2_SOA(dndv,i2, direct_stride_OP2CONSTANT)=w1
    w1=w3-OP2_SOA(delm,i1, direct_stride_OP2CONSTANT)
    w2=w4-OP2_SOA(delm,i2, direct_stride_OP2CONSTANT)
    w3=0.25_rlk*(w1-w2)
    OP2_SOA(dndm,i1, direct_stride_OP2CONSTANT)=w3
    OP2_SOA(dndm,i2, direct_stride_OP2CONSTANT)=w3
    w3=0.25_rlk*(w1+w2)
    OP2_SOA(flux,1, direct_stride_OP2CONSTANT)=OP2_SOA(flux,1, direct_stride_OP2CONSTANT)+w3
    OP2_SOA(flux,2, direct_stride_OP2CONSTANT)=OP2_SOA(flux,2, direct_stride_OP2CONSTANT)+w3
    OP2_SOA(flux,3, direct_stride_OP2CONSTANT)=OP2_SOA(flux,3, direct_stride_OP2CONSTANT)+w3
    OP2_SOA(flux,4, direct_stride_OP2CONSTANT)=OP2_SOA(flux,4, direct_stride_OP2CONSTANT)+w3
  END SUBROUTINE ale_advect_volmass_gpu


SUBROUTINE op_wrap_ale_advect_volmass( &
& opDat2Local, &
& opDat7Local, &
& opDat1Local, &
& opDat6Local, &
& opDat11Local, &
& opDat12Local, &
& opDat13Local, &
& opDat14Local, &
& opDat15Local, &
& opDat16Local, &
& opDat17Local, &
& opDat2Map, &
& opDat2MapDim, &
& col_reord, set_size, &
& bottom,top)
implicit none
real(8) opDat2Local(*)
real(8) opDat7Local(*)
real(8) opDat1Local(*)
real(8) opDat6Local(*)
real(8) opDat11Local(*)
real(8) opDat12Local(*)
real(8) opDat13Local(*)
integer(4) opDat14Local(*)
integer(4) opDat15Local(*)
integer(4) opDat16Local(1,*)
integer(4) opDat17Local(1)
INTEGER(kind=4) opDat2Map(*)
INTEGER(kind=4) opDat2MapDim
INTEGER(kind=4) col_reord(*)
INTEGER(kind=4) set_size

INTEGER(kind=4) bottom,top,i1,i2
INTEGER(kind=4) map2idx, map3idx, map4idx, map5idx


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat2Local) &
!$acc& deviceptr(opDat7Local) &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat6Local) &
!$acc& deviceptr(opDat11Local) &
!$acc& deviceptr(opDat12Local) &
!$acc& deviceptr(opDat13Local) &
!$acc& deviceptr(opDat14Local) &
!$acc& deviceptr(opDat15Local) &
!$acc& deviceptr(opDat16Local) &
!$acc& deviceptr(opDat2Map) &
!$acc& deviceptr(col_reord) private(i1) &
!$acc& private(map2idx) &
!$acc& private(map3idx) &
!$acc& private(map4idx) &
!$acc& private(map5idx) 
DO i2 = bottom, top-1, 1
  i1 = col_reord(i2+1)
  map2idx = opDat2Map(1 + i1 + set_size * 0)+1
  map3idx = opDat2Map(1 + i1 + set_size * 1)+1
  map4idx = opDat2Map(1 + i1 + set_size * 2)+1
  map5idx = opDat2Map(1 + i1 + set_size * 3)+1
! kernel call
  CALL ale_advect_volmass_gpu( &
  & opDat1Local(i1+1), &
  & opDat2Local(map2idx), &
  & opDat2Local(map3idx), &
  & opDat2Local(map4idx), &
  & opDat2Local(map5idx), &
  & opDat6Local(i1+1), &
  & opDat7Local(map2idx), &
  & opDat7Local(map3idx), &
  & opDat7Local(map4idx), &
  & opDat7Local(map5idx), &
  & opDat11Local(i1+1), &
  & opDat12Local(i1+1), &
  & opDat13Local(i1+1), &
  & opDat14Local(i1+1), &
  & opDat15Local(i1+1), &
  & opDat16Local(1,i1+1), &
  & opDat17Local(1) &
  & )
END DO

END SUBROUTINE
SUBROUTINE ale_advect_volmass_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7, &
& opArg8, &
& opArg9, &
& opArg10, &
& opArg11, &
& opArg12, &
& opArg13, &
& opArg14, &
& opArg15, &
& opArg16, &
& opArg17 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7
type ( op_arg ) , INTENT(IN) :: opArg8
type ( op_arg ) , INTENT(IN) :: opArg9
type ( op_arg ) , INTENT(IN) :: opArg10
type ( op_arg ) , INTENT(IN) :: opArg11
type ( op_arg ) , INTENT(IN) :: opArg12
type ( op_arg ) , INTENT(IN) :: opArg13
type ( op_arg ) , INTENT(IN) :: opArg14
type ( op_arg ) , INTENT(IN) :: opArg15
type ( op_arg ) , INTENT(IN) :: opArg16
type ( op_arg ) , INTENT(IN) :: opArg17

type ( op_arg ) , DIMENSION(17) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat2Map
INTEGER(kind=4) :: opDat2MapDim
real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat7Map
INTEGER(kind=4) :: opDat7MapDim
real(8), POINTER, DIMENSION(:) :: opDat7Local
INTEGER(kind=4) :: opDat7Cardinality

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat6Local
INTEGER(kind=4) :: opDat6Cardinality

real(8), POINTER, DIMENSION(:) :: opDat11Local
INTEGER(kind=4) :: opDat11Cardinality

real(8), POINTER, DIMENSION(:) :: opDat12Local
INTEGER(kind=4) :: opDat12Cardinality

real(8), POINTER, DIMENSION(:) :: opDat13Local
INTEGER(kind=4) :: opDat13Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat14Local
INTEGER(kind=4) :: opDat14Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat15Local
INTEGER(kind=4) :: opDat15Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat16Local
INTEGER(kind=4) :: opDat16Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat17Local
INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: exec_size
LOGICAL :: firstTime_ale_advect_volmass = .TRUE.
type ( c_ptr )  :: planRet_ale_advect_volmass
type ( op_plan ) , POINTER :: actualPlan_ale_advect_volmass
INTEGER(kind=4), POINTER, DIMENSION(:) :: col_reord_ale_advect_volmass
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_ale_advect_volmass
INTEGER(kind=4), DIMENSION(1:17) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 17

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7
opArgArray(8) = opArg8
opArgArray(9) = opArg9
opArgArray(10) = opArg10
opArgArray(11) = opArg11
opArgArray(12) = opArg12
opArgArray(13) = opArg13
opArgArray(14) = opArg14
opArgArray(15) = opArg15
opArgArray(16) = opArg16
opArgArray(17) = opArg17

returnSetKernelTiming = setKernelTime(4 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
IF ((calledTimes.EQ.0).OR.(opDat2_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg2))) THEN
  opDat2_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg2)
  !$acc update device(opDat2_stride_OP2CONSTANT)
END IF
IF ((calledTimes.EQ.0).OR.(direct_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg1))) THEN
  direct_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg1)
  !$acc update device(direct_stride_OP2CONSTANT)
END IF
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

indirectionDescriptorArray(1) = -1
indirectionDescriptorArray(2) = 0
indirectionDescriptorArray(3) = 0
indirectionDescriptorArray(4) = 0
indirectionDescriptorArray(5) = 0
indirectionDescriptorArray(6) = -1
indirectionDescriptorArray(7) = 1
indirectionDescriptorArray(8) = 1
indirectionDescriptorArray(9) = 1
indirectionDescriptorArray(10) = 1
indirectionDescriptorArray(11) = -1
indirectionDescriptorArray(12) = -1
indirectionDescriptorArray(13) = -1
indirectionDescriptorArray(14) = -1
indirectionDescriptorArray(15) = -1
indirectionDescriptorArray(16) = -1
indirectionDescriptorArray(17) = -1

exec_size = opSetCore%size + opSetCore%exec_size
numberOfIndirectOpDats = 2
partitionSize = 0

planRet_ale_advect_volmass = FortranPlanCaller( &
& userSubroutine//C_NULL_CHAR, &
& set%setCPtr, &
& partitionSize, &
& numberOfOpDats, &
& opArgArray, &
& numberOfIndirectOpDats, &
& indirectionDescriptorArray,4)

CALL c_f_pointer(planRet_ale_advect_volmass,actualPlan_ale_advect_volmass)
CALL c_f_pointer(actualPlan_ale_advect_volmass%col_reord,col_reord_ale_advect_volmass,(/exec_size/))
CALL c_f_pointer(actualPlan_ale_advect_volmass%color2_offsets,offset_ale_advect_volmass,(/actualPlan_ale_advect_volmass%ncolors+1/))
opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
opDat2MapDim = getMapDimFromOpArg(opArg2)
opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
opDat7MapDim = getMapDimFromOpArg(opArg7)
opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
opDat11Cardinality = opArg11%dim * getSetSizeFromOpArg(opArg11)
opDat12Cardinality = opArg12%dim * getSetSizeFromOpArg(opArg12)
opDat13Cardinality = opArg13%dim * getSetSizeFromOpArg(opArg13)
opDat14Cardinality = opArg14%dim * getSetSizeFromOpArg(opArg14)
opDat15Cardinality = opArg15%dim * getSetSizeFromOpArg(opArg15)
opDat16Cardinality = opArg16%dim * getSetSizeFromOpArg(opArg16)
CALL c_f_pointer(opArg2%data_d,opDat2Local,(/opDat2Cardinality/))
CALL c_f_pointer(opArg2%map_data_d,opDat2Map,(/exec_size*opDat2MapDim/))
CALL c_f_pointer(opArg7%data_d,opDat7Local,(/opDat7Cardinality/))
CALL c_f_pointer(opArg7%map_data_d,opDat7Map,(/exec_size*opDat7MapDim/))
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg6%data_d,opDat6Local,(/opDat6Cardinality/))
CALL c_f_pointer(opArg11%data_d,opDat11Local,(/opDat11Cardinality/))
CALL c_f_pointer(opArg12%data_d,opDat12Local,(/opDat12Cardinality/))
CALL c_f_pointer(opArg13%data_d,opDat13Local,(/opDat13Cardinality/))
CALL c_f_pointer(opArg14%data_d,opDat14Local,(/opDat14Cardinality/))
CALL c_f_pointer(opArg15%data_d,opDat15Local,(/opDat15Cardinality/))
CALL c_f_pointer(opArg16%data_d,opDat16Local,(/opDat16Cardinality/))
CALL c_f_pointer(opArg17%data,opDat17Local, (/opArg17%dim/))



DO i1 = 0, actualPlan_ale_advect_volmass%ncolors-1, 1
  IF (i1 .EQ. 1) THEN
    CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
  END IF

  offset_b = offset_ale_advect_volmass(i1 + 1)
  nelem = offset_ale_advect_volmass(i1 + 1 + 1)
  CALL op_wrap_ale_advect_volmass( &
  & opDat2Local, &
  & opDat7Local, &
  & opDat1Local, &
  & opDat6Local, &
  & opDat11Local, &
  & opDat12Local, &
  & opDat13Local, &
  & opDat14Local, &
  & opDat15Local, &
  & opDat16Local, &
  & opDat17Local(1), &
  & opDat2Map, &
  & opDat2MapDim, &
  & col_reord_ale_advect_volmass, exec_size, offset_b, nelem )
END DO
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

returnSetKernelTiming = setKernelTime(4 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, actualPlan_ale_advect_volmass%transfer,actualPlan_ale_advect_volmass%transfer2, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE