!
! auto-generated by op2.py
!

MODULE ALE_ADVECT_POSTMASS_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_advect_postmass
SUBROUTINE ale_advect_postmass(cnm1,flux, &
&             elv0ndm11,elv0ndm12,elv0ndm13,elv0ndm14)
    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: flux
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(INOUT) :: cnm1
    REAL(KIND=rlk), INTENT(INOUT) :: elv0ndm11,elv0ndm12,elv0ndm13,elv0ndm14

    cnm1(1)=cnm1(1)+flux(1)
    cnm1(2)=cnm1(2)+flux(2)
    cnm1(3)=cnm1(3)+flux(3)
    cnm1(4)=cnm1(4)+flux(4)
    elv0ndm11=elv0ndm11+flux(1)
    elv0ndm12=elv0ndm12+flux(2)
    elv0ndm13=elv0ndm13+flux(3)
    elv0ndm14=elv0ndm14+flux(4)

  END SUBROUTINE ale_advect_postmass


SUBROUTINE op_wrap_ale_advect_postmass( &
  & opDat3Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Map, &
  & opDat3MapDim, &
  & bottom,top)
  real(8) opDat3Local(1,*)
  real(8) opDat1Local(4,*)
  real(8) opDat2Local(4,*)
  INTEGER(kind=4) opDat3Map(*)
  INTEGER(kind=4) opDat3MapDim
  INTEGER(kind=4) bottom,top,i1
  INTEGER(kind=4) map3idx, map4idx, map5idx, map6idx

  DO i1 = bottom, top-1, 1
    map3idx = opDat3Map(1 + i1 * opDat3MapDim + 0)+1
    map4idx = opDat3Map(1 + i1 * opDat3MapDim + 1)+1
    map5idx = opDat3Map(1 + i1 * opDat3MapDim + 2)+1
    map6idx = opDat3Map(1 + i1 * opDat3MapDim + 3)+1
! kernel call
  CALL ale_advect_postmass( &
    & opDat1Local(1,i1+1), &
    & opDat2Local(1,i1+1), &
    & opDat3Local(1,map3idx), &
    & opDat3Local(1,map4idx), &
    & opDat3Local(1,map5idx), &
    & opDat3Local(1,map6idx) &
    & )
  END DO
END SUBROUTINE
SUBROUTINE ale_advect_postmass_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4
  type ( op_arg ) , INTENT(IN) :: opArg5
  type ( op_arg ) , INTENT(IN) :: opArg6

  type ( op_arg ) , DIMENSION(6) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
  REAL(kind=8) :: startTime
  REAL(kind=8) :: endTime
  INTEGER(kind=4) :: returnSetKernelTiming
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat3Map
  INTEGER(kind=4) :: opDat3MapDim
  real(8), POINTER, DIMENSION(:) :: opDat3Local
  INTEGER(kind=4) :: opDat3Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat2Local
  INTEGER(kind=4) :: opDat2Cardinality


  INTEGER(kind=4) :: i1

  numberOfOpDats = 6

  opArgArray(1) = opArg1
  opArgArray(2) = opArg2
  opArgArray(3) = opArg3
  opArgArray(4) = opArg4
  opArgArray(5) = opArg5
  opArgArray(6) = opArg6

  returnSetKernelTiming = setKernelTime(6 , userSubroutine//C_NULL_CHAR, &
  & 0.0_8, 0.00000_4,0.00000_4, 0)
  call op_timers_core(startTime)

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  opSetCore => set%setPtr

  opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
  opDat3MapDim = getMapDimFromOpArg(opArg3)
  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  CALL c_f_pointer(opArg3%data,opDat3Local,(/opDat3Cardinality/))
  CALL c_f_pointer(opArg3%map_data,opDat3Map,(/opSetCore%size*opDat3MapDim/))
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))


  CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  CALL op_wrap_ale_advect_postmass( &
  & opDat3Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Map, &
  & opDat3MapDim, &
  & 0, n_upper)

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(6 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime,0.00000_4,0.00000_4, 1)
END SUBROUTINE
END MODULE