!
! auto-generated by op2.py
!

MODULE ALE_ADVECTORS_TOTFLUX_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_advectors_totflux
SUBROUTINE ale_advectors_totflux(rFlux,rTotFlux1,rTotFlux2,rTotFlux3,rTotFlux4)
    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: rFlux
    REAL(KIND=rlk), INTENT(INOUT) :: rTotFlux1,rTotFlux2,rTotFlux3,rTotFlux4

    rTotFlux1 = rTotFlux1 + rFlux(1)
    rTotFlux2 = rTotFlux2 + rFlux(2)
    rTotFlux3 = rTotFlux3 + rFlux(3)
    rTotFlux4 = rTotFlux4 + rFlux(4)

  END SUBROUTINE ale_advectors_totflux


SUBROUTINE op_wrap_ale_advectors_totflux( &
& opDat2Local, &
& opDat1Local, &
& opDat2Map, &
& opDat2MapDim, &
& bottom,top)
real(8) opDat2Local(1,*)
real(8) opDat1Local(4,*)
INTEGER(kind=4) opDat2Map(*)
INTEGER(kind=4) opDat2MapDim
INTEGER(kind=4) bottom,top,i1
INTEGER(kind=4) map2idx, map3idx, map4idx, map5idx

DO i1 = bottom, top-1, 1
  map2idx = opDat2Map(1 + i1 * opDat2MapDim + 0)+1
  map3idx = opDat2Map(1 + i1 * opDat2MapDim + 1)+1
  map4idx = opDat2Map(1 + i1 * opDat2MapDim + 2)+1
  map5idx = opDat2Map(1 + i1 * opDat2MapDim + 3)+1
! kernel call
CALL ale_advectors_totflux( &
  & opDat1Local(1,i1+1), &
  & opDat2Local(1,map2idx), &
  & opDat2Local(1,map3idx), &
  & opDat2Local(1,map4idx), &
  & opDat2Local(1,map5idx) &
  & )
END DO
END SUBROUTINE
SUBROUTINE ale_advectors_totflux_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5

type ( op_arg ) , DIMENSION(5) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat2Map
INTEGER(kind=4) :: opDat2MapDim
real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
LOGICAL :: firstTime_ale_advectors_totflux = .TRUE.
type ( c_ptr )  :: planRet_ale_advectors_totflux
type ( op_plan ) , POINTER :: actualPlan_ale_advectors_totflux
INTEGER(kind=4), POINTER, DIMENSION(:) :: ncolblk_ale_advectors_totflux
INTEGER(kind=4), POINTER, DIMENSION(:) :: blkmap_ale_advectors_totflux
INTEGER(kind=4), POINTER, DIMENSION(:) :: nelems_ale_advectors_totflux
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_ale_advectors_totflux
INTEGER(kind=4), DIMENSION(1:5) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: blockOffset
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 5

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5

returnSetKernelTiming = setKernelTime(13 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  partitionSize = 0

  numberOfThreads = omp_get_max_threads()
  indirectionDescriptorArray(1) = -1
  indirectionDescriptorArray(2) = 0
  indirectionDescriptorArray(3) = 0
  indirectionDescriptorArray(4) = 0
  indirectionDescriptorArray(5) = 0

  numberOfIndirectOpDats = 1

  planRet_ale_advectors_totflux = FortranPlanCaller( &
  & userSubroutine//C_NULL_CHAR, &
  & set%setCPtr, &
  & partitionSize, &
  & numberOfOpDats, &
  & opArgArray, &
  & numberOfIndirectOpDats, &
  & indirectionDescriptorArray,2)

  CALL c_f_pointer(planRet_ale_advectors_totflux,actualPlan_ale_advectors_totflux)
  CALL c_f_pointer(actualPlan_ale_advectors_totflux%ncolblk,ncolblk_ale_advectors_totflux,(/actualPlan_ale_advectors_totflux%ncolors_core/))
  CALL c_f_pointer(actualPlan_ale_advectors_totflux%blkmap,blkmap_ale_advectors_totflux,(/actualPlan_ale_advectors_totflux%nblocks/))
  CALL c_f_pointer(actualPlan_ale_advectors_totflux%offset,offset_ale_advectors_totflux,(/actualPlan_ale_advectors_totflux%nblocks/))
  CALL c_f_pointer(actualPlan_ale_advectors_totflux%nelems,nelems_ale_advectors_totflux,(/actualPlan_ale_advectors_totflux%nblocks/))

  opSetCore => set%setPtr

  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat2MapDim = getMapDimFromOpArg(opArg2)
  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg2%map_data,opDat2Map,(/opSetCore%size*opDat2MapDim/))
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))


  blockOffset = 0

  DO i1 = 0, actualPlan_ale_advectors_totflux%ncolors-1, 1
    IF (i1 .EQ. actualPlan_ale_advectors_totflux%ncolors_core) THEN
      CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
    END IF

    nblocks = ncolblk_ale_advectors_totflux(i1 + 1)
    !$OMP PARALLEL DO private (threadID, blockID, nelem, offset_b)
    DO i2 = 0, nblocks-1, 1
      threadID = omp_get_thread_num()
      blockID = blkmap_ale_advectors_totflux(i2+blockOffset+1)
      nelem = nelems_ale_advectors_totflux(blockID+1)
      offset_b = offset_ale_advectors_totflux(blockID+1)
      CALL op_wrap_ale_advectors_totflux( &
      & opDat2Local, &
      & opDat1Local, &
      & opDat2Map, &
      & opDat2MapDim, &
      & offset_b, offset_b+nelem)
    END DO
    !$OMP END PARALLEL DO
    blockOffset = blockOffset + nblocks
  END DO
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(13 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, actualPlan_ale_advectors_totflux%transfer,actualPlan_ale_advectors_totflux%transfer2, 1)
END SUBROUTINE
END MODULE