!
! auto-generated by op2_fortran.py
!


!Crown Copyright 2014 AWE.
!
! This file is part of Bookleaf.
!
! Bookleaf is free software: you can redistribute it and/or modify it under
! the terms of the GNU General Public License as published by the
! Free Software Foundation, either version 3 of the License, or (at your option)
! any later version.
!
! Bookleaf is distributed in the hope that it will be useful, but
! WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
! FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
! details.
!
! You should have received a copy of the GNU General Public License along with
! Bookleaf. If not, see http://www.gnu.org/licenses/.

MODULE ale_getfvol_mod

  USE kinds_mod,ONLY: ink,lok,rlk
  use SET_ZERO4_MODULE
  use A_EQ_B_MODULE
  use ALE_GETFVOL_MIN1_MODULE
  use ALE_GETFVOL_NEWPOS_MODULE
  use ALE_GETFVOL_VOL_MODULE
   USE op2_bookleaf
  IMPLICIT NONE

  PRIVATE :: fvol
  PUBLIC  :: alegetfvol

CONTAINS

  SUBROUTINE alegetfvol(nshape,nnod,nel,nel2,dt,cut,d_indstatus,d_ndx,d_ndy,d_ndux,d_ndvy,d_rdelv)

    USE kinds_mod,    ONLY: ink,rlk
    USE logicals_mod, ONLY: zeul
    USE timers_mod,   ONLY: bookleaf_times,get_time
    USE op2_bookleaf, ONLY: s_nodes
        use OP2_Fortran_RT_Support
    ! USE common_kernels
    ! USE USE ale_getfvol_kernels

    ! Argument list
    INTEGER(KIND=ink),                       INTENT(IN)   :: nshape,nel,&
&                                                            nnod,nel2
    REAL(KIND=rlk),                          INTENT(IN)   :: dt,cut
    type(op_dat) :: d_indstatus,d_ndx,d_ndy,d_ndux,d_ndvy,d_rdelv
    ! Local
    INTEGER(KIND=ink) :: iNd
    REAL(KIND=rlk)    :: t0,t1,m1


    ! Timer
    t0=get_time()


    ! calculate mesh velocity
    IF (zeul) THEN
      call ale_getfvol_min1_host(&
                       & "ale_getfvol_min1",s_nodes,  &
                       & op_arg_dat(d_ndux,-1,OP_ID,1,'real(8)',OP_RW),  &
                       & op_arg_dat(d_ndvy,-1,OP_ID,1,'real(8)',OP_RW))

    ELSE
      !# Exchange MESH_MOTION ndx,ndy, Ndux,ndvy to nnod1
      ! Other options
    ENDIF

    ! construct new position
    call ale_getfvol_newpos_host(&
                     & "ale_getfvol_newpos",s_nodes,  &
                     & op_arg_dat(d_ndux,-1,OP_ID,1,'real(8)',OP_RW),  &
                     & op_arg_dat(d_ndvy,-1,OP_ID,1,'real(8)',OP_RW),  &
                     & op_arg_dat(d_ndx,-1,OP_ID,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndy,-1,OP_ID,1,'real(8)',OP_READ),  &
                     & op_arg_gbl(dt,1,'real(8)',OP_READ))


    ! construct flux volumes
    CALL fvol(nshape,nnod,nel,nel2,cut,d_ndx,d_ndy,d_ndux, &
&             d_ndvy,d_rDelV )

    ! update position
    call a_eq_b_host(&
                     & "a_eq_b",s_nodes,  &
                     & op_arg_dat(d_ndx,-1,OP_ID,1,'real(8)',OP_WRITE),  &
                     & op_arg_dat(d_ndux,-1,OP_ID,1,'real(8)',OP_READ))

    call a_eq_b_host(&
                     & "a_eq_b",s_nodes,  &
                     & op_arg_dat(d_ndy,-1,OP_ID,1,'real(8)',OP_WRITE),  &
                     & op_arg_dat(d_ndvy,-1,OP_ID,1,'real(8)',OP_READ))

    ! Timing data
    t1=get_time()
    t1=t1-t0
    bookleaf_times%time_in_alegetfvol=bookleaf_times%time_in_alegetfvol+&
&                                     t1

  END SUBROUTINE alegetfvol

  SUBROUTINE fvol(nshape,nnod,nel,nel2,cut,d_ndx0,d_ndy0,d_ndx1,d_ndy1,d_rdelv)

    USE kinds_mod,ONLY: ink,rlk
    USE op2_bookleaf, ONLY: s_elements,m_el2node
        use OP2_Fortran_RT_Support
    ! USE common_kernels
    ! USE USE ale_getfvol_kernels

    ! Argument list
    INTEGER(KIND=ink),                       INTENT(IN) :: nshape,nnod, &
&                                                          nel,nel2
    REAL(KIND=rlk),                          INTENT(IN) :: cut
    type(op_dat) :: d_ndx0,d_ndy0,d_ndx1,d_ndy1,d_rdelv

    ! Local
    INTEGER(KIND=ink) :: iel,ii,jj,jp,n1,n2
    REAL(KIND=rlk)    :: x1,x2,x3,x4,y1,y2,y3,y4,a1,a3,b1,b3

    ! initialise
    call set_zero4_host(&
                     & "set_zero4",s_elements,  &
                     & op_arg_dat(d_rdelv,-1,OP_ID,4,'real(8)',OP_WRITE))


    ! construct volumes
    call ale_getfvol_vol_host(&
                     & "ale_getfvol_vol",s_elements,  &
                     & op_arg_dat(d_ndx0,1,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndx0,2,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndx0,3,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndx0,4,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndy0,1,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndy0,2,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndy0,3,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndy0,4,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndx1,1,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndx1,2,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndx1,3,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndx1,4,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndy1,1,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndy1,2,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndy1,3,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_ndy1,4,m_el2node,1,'real(8)',OP_READ),  &
                     & op_arg_dat(d_rdelv,-1,OP_ID,4,'real(8)',OP_WRITE),  &
                     & op_arg_gbl(cut,1,'real(8)',OP_READ))


    END SUBROUTINE fvol

END MODULE ale_getfvol_mod
