!
! auto-generated by op2.py
!

MODULE ALE_ADVECTORS_TOTFLUX_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! ale_advectors_totfluxvariable declarations

INTEGER(kind=4) :: opDat2_stride_OP2CONSTANT
!$acc declare create(opDat2_stride_OP2CONSTANT)
INTEGER(kind=4) :: direct_stride_OP2CONSTANT
!$acc declare create(direct_stride_OP2CONSTANT)

#define OP2_SOA(var,dim,stride) var((dim-1)*stride+1)

CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_advectors_totflux
SUBROUTINE ale_advectors_totflux_gpu(rFlux,rTotFlux1,rTotFlux2,rTotFlux3,rTotFlux4)
!$acc routine seq
    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: rFlux
    REAL(KIND=rlk), INTENT(INOUT) :: rTotFlux1,rTotFlux2,rTotFlux3,rTotFlux4

    rTotFlux1 = rTotFlux1 + rFlux(1)
    rTotFlux2 = rTotFlux2 + rFlux(2)
    rTotFlux3 = rTotFlux3 + rFlux(3)
    rTotFlux4 = rTotFlux4 + rFlux(4)

  END SUBROUTINE ale_advectors_totflux_gpu


SUBROUTINE op_wrap_ale_advectors_totflux( &
& opDat2Local, &
& opDat1Local, &
& opDat2Map, &
& opDat2MapDim, &
& col_reord, set_size, &
& bottom,top)
implicit none
real(8) opDat2Local(1,*)
real(8) opDat1Local(*)
INTEGER(kind=4) opDat2Map(*)
INTEGER(kind=4) opDat2MapDim
INTEGER(kind=4) col_reord(*)
INTEGER(kind=4) set_size

INTEGER(kind=4) bottom,top,i1,i2
INTEGER(kind=4) map2idx, map3idx, map4idx, map5idx


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat2Local) &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat2Map) &
!$acc& deviceptr(col_reord) private(i1) &
!$acc& private(map2idx) &
!$acc& private(map3idx) &
!$acc& private(map4idx) &
!$acc& private(map5idx) 
DO i2 = bottom, top-1, 1
  i1 = col_reord(i2+1)
  map2idx = opDat2Map(1 + i1 + set_size * 0)+1
  map3idx = opDat2Map(1 + i1 + set_size * 1)+1
  map4idx = opDat2Map(1 + i1 + set_size * 2)+1
  map5idx = opDat2Map(1 + i1 + set_size * 3)+1
! kernel call
  CALL ale_advectors_totflux_gpu( &
  & opDat1Local(i1+1), &
  & opDat2Local(1,map2idx), &
  & opDat2Local(1,map3idx), &
  & opDat2Local(1,map4idx), &
  & opDat2Local(1,map5idx) &
  & )
END DO

END SUBROUTINE
SUBROUTINE ale_advectors_totflux_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5

type ( op_arg ) , DIMENSION(5) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat2Map
INTEGER(kind=4) :: opDat2MapDim
real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: exec_size
LOGICAL :: firstTime_ale_advectors_totflux = .TRUE.
type ( c_ptr )  :: planRet_ale_advectors_totflux
type ( op_plan ) , POINTER :: actualPlan_ale_advectors_totflux
INTEGER(kind=4), POINTER, DIMENSION(:) :: col_reord_ale_advectors_totflux
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_ale_advectors_totflux
INTEGER(kind=4), DIMENSION(1:5) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 5

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5

returnSetKernelTiming = setKernelTime(13 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
IF ((calledTimes.EQ.0).OR.(opDat2_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg2))) THEN
  opDat2_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg2)
  !$acc update device(opDat2_stride_OP2CONSTANT)
END IF
IF ((calledTimes.EQ.0).OR.(direct_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg1))) THEN
  direct_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg1)
  !$acc update device(direct_stride_OP2CONSTANT)
END IF
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

indirectionDescriptorArray(1) = -1
indirectionDescriptorArray(2) = 0
indirectionDescriptorArray(3) = 0
indirectionDescriptorArray(4) = 0
indirectionDescriptorArray(5) = 0

exec_size = opSetCore%size + opSetCore%exec_size
numberOfIndirectOpDats = 1

planRet_ale_advectors_totflux = FortranPlanCaller( &
& userSubroutine//C_NULL_CHAR, &
& set%setCPtr, &
& partitionSize, &
& numberOfOpDats, &
& opArgArray, &
& numberOfIndirectOpDats, &
& indirectionDescriptorArray,4)

CALL c_f_pointer(planRet_ale_advectors_totflux,actualPlan_ale_advectors_totflux)
CALL c_f_pointer(actualPlan_ale_advectors_totflux%col_reord,col_reord_ale_advectors_totflux,(/exec_size/))
CALL c_f_pointer(actualPlan_ale_advectors_totflux%color2_offsets,offset_ale_advectors_totflux,(/actualPlan_ale_advectors_totflux%ncolors+1/))
opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
opDat2MapDim = getMapDimFromOpArg(opArg2)
opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
CALL c_f_pointer(opArg2%data_d,opDat2Local,(/opDat2Cardinality/))
CALL c_f_pointer(opArg2%map_data_d,opDat2Map,(/exec_size*opDat2MapDim/))
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))



DO i1 = 0, actualPlan_ale_advectors_totflux%ncolors-1, 1
  IF (i1 .EQ. 1) THEN
    CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
  END IF

  offset_b = offset_ale_advectors_totflux(i1 + 1)
  nelem = offset_ale_advectors_totflux(i1 + 1 + 1)
  CALL op_wrap_ale_advectors_totflux( &
  & opDat2Local, &
  & opDat1Local, &
  & opDat2Map, &
  & opDat2MapDim, &
  & col_reord_ale_advectors_totflux, exec_size, offset_b, nelem )
END DO
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

returnSetKernelTiming = setKernelTime(13 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, actualPlan_ale_advectors_totflux%transfer,actualPlan_ale_advectors_totflux%transfer2, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE