!
! auto-generated by op2.py
!

MODULE ALE_ADVECT_VOLMASS_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_advect_volmass
SUBROUTINE ale_advect_volmass(delv,delv1,delv2,delv3, delv4, &
&       delm,delm1,delm2,delm3,delm4,dndv,dndm,flux,ielsd,ielel,iel,i1)
    USE kinds_mod,ONLY: rlk, ink
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: delv,delv1,delv2,delv3, delv4, &
&       delm,delm1,delm2,delm3,delm4
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(INOUT) :: flux
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(OUT) :: dndv,dndm
    INTEGER(KIND=ink), DIMENSION(N_SHAPE), INTENT(IN) :: ielel,ielsd
    INTEGER(KIND=ink), INTENT(IN) :: iel
    INTEGER(KIND=ink) :: i1

    INTEGER(KIND=ink) :: i2,ie1,ie2,is1,is2
    REAL(KIND=rlk)  :: w1,w2,w3,w4

    i2 = i1+2_ink

    ie1=ielel(i1)
    ie2=ielel(i2)
    is1=ielsd(i1)
    is2=ielsd(i2)
    IF (i1.EQ.1) THEN !i1 may only be 1 or 2, so that i2<=4
      w1=delv1(is1)
      w2=delv3(is2)
      w3=delm1(is1)
      w4=delm3(is2)
    ELSEIF (i1.EQ.2) THEN
      w1=delv2(is1)
      w2=delv4(is2)
      w3=delm2(is1)
      w4=delm4(is2)
    ENDIF

    IF (ie1.EQ.iel) THEN !i.e. boundary
      w1=0.0_rlk
      w3=0.0_rlk
    ENDIF
    IF (ie2.EQ.iel) THEN !i.e. boundary
      w2=0.0_rlk
      w4=0.0_rlk
    ENDIF
    w1=w1-delv(i1)
    w2=w2-delv(i2)
    w1=0.25_rlk*(w1-w2)
    dndv(i1)=w1
    dndv(i2)=w1
    w1=w3-delm(i1)
    w2=w4-delm(i2)
    w3=0.25_rlk*(w1-w2)
    dndm(i1)=w3
    dndm(i2)=w3
    w3=0.25_rlk*(w1+w2)
    flux(1)=flux(1)+w3
    flux(2)=flux(2)+w3
    flux(3)=flux(3)+w3
    flux(4)=flux(4)+w3
  END SUBROUTINE ale_advect_volmass


SUBROUTINE op_wrap_ale_advect_volmass( &
& opDat2Local, &
& opDat7Local, &
& opDat1Local, &
& opDat6Local, &
& opDat11Local, &
& opDat12Local, &
& opDat13Local, &
& opDat14Local, &
& opDat15Local, &
& opDat16Local, &
& opDat17Local, &
& opDat2Map, &
& opDat2MapDim, &
& bottom,top)
real(8) opDat2Local(4,*)
real(8) opDat7Local(4,*)
real(8) opDat1Local(4,*)
real(8) opDat6Local(4,*)
real(8) opDat11Local(4,*)
real(8) opDat12Local(4,*)
real(8) opDat13Local(4,*)
integer(4) opDat14Local(4,*)
integer(4) opDat15Local(4,*)
integer(4) opDat16Local(1,*)
integer(4) opDat17Local(1)
INTEGER(kind=4) opDat2Map(*)
INTEGER(kind=4) opDat2MapDim
INTEGER(kind=4) bottom,top,i1
INTEGER(kind=4) map2idx, map3idx, map4idx, map5idx

DO i1 = bottom, top-1, 1
  map2idx = opDat2Map(1 + i1 * opDat2MapDim + 0)+1
  map3idx = opDat2Map(1 + i1 * opDat2MapDim + 1)+1
  map4idx = opDat2Map(1 + i1 * opDat2MapDim + 2)+1
  map5idx = opDat2Map(1 + i1 * opDat2MapDim + 3)+1
! kernel call
CALL ale_advect_volmass( &
  & opDat1Local(1,i1+1), &
  & opDat2Local(1,map2idx), &
  & opDat2Local(1,map3idx), &
  & opDat2Local(1,map4idx), &
  & opDat2Local(1,map5idx), &
  & opDat6Local(1,i1+1), &
  & opDat7Local(1,map2idx), &
  & opDat7Local(1,map3idx), &
  & opDat7Local(1,map4idx), &
  & opDat7Local(1,map5idx), &
  & opDat11Local(1,i1+1), &
  & opDat12Local(1,i1+1), &
  & opDat13Local(1,i1+1), &
  & opDat14Local(1,i1+1), &
  & opDat15Local(1,i1+1), &
  & opDat16Local(1,i1+1), &
  & opDat17Local(1) &
  & )
END DO
END SUBROUTINE
SUBROUTINE ale_advect_volmass_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7, &
& opArg8, &
& opArg9, &
& opArg10, &
& opArg11, &
& opArg12, &
& opArg13, &
& opArg14, &
& opArg15, &
& opArg16, &
& opArg17 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7
type ( op_arg ) , INTENT(IN) :: opArg8
type ( op_arg ) , INTENT(IN) :: opArg9
type ( op_arg ) , INTENT(IN) :: opArg10
type ( op_arg ) , INTENT(IN) :: opArg11
type ( op_arg ) , INTENT(IN) :: opArg12
type ( op_arg ) , INTENT(IN) :: opArg13
type ( op_arg ) , INTENT(IN) :: opArg14
type ( op_arg ) , INTENT(IN) :: opArg15
type ( op_arg ) , INTENT(IN) :: opArg16
type ( op_arg ) , INTENT(IN) :: opArg17

type ( op_arg ) , DIMENSION(17) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat2Map
INTEGER(kind=4) :: opDat2MapDim
real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat7Map
INTEGER(kind=4) :: opDat7MapDim
real(8), POINTER, DIMENSION(:) :: opDat7Local
INTEGER(kind=4) :: opDat7Cardinality

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat6Local
INTEGER(kind=4) :: opDat6Cardinality

real(8), POINTER, DIMENSION(:) :: opDat11Local
INTEGER(kind=4) :: opDat11Cardinality

real(8), POINTER, DIMENSION(:) :: opDat12Local
INTEGER(kind=4) :: opDat12Cardinality

real(8), POINTER, DIMENSION(:) :: opDat13Local
INTEGER(kind=4) :: opDat13Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat14Local
INTEGER(kind=4) :: opDat14Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat15Local
INTEGER(kind=4) :: opDat15Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat16Local
INTEGER(kind=4) :: opDat16Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat17Local
INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
LOGICAL :: firstTime_ale_advect_volmass = .TRUE.
type ( c_ptr )  :: planRet_ale_advect_volmass
type ( op_plan ) , POINTER :: actualPlan_ale_advect_volmass
INTEGER(kind=4), POINTER, DIMENSION(:) :: ncolblk_ale_advect_volmass
INTEGER(kind=4), POINTER, DIMENSION(:) :: blkmap_ale_advect_volmass
INTEGER(kind=4), POINTER, DIMENSION(:) :: nelems_ale_advect_volmass
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_ale_advect_volmass
INTEGER(kind=4), DIMENSION(1:17) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: blockOffset
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 17

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7
opArgArray(8) = opArg8
opArgArray(9) = opArg9
opArgArray(10) = opArg10
opArgArray(11) = opArg11
opArgArray(12) = opArg12
opArgArray(13) = opArg13
opArgArray(14) = opArg14
opArgArray(15) = opArg15
opArgArray(16) = opArg16
opArgArray(17) = opArg17

returnSetKernelTiming = setKernelTime(4 , userSubroutine//C_NULL_CHAR, &
& 0.0_8, 0.00000_4,0.00000_4, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  partitionSize = 0

  numberOfThreads = omp_get_max_threads()
  indirectionDescriptorArray(1) = -1
  indirectionDescriptorArray(2) = 0
  indirectionDescriptorArray(3) = 0
  indirectionDescriptorArray(4) = 0
  indirectionDescriptorArray(5) = 0
  indirectionDescriptorArray(6) = -1
  indirectionDescriptorArray(7) = 1
  indirectionDescriptorArray(8) = 1
  indirectionDescriptorArray(9) = 1
  indirectionDescriptorArray(10) = 1
  indirectionDescriptorArray(11) = -1
  indirectionDescriptorArray(12) = -1
  indirectionDescriptorArray(13) = -1
  indirectionDescriptorArray(14) = -1
  indirectionDescriptorArray(15) = -1
  indirectionDescriptorArray(16) = -1
  indirectionDescriptorArray(17) = -1

  numberOfIndirectOpDats = 2

  planRet_ale_advect_volmass = FortranPlanCaller( &
  & userSubroutine//C_NULL_CHAR, &
  & set%setCPtr, &
  & partitionSize, &
  & numberOfOpDats, &
  & opArgArray, &
  & numberOfIndirectOpDats, &
  & indirectionDescriptorArray,2)

  CALL c_f_pointer(planRet_ale_advect_volmass,actualPlan_ale_advect_volmass)
  CALL c_f_pointer(actualPlan_ale_advect_volmass%ncolblk, &
&    ncolblk_ale_advect_volmass,(/actualPlan_ale_advect_volmass%ncolors_core/))
  CALL c_f_pointer(actualPlan_ale_advect_volmass%blkmap, &
&    blkmap_ale_advect_volmass,(/actualPlan_ale_advect_volmass%nblocks/))
  CALL c_f_pointer(actualPlan_ale_advect_volmass%offset,&
&    offset_ale_advect_volmass,(/actualPlan_ale_advect_volmass%nblocks/))
  CALL c_f_pointer(actualPlan_ale_advect_volmass%nelems,&
&    nelems_ale_advect_volmass,(/actualPlan_ale_advect_volmass%nblocks/))

  opSetCore => set%setPtr

  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat2MapDim = getMapDimFromOpArg(opArg2)
  opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
  opDat7MapDim = getMapDimFromOpArg(opArg7)
  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
  opDat11Cardinality = opArg11%dim * getSetSizeFromOpArg(opArg11)
  opDat12Cardinality = opArg12%dim * getSetSizeFromOpArg(opArg12)
  opDat13Cardinality = opArg13%dim * getSetSizeFromOpArg(opArg13)
  opDat14Cardinality = opArg14%dim * getSetSizeFromOpArg(opArg14)
  opDat15Cardinality = opArg15%dim * getSetSizeFromOpArg(opArg15)
  opDat16Cardinality = opArg16%dim * getSetSizeFromOpArg(opArg16)
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg2%map_data,opDat2Map,(/opSetCore%size*opDat2MapDim/))
  CALL c_f_pointer(opArg7%data,opDat7Local,(/opDat7Cardinality/))
  CALL c_f_pointer(opArg7%map_data,opDat7Map,(/opSetCore%size*opDat7MapDim/))
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg6%data,opDat6Local,(/opDat6Cardinality/))
  CALL c_f_pointer(opArg11%data,opDat11Local,(/opDat11Cardinality/))
  CALL c_f_pointer(opArg12%data,opDat12Local,(/opDat12Cardinality/))
  CALL c_f_pointer(opArg13%data,opDat13Local,(/opDat13Cardinality/))
  CALL c_f_pointer(opArg14%data,opDat14Local,(/opDat14Cardinality/))
  CALL c_f_pointer(opArg15%data,opDat15Local,(/opDat15Cardinality/))
  CALL c_f_pointer(opArg16%data,opDat16Local,(/opDat16Cardinality/))
  CALL c_f_pointer(opArg17%data,opDat17Local, (/opArg17%dim/))


  blockOffset = 0

  DO i1 = 0, actualPlan_ale_advect_volmass%ncolors-1, 1
    IF (i1 .EQ. actualPlan_ale_advect_volmass%ncolors_core) THEN
      CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
    END IF

    nblocks = ncolblk_ale_advect_volmass(i1 + 1)
    !$OMP PARALLEL DO private (threadID, blockID, nelem, offset_b)
    DO i2 = 0, nblocks-1, 1
      threadID = omp_get_thread_num()
      blockID = blkmap_ale_advect_volmass(i2+blockOffset+1)
      nelem = nelems_ale_advect_volmass(blockID+1)
      offset_b = offset_ale_advect_volmass(blockID+1)
      CALL op_wrap_ale_advect_volmass( &
      & opDat2Local, &
      & opDat7Local, &
      & opDat1Local, &
      & opDat6Local, &
      & opDat11Local, &
      & opDat12Local, &
      & opDat13Local, &
      & opDat14Local, &
      & opDat15Local, &
      & opDat16Local, &
      & opDat17Local, &
      & opDat2Map, &
      & opDat2MapDim, &
      & offset_b, offset_b+nelem)
    END DO
    !$OMP END PARALLEL DO
    blockOffset = blockOffset + nblocks
  END DO
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(4 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, actualPlan_ale_advect_volmass%transfer,actualPlan_ale_advect_volmass%transfer2, 1)
END SUBROUTINE
END MODULE