!
! auto-generated by op2.py
!

MODULE ALE_ADVECTORS_FLUX_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: ale_advectors_flux
SUBROUTINE ale_advectors_flux(rCorner,rCorner1,rCorner2,rCorner3,rCorner4, &
&   rVar,rVar1,rVar2,rVar3,rVar4,rDel,rFlux,ielsd,i1)
    USE kinds_mod,ONLY: rlk, ink
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: rCorner,rCorner1,rCorner2,rCorner3,rCorner4,rDel
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(OUT) :: rFlux
    REAL(KIND=rlk), INTENT(IN) :: rVar,rVar1,rVar2,rVar3,rVar4
    INTEGER(KIND=ink), DIMENSION(N_SHAPE), INTENT(IN) :: ielsd
    INTEGER(KIND=ink) :: i1

    INTEGER(KIND=ink) :: i2,j1,j2
    REAL(KIND=rlk) :: r1,r2,r3,r4,w1,w2,w3,w4,w5,w6,w7,w8,rV,rGrad

    i2 = i1+2_ink


!    iE2=iElEl(i2)
    j2=iElSd(i2)
    j1=MOD(i2,N_SHAPE)+1_ink
    r3=rCorner(i2)+rCorner(j1)
    j1=MOD(j2,N_SHAPE)+1_ink
    IF (i2.EQ.3) THEN
      w5=r3+rCorner3(j2)+rCorner3(j1)
    ELSEIF (i2.EQ.4) THEN
      w5=r3+rCorner4(j2)+rCorner4(j1)
    ENDIF
!    iE1=iElEl(i1)
    j2=iElSd(i1)
    j1=i1+1_ink
    r4=rCorner(i1)+rCorner(j1)
    j1=MOD(j2,N_SHAPE)+1_ink
    IF (i1.EQ.1) THEN
      w6=r4+rCorner1(j2)+rCorner1(j1)
    ELSEIF (i1.EQ.2) THEN
      w6=r4+rCorner2(j2)+rCorner2(j1)
    ENDIF
    rV=rVar
    r1=rDel(i1)
    r2=rDel(i2)
    IF (i2.EQ.3) THEN
      w1=rV-rVar3
    ELSEIF (i2.EQ.4) THEN
      w1=rV-rVar4
    ENDIF
    IF (i1.EQ.1) THEN
      w2=rVar1-rV
    ELSEIF (i1.EQ.2) THEN
      w2=rVar2-rV
    ENDIF
    w3=ABS(w1)
    w4=ABS(w2)
    w7=SIGN(1.0_rlk,w2)
    w8=(w4*w6*w6+w3*w5*w5)/(w5*w6*(w5+w6))
    rGrad=w7*MIN(ABS(w8),w3/w5,w4/w6)
    IF (w1*w2.LE.0.0_rlk) rGrad=0.0_rlk
    r1=r1*(rV+rGrad*(r3-0.5_rlk*r1))
    r2=r2*(rV-rGrad*(r4-0.5_rlk*r2))
    rFlux(i1)=r1
    rFlux(i2)=r2

  END SUBROUTINE ale_advectors_flux


SUBROUTINE op_wrap_ale_advectors_flux( &
  & opDat2Local, &
  & opDat7Local, &
  & opDat1Local, &
  & opDat6Local, &
  & opDat11Local, &
  & opDat12Local, &
  & opDat13Local, &
  & opDat14Local, &
  & opDat2Map, &
  & opDat2MapDim, &
  & bottom,top)
  implicit none
  real(8) opDat2Local(4,*)
  real(8) opDat7Local(1,*)
  real(8) opDat1Local(4,*)
  real(8) opDat6Local(1,*)
  real(8) opDat11Local(4,*)
  real(8) opDat12Local(4,*)
  integer(4) opDat13Local(4,*)
  integer(4) opDat14Local(1)
  INTEGER(kind=4) opDat2Map(*)
  INTEGER(kind=4) opDat2MapDim
  INTEGER(kind=4) bottom,top,i1
  INTEGER(kind=4) map2idx, map3idx, map4idx, map5idx

  DO i1 = bottom, top-1, 1
    map2idx = opDat2Map(1 + i1 * opDat2MapDim + 0)+1
    map3idx = opDat2Map(1 + i1 * opDat2MapDim + 1)+1
    map4idx = opDat2Map(1 + i1 * opDat2MapDim + 2)+1
    map5idx = opDat2Map(1 + i1 * opDat2MapDim + 3)+1
! kernel call
  CALL ale_advectors_flux( &
    & opDat1Local(1,i1+1), &
    & opDat2Local(1,map2idx), &
    & opDat2Local(1,map3idx), &
    & opDat2Local(1,map4idx), &
    & opDat2Local(1,map5idx), &
    & opDat6Local(1,i1+1), &
    & opDat7Local(1,map2idx), &
    & opDat7Local(1,map3idx), &
    & opDat7Local(1,map4idx), &
    & opDat7Local(1,map5idx), &
    & opDat11Local(1,i1+1), &
    & opDat12Local(1,i1+1), &
    & opDat13Local(1,i1+1), &
    & opDat14Local(1) &
    & )
  END DO
END SUBROUTINE
SUBROUTINE ale_advectors_flux_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6, &
  & opArg7, &
  & opArg8, &
  & opArg9, &
  & opArg10, &
  & opArg11, &
  & opArg12, &
  & opArg13, &
  & opArg14 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4
  type ( op_arg ) , INTENT(IN) :: opArg5
  type ( op_arg ) , INTENT(IN) :: opArg6
  type ( op_arg ) , INTENT(IN) :: opArg7
  type ( op_arg ) , INTENT(IN) :: opArg8
  type ( op_arg ) , INTENT(IN) :: opArg9
  type ( op_arg ) , INTENT(IN) :: opArg10
  type ( op_arg ) , INTENT(IN) :: opArg11
  type ( op_arg ) , INTENT(IN) :: opArg12
  type ( op_arg ) , INTENT(IN) :: opArg13
  type ( op_arg ) , INTENT(IN) :: opArg14

  type ( op_arg ) , DIMENSION(14) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
  REAL(kind=8) :: startTime
  REAL(kind=8) :: endTime
  INTEGER(kind=4) :: returnSetKernelTiming
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat2Map
  INTEGER(kind=4) :: opDat2MapDim
  real(8), POINTER, DIMENSION(:) :: opDat2Local
  INTEGER(kind=4) :: opDat2Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat7Map
  INTEGER(kind=4) :: opDat7MapDim
  real(8), POINTER, DIMENSION(:) :: opDat7Local
  INTEGER(kind=4) :: opDat7Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat6Local
  INTEGER(kind=4) :: opDat6Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat11Local
  INTEGER(kind=4) :: opDat11Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat12Local
  INTEGER(kind=4) :: opDat12Cardinality

  integer(4), POINTER, DIMENSION(:) :: opDat13Local
  INTEGER(kind=4) :: opDat13Cardinality

  integer(4), POINTER, DIMENSION(:) :: opDat14Local

  INTEGER(kind=4) :: i1
  REAL(kind=4) :: dataTransfer

  numberOfOpDats = 14

  opArgArray(1) = opArg1
  opArgArray(2) = opArg2
  opArgArray(3) = opArg3
  opArgArray(4) = opArg4
  opArgArray(5) = opArg5
  opArgArray(6) = opArg6
  opArgArray(7) = opArg7
  opArgArray(8) = opArg8
  opArgArray(9) = opArg9
  opArgArray(10) = opArg10
  opArgArray(11) = opArg11
  opArgArray(12) = opArg12
  opArgArray(13) = opArg13
  opArgArray(14) = opArg14

  returnSetKernelTiming = setKernelTime(10 , userSubroutine//C_NULL_CHAR, &
  & 0.d0, 0.00000_4,0.00000_4, 0)
  call op_timers_core(startTime)

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  opSetCore => set%setPtr

  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat2MapDim = getMapDimFromOpArg(opArg2)
  opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
  opDat7MapDim = getMapDimFromOpArg(opArg7)
  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
  opDat11Cardinality = opArg11%dim * getSetSizeFromOpArg(opArg11)
  opDat12Cardinality = opArg12%dim * getSetSizeFromOpArg(opArg12)
  opDat13Cardinality = opArg13%dim * getSetSizeFromOpArg(opArg13)
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg2%map_data,opDat2Map,(/opSetCore%size*opDat2MapDim/))
  CALL c_f_pointer(opArg7%data,opDat7Local,(/opDat7Cardinality/))
  CALL c_f_pointer(opArg7%map_data,opDat7Map,(/opSetCore%size*opDat7MapDim/))
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg6%data,opDat6Local,(/opDat6Cardinality/))
  CALL c_f_pointer(opArg11%data,opDat11Local,(/opDat11Cardinality/))
  CALL c_f_pointer(opArg12%data,opDat12Local,(/opDat12Cardinality/))
  CALL c_f_pointer(opArg13%data,opDat13Local,(/opDat13Cardinality/))
  CALL c_f_pointer(opArg14%data,opDat14Local, (/opArg14%dim/))


  CALL op_wrap_ale_advectors_flux( &
  & opDat2Local, &
  & opDat7Local, &
  & opDat1Local, &
  & opDat6Local, &
  & opDat11Local, &
  & opDat12Local, &
  & opDat13Local, &
  & opDat14Local, &
  & opDat2Map, &
  & opDat2MapDim, &
  & 0, opSetCore%core_size)
  CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  CALL op_wrap_ale_advectors_flux( &
  & opDat2Local, &
  & opDat7Local, &
  & opDat1Local, &
  & opDat6Local, &
  & opDat11Local, &
  & opDat12Local, &
  & opDat13Local, &
  & opDat14Local, &
  & opDat2Map, &
  & opDat2MapDim, &
  & opSetCore%core_size, n_upper)
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF


  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  dataTransfer = 0.0
  dataTransfer = dataTransfer + opArg2%size * MIN(n_upper,getSetSizeFromOpArg(opArg2))
  dataTransfer = dataTransfer + opArg7%size * MIN(n_upper,getSetSizeFromOpArg(opArg7))
  dataTransfer = dataTransfer + opArg11%size * MIN(n_upper,getSetSizeFromOpArg(opArg11))
  dataTransfer = dataTransfer + opArg12%size * MIN(n_upper,getSetSizeFromOpArg(opArg12))
  dataTransfer = dataTransfer + opArg13%size * MIN(n_upper,getSetSizeFromOpArg(opArg13))
  dataTransfer = dataTransfer + opArg14%size
  dataTransfer = dataTransfer + n_upper * opDat2MapDim * 4.d0
  returnSetKernelTiming = setKernelTime(10 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, dataTransfer, 0.00000_4, 1)
END SUBROUTINE
END MODULE