#
#!Crown Copyright 2014 AWE.
#!
#! This file is part of Bookleaf.
#!
#! Bookleaf is free software: you can redistribute it and/or modify it under
#! the terms of the GNU General Public License as published by the
#! Free Software Foundation, either version 3 of the License, or (at your option)
#! any later version.
#!
#! Bookleaf is distributed in the hope that it will be useful, but
#! WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#! FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#! details.
#!
#! You should have received a copy of the GNU General Public License along with
#! Bookleaf. If not, see http://www.gnu.org/licenses/.

ifeq ($(OPTARGET),meshgen)
else
ifndef OPTARGET
OBJ+= ale_advect.o       \
	ale_advect_kernels.o \
      ale_advectors.o    \
      ale_advectors_kernels.o    \
      ale_getfvol_kernels.o      \
      ale_getfvol.o      \
      ale_getmesh_kernels.o      \
      ale_getmesh.o      \
      ale_update_kernels.o       \
      ale_update.o       \
      alestep.o
else
OBJ+= ale_advect_op.o       \
      ale_advectors_op.o    \
      ale_getfvol_op.o      \
      ale_getmesh_op.o      \
      ale_update_op.o       \
      alestep.o
ifeq ($(OPTARGET),genseq)
OBJ += $(shell cd ale; find . -maxdepth 1 -name "*_seqkernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
ifeq ($(OPTARGET),openmp)
OBJ += $(shell cd ale; find . -maxdepth 1 -name "*_kernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
ifeq ($(OPTARGET),cuda)
OBJ += $(shell cd ale; find . -maxdepth 1 -name "*_gpukernel.CUF" | sed s/\\.CUF/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
ifeq ($(OPTARGET),mpi)
OBJ += $(shell cd ale; find . -maxdepth 1 -name "*_seqkernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
ifeq ($(OPTARGET),mpi_openmp)
OBJ += $(shell cd ale; find . -maxdepth 1 -name "*_kernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
ifeq ($(OPTARGET),mpi_cuda)
OBJ += $(shell cd ale; find . -maxdepth 1 -name "*_gpukernel.CUF" | sed s/\\.CUF/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
endif
endif
