!
! auto-generated by op2.py
!

MODULE GETPC_MERGE_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! getpc_mergevariable declarations



CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getpc_merge
SUBROUTINE getpc_merge_gpu(csqrd)
!$acc routine seq

    USE kinds_mod,ONLY: rlk
    USE integers_mod,ONLY: nshape

    implicit none

    REAL(KIND=rlk), INTENT(INOUT) :: csqrd

    IF (csqrd.LT.0.0_rlk) THEN
      csqrd = 0.0_rlk
    ENDIF

  END SUBROUTINE getpc_merge_gpu


SUBROUTINE op_wrap_getpc_merge( &
& opDat1Local, &
& bottom,top)
implicit none
real(8) opDat1Local(1,*)

INTEGER(kind=4) bottom,top,i1,i2


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat1Local) 
DO i1 = bottom, top-1, 1
! kernel call
  CALL getpc_merge_gpu( &
  & opDat1Local(1,i1+1) &
  & )
END DO

END SUBROUTINE
SUBROUTINE getpc_merge_host( userSubroutine, set, &
& opArg1 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1

type ( op_arg ) , DIMENSION(1) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: sliceStart
INTEGER(kind=4) :: sliceEnd
REAL(kind=4) :: dataTransfer


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 1

opArgArray(1) = opArg1

returnSetKernelTiming = setKernelTime(22 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))


sliceStart = 0
sliceEnd = opSetCore%size
CALL op_wrap_getpc_merge( &
& opDat1Local, &
& sliceStart, sliceEnd)
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

dataTransfer = 0.0
dataTransfer = dataTransfer + opArg1%size * getSetSizeFromOpArg(opArg1) * 2.d0
returnSetKernelTiming = setKernelTime(22 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, dataTransfer, 0.00000_4, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE