#
# !Crown Copyright 2014 AWE.
# !
# ! This file is part of Bookleaf.
# !
# ! Bookleaf is free software: you can redistribute it and/or modify it under
# ! the terms of the GNU General Public License as published by the
# ! Free Software Foundation, either version 3 of the License, or (at your option)
# ! any later version.
# !
# ! Bookleaf is distributed in the hope that it will be useful, but
# ! WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# ! FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# ! details.
# !
# ! You should have received a copy of the GNU General Public License along with
# ! Bookleaf. If not, see http://www.gnu.org/licenses/.
#
#
# Object list
ifeq ($(OPTARGET),meshgen)
OBJ += data_gen.o        \
       common_kernels.o       \
       error.o       \
       geometry.o    \
       geometry_kernels.o    \
       halt.o        \
       init_gen.o        \
       init_kernels.o        \
       mesh.o        \
       timers.o      \
       utilities.o
else
ifndef OPTARGET
OBJ += data.o        \
       common_kernels.o       \
       error.o       \
       geometry.o    \
       geometry_kernels.o    \
       halt.o        \
       init.o        \
       init_kernels.o        \
       mesh.o        \
       timers.o      \
       utilities.o
else
OBJ += error.o       \
       geometry_op.o    \
       halt.o        \
       init_op.o        \
       mesh.o        \
       timers.o      \
       utilities_op.o
ifeq ($(OPTARGET),genseq)
OBJ += data.o
OBJ += $(shell cd utils; find . -maxdepth 1 -name "*_seqkernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
ifeq ($(OPTARGET),openmp)
OBJ += data.o
OBJ += $(shell cd utils; find . -maxdepth 1 -name "*_kernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
ifeq ($(OPTARGET),cuda)
OBJ += $(shell cd utils; find . -maxdepth 1 -name "*_gpukernel.CUF" | sed s/\\.CUF/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
ifeq ($(OPTARGET),mpi)
OBJ += $(shell cd utils; find . -maxdepth 1 -name "*_seqkernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
OBJ += data.o
endif
ifeq ($(OPTARGET),mpi_openmp)
OBJ += data.o
OBJ += $(shell cd utils; find . -maxdepth 1 -name "*_kernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
ifeq ($(OPTARGET),mpi_cuda)
OBJ += $(shell cd utils; find . -maxdepth 1 -name "*_gpukernel.CUF" | sed s/\\.CUF/\\.o/g | sed s/\\.\\///g | tr "\n" ' '; cd ..)
endif
endif
endif
