!
! auto-generated by op2.py
!

MODULE SOD_RESET_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! sod_resetvariable declarations

INTEGER(kind=4) :: opDat1_stride_OP2CONSTANT
!$acc declare create(opDat1_stride_OP2CONSTANT)
INTEGER(kind=4) :: direct_stride_OP2CONSTANT
!$acc declare create(direct_stride_OP2CONSTANT)

#define OP2_SOA(var,dim,stride) var((dim-1)*stride+1)

CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: sod_reset
SUBROUTINE sod_reset_gpu(ndx1,ndx2,ndx3,ndx4,xmid,ielmat,rho, &
&                      pre,ein,elmass,cnmass,eos_param,elvol,cnwt)
!$acc routine seq

    USE kinds_mod,ONLY: rlk,ink
    USE parameters_mod,ONLY: LI, N_SHAPE

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: ndx1,ndx2,ndx3,ndx4,elvol
    REAL(KIND=rlk), INTENT(INOUT) :: xmid
    REAL(KIND=rlk), INTENT(OUT) :: rho,pre,ein,elmass
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(OUT) :: cnmass
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: cnwt
    REAL(KIND=rlk), DIMENSION(6,LI), INTENT(IN) :: eos_param
    INTEGER(KIND=ink), INTENT(OUT) :: ielmat


    IF ((0.25_rlk*(ndx1+ndx2+ndx3+ndx4)).LT.xmid) THEN
      ielmat=1_ink
      rho=1.0_rlk
      pre=1.0_rlk
    ELSE
      ielmat=2_ink
      rho=0.125_rlk
      pre=0.1_rlk
    ENDIF
    ein=pre/(rho*(eos_param(1,ielmat)-1.0_rlk))
    elmass=rho*elvol
    OP2_SOA(cnmass,1, direct_stride_OP2CONSTANT)=rho*OP2_SOA(cnwt,1, direct_stride_OP2CONSTANT)
    OP2_SOA(cnmass,2, direct_stride_OP2CONSTANT)=rho*OP2_SOA(cnwt,2, direct_stride_OP2CONSTANT)
    OP2_SOA(cnmass,3, direct_stride_OP2CONSTANT)=rho*OP2_SOA(cnwt,3, direct_stride_OP2CONSTANT)
    OP2_SOA(cnmass,4, direct_stride_OP2CONSTANT)=rho*OP2_SOA(cnwt,4, direct_stride_OP2CONSTANT)

  END SUBROUTINE sod_reset_gpu


SUBROUTINE op_wrap_sod_reset( &
& opDat1Local, &
& opDat5Local, &
& opDat6Local, &
& opDat7Local, &
& opDat8Local, &
& opDat9Local, &
& opDat10Local, &
& opDat11Local, &
& opDat12Dim, &
& opDat12Local, &
& opDat13Local, &
& opDat14Local, &
& opDat1Map, &
& opDat1MapDim, &
& col_reord, set_size, &
& bottom,top)
implicit none
real(8) opDat1Local(1,*)
real(8) opDat5Local(1)
integer(4) opDat6Local(1,*)
real(8) opDat7Local(1,*)
real(8) opDat8Local(1,*)
real(8) opDat9Local(1,*)
real(8) opDat10Local(1,*)
real(8) opDat11Local(*)
INTEGER(kind=4) opDat12Dim
real(8) opDat12Local(opDat12Dim)
real(8) opDat13Local(1,*)
real(8) opDat14Local(*)
INTEGER(kind=4) opDat1Map(*)
INTEGER(kind=4) opDat1MapDim
INTEGER(kind=4) col_reord(*)
INTEGER(kind=4) set_size

INTEGER(kind=4) bottom,top,i1,i2
INTEGER(kind=4) map1idx, map2idx, map3idx, map4idx


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat6Local) &
!$acc& deviceptr(opDat7Local) &
!$acc& deviceptr(opDat8Local) &
!$acc& deviceptr(opDat9Local) &
!$acc& deviceptr(opDat10Local) &
!$acc& deviceptr(opDat11Local) &
!$acc& deviceptr(opDat13Local) &
!$acc& deviceptr(opDat14Local) &
!$acc& deviceptr(opDat1Map) &
!$acc& deviceptr(col_reord) private(i1) &
!$acc& private(map1idx) &
!$acc& private(map2idx) &
!$acc& private(map3idx) &
!$acc& private(map4idx) 
DO i2 = bottom, top-1, 1
  i1 = col_reord(i2+1)
  map1idx = opDat1Map(1 + i1 + set_size * 0)+1
  map2idx = opDat1Map(1 + i1 + set_size * 1)+1
  map3idx = opDat1Map(1 + i1 + set_size * 2)+1
  map4idx = opDat1Map(1 + i1 + set_size * 3)+1
! kernel call
  CALL sod_reset_gpu( &
  & opDat1Local(1,map1idx), &
  & opDat1Local(1,map2idx), &
  & opDat1Local(1,map3idx), &
  & opDat1Local(1,map4idx), &
  & opDat5Local(1), &
  & opDat6Local(1,i1+1), &
  & opDat7Local(1,i1+1), &
  & opDat8Local(1,i1+1), &
  & opDat9Local(1,i1+1), &
  & opDat10Local(1,i1+1), &
  & opDat11Local(i1+1), &
  & opDat12Local(1), &
  & opDat13Local(1,i1+1), &
  & opDat14Local(i1+1) &
  & )
END DO

END SUBROUTINE
SUBROUTINE sod_reset_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7, &
& opArg8, &
& opArg9, &
& opArg10, &
& opArg11, &
& opArg12, &
& opArg13, &
& opArg14 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7
type ( op_arg ) , INTENT(IN) :: opArg8
type ( op_arg ) , INTENT(IN) :: opArg9
type ( op_arg ) , INTENT(IN) :: opArg10
type ( op_arg ) , INTENT(IN) :: opArg11
type ( op_arg ) , INTENT(IN) :: opArg12
type ( op_arg ) , INTENT(IN) :: opArg13
type ( op_arg ) , INTENT(IN) :: opArg14

type ( op_arg ) , DIMENSION(14) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat1Map
INTEGER(kind=4) :: opDat1MapDim
real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat5Local
integer(4), POINTER, DIMENSION(:) :: opDat6Local
INTEGER(kind=4) :: opDat6Cardinality

real(8), POINTER, DIMENSION(:) :: opDat7Local
INTEGER(kind=4) :: opDat7Cardinality

real(8), POINTER, DIMENSION(:) :: opDat8Local
INTEGER(kind=4) :: opDat8Cardinality

real(8), POINTER, DIMENSION(:) :: opDat9Local
INTEGER(kind=4) :: opDat9Cardinality

real(8), POINTER, DIMENSION(:) :: opDat10Local
INTEGER(kind=4) :: opDat10Cardinality

real(8), POINTER, DIMENSION(:) :: opDat11Local
INTEGER(kind=4) :: opDat11Cardinality

real(8), POINTER, DIMENSION(:) :: opDat12Local
real(8), POINTER, DIMENSION(:) :: opDat13Local
INTEGER(kind=4) :: opDat13Cardinality

real(8), POINTER, DIMENSION(:) :: opDat14Local
INTEGER(kind=4) :: opDat14Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: exec_size
LOGICAL :: firstTime_sod_reset = .TRUE.
type ( c_ptr )  :: planRet_sod_reset
type ( op_plan ) , POINTER :: actualPlan_sod_reset
INTEGER(kind=4), POINTER, DIMENSION(:) :: col_reord_sod_reset
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_sod_reset
INTEGER(kind=4), DIMENSION(1:14) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 14

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7
opArgArray(8) = opArg8
opArgArray(9) = opArg9
opArgArray(10) = opArg10
opArgArray(11) = opArg11
opArgArray(12) = opArg12
opArgArray(13) = opArg13
opArgArray(14) = opArg14

returnSetKernelTiming = setKernelTime(29 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
IF ((calledTimes.EQ.0).OR.(opDat1_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg1))) THEN
  opDat1_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg1)
  !$acc update device(opDat1_stride_OP2CONSTANT)
END IF
IF ((calledTimes.EQ.0).OR.(direct_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg11))) THEN
  direct_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg11)
  !$acc update device(direct_stride_OP2CONSTANT)
END IF
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

indirectionDescriptorArray(1) = 0
indirectionDescriptorArray(2) = 0
indirectionDescriptorArray(3) = 0
indirectionDescriptorArray(4) = 0
indirectionDescriptorArray(5) = -1
indirectionDescriptorArray(6) = -1
indirectionDescriptorArray(7) = -1
indirectionDescriptorArray(8) = -1
indirectionDescriptorArray(9) = -1
indirectionDescriptorArray(10) = -1
indirectionDescriptorArray(11) = -1
indirectionDescriptorArray(12) = -1
indirectionDescriptorArray(13) = -1
indirectionDescriptorArray(14) = -1

exec_size = opSetCore%size + opSetCore%exec_size
numberOfIndirectOpDats = 1
partitionSize = 0

planRet_sod_reset = FortranPlanCaller( &
& userSubroutine//C_NULL_CHAR, &
& set%setCPtr, &
& partitionSize, &
& numberOfOpDats, &
& opArgArray, &
& numberOfIndirectOpDats, &
& indirectionDescriptorArray,4)

CALL c_f_pointer(planRet_sod_reset,actualPlan_sod_reset)
CALL c_f_pointer(actualPlan_sod_reset%col_reord,col_reord_sod_reset,(/exec_size/))
CALL c_f_pointer(actualPlan_sod_reset%color2_offsets,offset_sod_reset,(/actualPlan_sod_reset%ncolors+1/))
opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
opDat1MapDim = getMapDimFromOpArg(opArg1)
opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
opDat8Cardinality = opArg8%dim * getSetSizeFromOpArg(opArg8)
opDat9Cardinality = opArg9%dim * getSetSizeFromOpArg(opArg9)
opDat10Cardinality = opArg10%dim * getSetSizeFromOpArg(opArg10)
opDat11Cardinality = opArg11%dim * getSetSizeFromOpArg(opArg11)
opDat13Cardinality = opArg13%dim * getSetSizeFromOpArg(opArg13)
opDat14Cardinality = opArg14%dim * getSetSizeFromOpArg(opArg14)
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg1%map_data_d,opDat1Map,(/exec_size*opDat1MapDim/))
CALL c_f_pointer(opArg5%data,opDat5Local, (/opArg5%dim/))
CALL c_f_pointer(opArg6%data_d,opDat6Local,(/opDat6Cardinality/))
CALL c_f_pointer(opArg7%data_d,opDat7Local,(/opDat7Cardinality/))
CALL c_f_pointer(opArg8%data_d,opDat8Local,(/opDat8Cardinality/))
CALL c_f_pointer(opArg9%data_d,opDat9Local,(/opDat9Cardinality/))
CALL c_f_pointer(opArg10%data_d,opDat10Local,(/opDat10Cardinality/))
CALL c_f_pointer(opArg11%data_d,opDat11Local,(/opDat11Cardinality/))
CALL c_f_pointer(opArg12%data,opDat12Local, (/opArg12%dim/))
CALL c_f_pointer(opArg13%data_d,opDat13Local,(/opDat13Cardinality/))
CALL c_f_pointer(opArg14%data_d,opDat14Local,(/opDat14Cardinality/))



DO i1 = 0, actualPlan_sod_reset%ncolors-1, 1
  IF (i1 .EQ. 1) THEN
    CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
  END IF

  offset_b = offset_sod_reset(i1 + 1)
  nelem = offset_sod_reset(i1 + 1 + 1)
  CALL op_wrap_sod_reset( &
  & opDat1Local, &
  & opDat5Local(1), &
  & opDat6Local, &
  & opDat7Local, &
  & opDat8Local, &
  & opDat9Local, &
  & opDat10Local, &
  & opDat11Local, &
  & opArg12%dim, &
  & opDat12Local(1), &
  & opDat13Local, &
  & opDat14Local, &
  & opDat1Map, &
  & opDat1MapDim, &
  & col_reord_sod_reset, exec_size, offset_b, nelem )
END DO
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

returnSetKernelTiming = setKernelTime(29 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, actualPlan_sod_reset%transfer,actualPlan_sod_reset%transfer2, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE