!
! auto-generated by op2.py
!

MODULE GATHER_FUN_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! gather_funvariable declarations

INTEGER(kind=4) :: opDat1_stride_OP2CONSTANT
!$acc declare create(opDat1_stride_OP2CONSTANT)
INTEGER(kind=4) :: direct_stride_OP2CONSTANT
!$acc declare create(direct_stride_OP2CONSTANT)

#define OP2_SOA(var,dim,stride) var((dim-1)*stride+1)


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: gather_fun
SUBROUTINE gather_fun_gpu(a1,a2,a3,a4,b)
!$acc routine seq

    USE kinds_mod,ONLY: rlk

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: a1,a2,a3,a4
    REAL(KIND=rlk), DIMENSION(4), INTENT(OUT) :: b

    b(1) = a1
    b(2) = a2
    b(3) = a3
    b(4) = a4

  END SUBROUTINE gather_fun_gpu


SUBROUTINE op_wrap_gather_fun( &
& opDat1Local, &
& opDat5Local, &
& opDat1Map, &
& opDat1MapDim, &
& col_reord, set_size, &
& bottom,top)
implicit none
real(8) opDat1Local(1,*)
real(8) opDat5Local(*)
INTEGER(kind=4) opDat1Map(*)
INTEGER(kind=4) opDat1MapDim
INTEGER(kind=4) col_reord(*)
INTEGER(kind=4) set_size

INTEGER(kind=4) bottom,top,i1,i2
INTEGER(kind=4) map1idx, map2idx, map3idx, map4idx


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat5Local) &
!$acc& deviceptr(opDat1Map) &
!$acc& deviceptr(col_reord) private(i1) &
!$acc& private(map1idx) &
!$acc& private(map2idx) &
!$acc& private(map3idx) &
!$acc& private(map4idx) 
DO i2 = bottom, top-1, 1
  i1 = col_reord(i2+1)
  map1idx = opDat1Map(1 + i1 + set_size * 0)+1
  map2idx = opDat1Map(1 + i1 + set_size * 1)+1
  map3idx = opDat1Map(1 + i1 + set_size * 2)+1
  map4idx = opDat1Map(1 + i1 + set_size * 3)+1
! kernel call
  CALL gather_fun_gpu( &
  & opDat1Local(1,map1idx), &
  & opDat1Local(1,map2idx), &
  & opDat1Local(1,map3idx), &
  & opDat1Local(1,map4idx), &
  & opDat5Local(i1+1) &
  & )
END DO

END SUBROUTINE
SUBROUTINE gather_fun_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5

type ( op_arg ) , DIMENSION(5) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat1Map
INTEGER(kind=4) :: opDat1MapDim
real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat5Local
INTEGER(kind=4) :: opDat5Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: exec_size
LOGICAL :: firstTime_gather_fun = .TRUE.
type ( c_ptr )  :: planRet_gather_fun
type ( op_plan ) , POINTER :: actualPlan_gather_fun
INTEGER(kind=4), POINTER, DIMENSION(:) :: col_reord_gather_fun
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_gather_fun
INTEGER(kind=4), DIMENSION(1:5) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 5

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5

returnSetKernelTiming = setKernelTime(35 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
IF ((calledTimes.EQ.0).OR.(opDat1_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg1))) THEN
  opDat1_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg1)
  !$acc update device(opDat1_stride_OP2CONSTANT)
END IF
IF ((calledTimes.EQ.0).OR.(direct_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg5))) THEN
  direct_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg5)
  !$acc update device(direct_stride_OP2CONSTANT)
END IF
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

indirectionDescriptorArray(1) = 0
indirectionDescriptorArray(2) = 0
indirectionDescriptorArray(3) = 0
indirectionDescriptorArray(4) = 0
indirectionDescriptorArray(5) = -1

exec_size = opSetCore%size + opSetCore%exec_size
numberOfIndirectOpDats = 1

planRet_gather_fun = FortranPlanCaller( &
& userSubroutine//C_NULL_CHAR, &
& set%setCPtr, &
& partitionSize, &
& numberOfOpDats, &
& opArgArray, &
& numberOfIndirectOpDats, &
& indirectionDescriptorArray,4)

CALL c_f_pointer(planRet_gather_fun,actualPlan_gather_fun)
CALL c_f_pointer(actualPlan_gather_fun%col_reord,col_reord_gather_fun,(/exec_size/))
CALL c_f_pointer(actualPlan_gather_fun%color2_offsets,offset_gather_fun,(/actualPlan_gather_fun%ncolors+1/))
opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
opDat1MapDim = getMapDimFromOpArg(opArg1)
opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg1%map_data_d,opDat1Map,(/exec_size*opDat1MapDim/))
CALL c_f_pointer(opArg5%data_d,opDat5Local,(/opDat5Cardinality/))



DO i1 = 0, actualPlan_gather_fun%ncolors-1, 1
  IF (i1 .EQ. 1) THEN
    CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
  END IF

  offset_b = offset_gather_fun(i1 + 1)
  nelem = offset_gather_fun(i1 + 1 + 1)
  CALL op_wrap_gather_fun( &
  & opDat1Local, &
  & opDat5Local, &
  & opDat1Map, &
  & opDat1MapDim, &
  & col_reord_gather_fun, exec_size, offset_b, nelem )
END DO
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

returnSetKernelTiming = setKernelTime(35 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, actualPlan_gather_fun%transfer,actualPlan_gather_fun%transfer2, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE
