!
! auto-generated by op2.py
!

MODULE GETACC_SCATTER_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! getacc_scattervariable declarations

INTEGER(kind=4) :: opDat6_stride_OP2CONSTANT
!$acc declare create(opDat6_stride_OP2CONSTANT)
INTEGER(kind=4) :: direct_stride_OP2CONSTANT
!$acc declare create(direct_stride_OP2CONSTANT)

#define OP2_SOA(var,dim,stride) var((dim-1)*stride+1)

CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getacc_scatter
SUBROUTINE getacc_scatter_gpu(cnmass,rho,cnwt,cnfx,cnfy, &
&                           ndmass1,ndmass2,ndmass3,ndmass4, &
&                           ndarea1,ndarea2,ndarea3,ndarea4, &
&                           ndub1,ndub2,ndub3,ndub4, &
&                           ndvb1,ndvb2,ndvb3,ndvb4)
!$acc routine seq

    USE kinds_mod,ONLY: ink,rlk
    USE reals_mod,    ONLY: zerocut

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: rho
    REAL(KIND=rlk), INTENT(INOUT) :: ndarea1,ndarea2,ndarea3,ndarea4, &
&                           ndub1,ndub2,ndub3,ndub4, &
&                           ndvb1,ndvb2,ndvb3,ndvb4, &
&                           ndmass1,ndmass2,ndmass3,ndmass4
    REAL(KIND=rlk),DIMENSION(4),INTENT(IN) :: cnmass,cnwt,cnfx,cnfy
    INTEGER(KIND=ink) :: jj,ii

    jj=1_ink
    IF (OP2_SOA(cnmass,jj, direct_stride_OP2CONSTANT).GT.zerocut) THEN
      ndmass1=ndmass1+OP2_SOA(cnmass,jj, direct_stride_OP2CONSTANT)
    ELSE
      ii=jj-1_ink
      IF (ii.EQ.0_ink) ii=4_ink
      IF (OP2_SOA(cnmass,ii, direct_stride_OP2CONSTANT).GT.zerocut) THEN
        ndmass1=ndmass1+OP2_SOA(cnmass,ii, direct_stride_OP2CONSTANT)
      ELSE
        ndmass1=ndmass1+rho*OP2_SOA(cnwt,jj, direct_stride_OP2CONSTANT)
      ENDIF
    ENDIF
    ndarea1=ndarea1+OP2_SOA(cnwt,jj, direct_stride_OP2CONSTANT)
    ndub1=ndub1+OP2_SOA(cnfx,jj, direct_stride_OP2CONSTANT)
    ndvb1=ndvb1+OP2_SOA(cnfy,jj, direct_stride_OP2CONSTANT)

    jj=2_ink
    IF (OP2_SOA(cnmass,jj, direct_stride_OP2CONSTANT).GT.zerocut) THEN
      ndmass2=ndmass2+OP2_SOA(cnmass,jj, direct_stride_OP2CONSTANT)
    ELSE
      ii=jj-1_ink
      IF (ii.EQ.0_ink) ii=4_ink
      IF (OP2_SOA(cnmass,ii, direct_stride_OP2CONSTANT).GT.zerocut) THEN
        ndmass2=ndmass2+OP2_SOA(cnmass,ii, direct_stride_OP2CONSTANT)
      ELSE
        ndmass2=ndmass2+rho*OP2_SOA(cnwt,jj, direct_stride_OP2CONSTANT)
      ENDIF
    ENDIF
    ndarea2=ndarea2+OP2_SOA(cnwt,jj, direct_stride_OP2CONSTANT)
    ndub2=ndub2+OP2_SOA(cnfx,jj, direct_stride_OP2CONSTANT)
    ndvb2=ndvb2+OP2_SOA(cnfy,jj, direct_stride_OP2CONSTANT)

    jj=3_ink
    IF (OP2_SOA(cnmass,jj, direct_stride_OP2CONSTANT).GT.zerocut) THEN
      ndmass3=ndmass3+OP2_SOA(cnmass,jj, direct_stride_OP2CONSTANT)
    ELSE
      ii=jj-1_ink
      IF (ii.EQ.0_ink) ii=4_ink
      IF (OP2_SOA(cnmass,ii, direct_stride_OP2CONSTANT).GT.zerocut) THEN
        ndmass3=ndmass3+OP2_SOA(cnmass,ii, direct_stride_OP2CONSTANT)
      ELSE
        ndmass3=ndmass3+rho*OP2_SOA(cnwt,jj, direct_stride_OP2CONSTANT)
      ENDIF
    ENDIF
    ndarea3=ndarea3+OP2_SOA(cnwt,jj, direct_stride_OP2CONSTANT)
    ndub3=ndub3+OP2_SOA(cnfx,jj, direct_stride_OP2CONSTANT)
    ndvb3=ndvb3+OP2_SOA(cnfy,jj, direct_stride_OP2CONSTANT)

    jj=4_ink
    IF (OP2_SOA(cnmass,jj, direct_stride_OP2CONSTANT).GT.zerocut) THEN
      ndmass4=ndmass4+OP2_SOA(cnmass,jj, direct_stride_OP2CONSTANT)
    ELSE
      ii=jj-1_ink
      IF (ii.EQ.0_ink) ii=4_ink
      IF (OP2_SOA(cnmass,ii, direct_stride_OP2CONSTANT).GT.zerocut) THEN
        ndmass4=ndmass4+OP2_SOA(cnmass,ii, direct_stride_OP2CONSTANT)
      ELSE
        ndmass4=ndmass4+rho*OP2_SOA(cnwt,jj, direct_stride_OP2CONSTANT)
      ENDIF
    ENDIF
    ndarea4=ndarea4+OP2_SOA(cnwt,jj, direct_stride_OP2CONSTANT)
    ndub4=ndub4+OP2_SOA(cnfx,jj, direct_stride_OP2CONSTANT)
    ndvb4=ndvb4+OP2_SOA(cnfy,jj, direct_stride_OP2CONSTANT)

  END SUBROUTINE getacc_scatter_gpu


SUBROUTINE op_wrap_getacc_scatter( &
& opDat6Local, &
& opDat10Local, &
& opDat14Local, &
& opDat18Local, &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat4Local, &
& opDat5Local, &
& opDat6Map, &
& opDat6MapDim, &
& col_reord, set_size, &
& bottom,top)
implicit none
real(8) opDat6Local(1,*)
real(8) opDat10Local(1,*)
real(8) opDat14Local(1,*)
real(8) opDat18Local(1,*)
real(8) opDat1Local(*)
real(8) opDat2Local(1,*)
real(8) opDat3Local(*)
real(8) opDat4Local(*)
real(8) opDat5Local(*)
INTEGER(kind=4) opDat6Map(*)
INTEGER(kind=4) opDat6MapDim
INTEGER(kind=4) col_reord(*)
INTEGER(kind=4) set_size

INTEGER(kind=4) bottom,top,i1,i2
INTEGER(kind=4) map6idx, map7idx, map8idx, map9idx


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat6Local) &
!$acc& deviceptr(opDat10Local) &
!$acc& deviceptr(opDat14Local) &
!$acc& deviceptr(opDat18Local) &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat2Local) &
!$acc& deviceptr(opDat3Local) &
!$acc& deviceptr(opDat4Local) &
!$acc& deviceptr(opDat5Local) &
!$acc& deviceptr(opDat6Map) &
!$acc& deviceptr(col_reord) private(i1) &
!$acc& private(map6idx) &
!$acc& private(map7idx) &
!$acc& private(map8idx) &
!$acc& private(map9idx) 
DO i2 = bottom, top-1, 1
  i1 = col_reord(i2+1)
  map6idx = opDat6Map(1 + i1 + set_size * 0)+1
  map7idx = opDat6Map(1 + i1 + set_size * 1)+1
  map8idx = opDat6Map(1 + i1 + set_size * 2)+1
  map9idx = opDat6Map(1 + i1 + set_size * 3)+1
! kernel call
  CALL getacc_scatter_gpu( &
  & opDat1Local(i1+1), &
  & opDat2Local(1,i1+1), &
  & opDat3Local(i1+1), &
  & opDat4Local(i1+1), &
  & opDat5Local(i1+1), &
  & opDat6Local(1,map6idx), &
  & opDat6Local(1,map7idx), &
  & opDat6Local(1,map8idx), &
  & opDat6Local(1,map9idx), &
  & opDat10Local(1,map6idx), &
  & opDat10Local(1,map7idx), &
  & opDat10Local(1,map8idx), &
  & opDat10Local(1,map9idx), &
  & opDat14Local(1,map6idx), &
  & opDat14Local(1,map7idx), &
  & opDat14Local(1,map8idx), &
  & opDat14Local(1,map9idx), &
  & opDat18Local(1,map6idx), &
  & opDat18Local(1,map7idx), &
  & opDat18Local(1,map8idx), &
  & opDat18Local(1,map9idx) &
  & )
END DO

END SUBROUTINE
SUBROUTINE getacc_scatter_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7, &
& opArg8, &
& opArg9, &
& opArg10, &
& opArg11, &
& opArg12, &
& opArg13, &
& opArg14, &
& opArg15, &
& opArg16, &
& opArg17, &
& opArg18, &
& opArg19, &
& opArg20, &
& opArg21 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7
type ( op_arg ) , INTENT(IN) :: opArg8
type ( op_arg ) , INTENT(IN) :: opArg9
type ( op_arg ) , INTENT(IN) :: opArg10
type ( op_arg ) , INTENT(IN) :: opArg11
type ( op_arg ) , INTENT(IN) :: opArg12
type ( op_arg ) , INTENT(IN) :: opArg13
type ( op_arg ) , INTENT(IN) :: opArg14
type ( op_arg ) , INTENT(IN) :: opArg15
type ( op_arg ) , INTENT(IN) :: opArg16
type ( op_arg ) , INTENT(IN) :: opArg17
type ( op_arg ) , INTENT(IN) :: opArg18
type ( op_arg ) , INTENT(IN) :: opArg19
type ( op_arg ) , INTENT(IN) :: opArg20
type ( op_arg ) , INTENT(IN) :: opArg21

type ( op_arg ) , DIMENSION(21) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat6Map
INTEGER(kind=4) :: opDat6MapDim
real(8), POINTER, DIMENSION(:) :: opDat6Local
INTEGER(kind=4) :: opDat6Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat10Map
INTEGER(kind=4) :: opDat10MapDim
real(8), POINTER, DIMENSION(:) :: opDat10Local
INTEGER(kind=4) :: opDat10Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat14Map
INTEGER(kind=4) :: opDat14MapDim
real(8), POINTER, DIMENSION(:) :: opDat14Local
INTEGER(kind=4) :: opDat14Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat18Map
INTEGER(kind=4) :: opDat18MapDim
real(8), POINTER, DIMENSION(:) :: opDat18Local
INTEGER(kind=4) :: opDat18Cardinality

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat3Local
INTEGER(kind=4) :: opDat3Cardinality

real(8), POINTER, DIMENSION(:) :: opDat4Local
INTEGER(kind=4) :: opDat4Cardinality

real(8), POINTER, DIMENSION(:) :: opDat5Local
INTEGER(kind=4) :: opDat5Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: exec_size
LOGICAL :: firstTime_getacc_scatter = .TRUE.
type ( c_ptr )  :: planRet_getacc_scatter
type ( op_plan ) , POINTER :: actualPlan_getacc_scatter
INTEGER(kind=4), POINTER, DIMENSION(:) :: col_reord_getacc_scatter
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_getacc_scatter
INTEGER(kind=4), DIMENSION(1:21) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 21

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7
opArgArray(8) = opArg8
opArgArray(9) = opArg9
opArgArray(10) = opArg10
opArgArray(11) = opArg11
opArgArray(12) = opArg12
opArgArray(13) = opArg13
opArgArray(14) = opArg14
opArgArray(15) = opArg15
opArgArray(16) = opArg16
opArgArray(17) = opArg17
opArgArray(18) = opArg18
opArgArray(19) = opArg19
opArgArray(20) = opArg20
opArgArray(21) = opArg21

returnSetKernelTiming = setKernelTime(36 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
IF ((calledTimes.EQ.0).OR.(opDat6_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg6))) THEN
  opDat6_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg6)
  !$acc update device(opDat6_stride_OP2CONSTANT)
END IF
IF ((calledTimes.EQ.0).OR.(direct_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg1))) THEN
  direct_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg1)
  !$acc update device(direct_stride_OP2CONSTANT)
END IF
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

indirectionDescriptorArray(1) = -1
indirectionDescriptorArray(2) = -1
indirectionDescriptorArray(3) = -1
indirectionDescriptorArray(4) = -1
indirectionDescriptorArray(5) = -1
indirectionDescriptorArray(6) = 0
indirectionDescriptorArray(7) = 0
indirectionDescriptorArray(8) = 0
indirectionDescriptorArray(9) = 0
indirectionDescriptorArray(10) = 1
indirectionDescriptorArray(11) = 1
indirectionDescriptorArray(12) = 1
indirectionDescriptorArray(13) = 1
indirectionDescriptorArray(14) = 2
indirectionDescriptorArray(15) = 2
indirectionDescriptorArray(16) = 2
indirectionDescriptorArray(17) = 2
indirectionDescriptorArray(18) = 3
indirectionDescriptorArray(19) = 3
indirectionDescriptorArray(20) = 3
indirectionDescriptorArray(21) = 3

exec_size = opSetCore%size + opSetCore%exec_size
numberOfIndirectOpDats = 4

planRet_getacc_scatter = FortranPlanCaller( &
& userSubroutine//C_NULL_CHAR, &
& set%setCPtr, &
& partitionSize, &
& numberOfOpDats, &
& opArgArray, &
& numberOfIndirectOpDats, &
& indirectionDescriptorArray,4)

CALL c_f_pointer(planRet_getacc_scatter,actualPlan_getacc_scatter)
CALL c_f_pointer(actualPlan_getacc_scatter%col_reord,col_reord_getacc_scatter,(/exec_size/))
CALL c_f_pointer(actualPlan_getacc_scatter%color2_offsets,offset_getacc_scatter,(/actualPlan_getacc_scatter%ncolors+1/))
opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
opDat6MapDim = getMapDimFromOpArg(opArg6)
opDat10Cardinality = opArg10%dim * getSetSizeFromOpArg(opArg10)
opDat10MapDim = getMapDimFromOpArg(opArg10)
opDat14Cardinality = opArg14%dim * getSetSizeFromOpArg(opArg14)
opDat14MapDim = getMapDimFromOpArg(opArg14)
opDat18Cardinality = opArg18%dim * getSetSizeFromOpArg(opArg18)
opDat18MapDim = getMapDimFromOpArg(opArg18)
opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
CALL c_f_pointer(opArg6%data_d,opDat6Local,(/opDat6Cardinality/))
CALL c_f_pointer(opArg6%map_data_d,opDat6Map,(/exec_size*opDat6MapDim/))
CALL c_f_pointer(opArg10%data_d,opDat10Local,(/opDat10Cardinality/))
CALL c_f_pointer(opArg10%map_data_d,opDat10Map,(/exec_size*opDat10MapDim/))
CALL c_f_pointer(opArg14%data_d,opDat14Local,(/opDat14Cardinality/))
CALL c_f_pointer(opArg14%map_data_d,opDat14Map,(/exec_size*opDat14MapDim/))
CALL c_f_pointer(opArg18%data_d,opDat18Local,(/opDat18Cardinality/))
CALL c_f_pointer(opArg18%map_data_d,opDat18Map,(/exec_size*opDat18MapDim/))
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg2%data_d,opDat2Local,(/opDat2Cardinality/))
CALL c_f_pointer(opArg3%data_d,opDat3Local,(/opDat3Cardinality/))
CALL c_f_pointer(opArg4%data_d,opDat4Local,(/opDat4Cardinality/))
CALL c_f_pointer(opArg5%data_d,opDat5Local,(/opDat5Cardinality/))



DO i1 = 0, actualPlan_getacc_scatter%ncolors-1, 1
  IF (i1 .EQ. 1) THEN
    CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
  END IF

  offset_b = offset_getacc_scatter(i1 + 1)
  nelem = offset_getacc_scatter(i1 + 1 + 1)
  CALL op_wrap_getacc_scatter( &
  & opDat6Local, &
  & opDat10Local, &
  & opDat14Local, &
  & opDat18Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat4Local, &
  & opDat5Local, &
  & opDat6Map, &
  & opDat6MapDim, &
  & col_reord_getacc_scatter, exec_size, offset_b, nelem )
END DO
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

returnSetKernelTiming = setKernelTime(36 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, actualPlan_getacc_scatter%transfer,actualPlan_getacc_scatter%transfer2, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE