!
! auto-generated by op2.py
!

MODULE GETDT_MINDT_REG_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getdt_mindt_reg
SUBROUTINE getdt_mindt_reg(elidx,ielreg,idx,reg)
    USE kinds_mod,ONLY: rlk,ink
    implicit none
    INTEGER(KIND=ink), INTENT(IN) :: elidx,ielreg
    INTEGER(KIND=ink) :: idx
    INTEGER(KIND=ink), INTENT(INOUT) :: reg
    IF (idx.EQ.elidx) then
      reg = ielreg+1
    ENDIF
  END SUBROUTINE getdt_mindt_reg


SUBROUTINE op_wrap_getdt_mindt_reg( &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat4Local, &
  & bottom,top)
  integer(4) opDat1Local(1,*)
  integer(4) opDat2Local(1,*)
  integer(4) opDat3Local(1)
  integer(4) opDat4Local(1)
  INTEGER(kind=4) bottom,top,i1

  DO i1 = bottom, top-1, 1
! kernel call
  CALL getdt_mindt_reg( &
    & opDat1Local(1,i1+1), &
    & opDat2Local(1,i1+1), &
    & opDat3Local(1), &
    & opDat4Local(1) &
    & )
  END DO
END SUBROUTINE
SUBROUTINE getdt_mindt_reg_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4

  type ( op_arg ) , DIMENSION(4) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
  REAL(kind=8) :: startTime
  REAL(kind=8) :: endTime
  INTEGER(kind=4) :: returnSetKernelTiming
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  integer(4), POINTER, DIMENSION(:) :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality

  integer(4), POINTER, DIMENSION(:) :: opDat2Local
  INTEGER(kind=4) :: opDat2Cardinality

  integer(4), POINTER, DIMENSION(:) :: opDat3Local
  integer(4), POINTER, DIMENSION(:) :: opDat4Local

  INTEGER(kind=4) :: i1

  numberOfOpDats = 4

  opArgArray(1) = opArg1
  opArgArray(2) = opArg2
  opArgArray(3) = opArg3
  opArgArray(4) = opArg4

  returnSetKernelTiming = setKernelTime(48 , userSubroutine//C_NULL_CHAR, &
  & 0.0_8, 0.00000_4,0.00000_4, 0)
  call op_timers_core(startTime)

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  opSetCore => set%setPtr

  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg3%data,opDat3Local, (/opArg3%dim/))
  CALL c_f_pointer(opArg4%data,opDat4Local, (/opArg4%dim/))


  CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  CALL op_wrap_getdt_mindt_reg( &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat4Local, &
  & 0, n_upper)

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  CALL op_mpi_reduce_int(opArg4,opArg4%data)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(48 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime,0.00000_4,0.00000_4, 1)
END SUBROUTINE
END MODULE