!
! auto-generated by op2.py
!

MODULE GETDT_MINVAL_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! getdt_minvalvariable declarations



CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getdt_minval
SUBROUTINE getdt_minval_gpu(rscratch11,w1)
!$acc routine seq

    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: rscratch11
    REAL(KIND=rlk), INTENT(INOUT) :: w1

    w1 = MIN(w1,rscratch11)

  END SUBROUTINE getdt_minval_gpu


SUBROUTINE op_wrap_getdt_minval( &
& opDat1Local, &
& opDat2Local, &
& bottom,top)
implicit none
real(8) opDat1Local(1,*)
real(8) opDat2Local

INTEGER(kind=4) bottom,top,i1,i2


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat1Local) &
!$acc& reduction(min:opDat2Local) 
DO i1 = bottom, top-1, 1
! kernel call
  CALL getdt_minval_gpu( &
  & opDat1Local(1,i1+1), &
  & opDat2Local &
  & )
END DO

END SUBROUTINE
SUBROUTINE getdt_minval_host( userSubroutine, set, &
& opArg1, &
& opArg2 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2

type ( op_arg ) , DIMENSION(2) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: sliceStart
INTEGER(kind=4) :: sliceEnd
REAL(kind=4) :: dataTransfer

real(8), ALLOCATABLE, DIMENSION(:) :: opDat2LocalReduction

INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 2

opArgArray(1) = opArg1
opArgArray(2) = opArg2

returnSetKernelTiming = setKernelTime(42 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg2%data,opDat2Local, (/opArg2%dim/))
allocate(opDat2LocalReduction(opArg2%dim)) 
opDat2LocalReduction = opDat2Local


sliceStart = 0
sliceEnd = opSetCore%size
CALL op_wrap_getdt_minval( &
& opDat1Local, &
& opDat2LocalReduction(1), &
& sliceStart, sliceEnd)
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF
opDat2Local = opDat2LocalReduction

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

deallocate( opDat2LocalReduction )

CALL op_mpi_reduce_double(opArg2,opArg2%data)

call op_timers_core(endTime)

dataTransfer = 0.0
dataTransfer = dataTransfer + opArg1%size * getSetSizeFromOpArg(opArg1)
dataTransfer = dataTransfer + opArg2%size * 2.d0
returnSetKernelTiming = setKernelTime(42 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, dataTransfer, 0.00000_4, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE