!
! auto-generated by op2.py
!

MODULE GETDT_ALE_ZEUL_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getdt_ale_zeul
SUBROUTINE getdt_ale_zeul(elu,elv,rscratch12,w2_s,w2)

    USE kinds_mod,ONLY: rlk,ink
    USE parameters_mod,ONLY: N_SHAPE
    USE reals_mod,ONLY: zerocut

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: rscratch12
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: elu,elv
    REAL(KIND=rlk), INTENT(INOUT) :: w2,w2_s
!    INTEGER(KIND=ink), INTENT(IN) :: iel
!    INTEGER(KIND=ink), INTENT(INOUT) :: ii

    REAL(KIND=rlk) :: w1

          w1=MAX(elu(1)*elu(1)+elv(1)*elv(1),           &
&                elu(2)*elu(2)+elv(2)*elv(2),           &
&                elu(3)*elu(3)+elv(3)*elv(3),           &
&                elu(4)*elu(4)+elv(4)*elv(4))
    w1=rscratch12/MAX(w1,zerocut)
    w2_s=w1
    IF (w1.LT.w2) THEN
      w2=w1
    ENDIF

  END SUBROUTINE getdt_ale_zeul


SUBROUTINE op_wrap_getdt_ale_zeul( &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat4Local, &
& opDat5Local, &
& bottom,top)
implicit none
real(8) opDat1Local(4,*)
real(8) opDat2Local(4,*)
real(8) opDat3Local(1,*)
real(8) opDat4Local(1,*)
real(8) opDat5Local(1)
INTEGER(kind=4) bottom,top,i1

DO i1 = bottom, top-1, 1
! kernel call
CALL getdt_ale_zeul( &
  & opDat1Local(1,i1+1), &
  & opDat2Local(1,i1+1), &
  & opDat3Local(1,i1+1), &
  & opDat4Local(1,i1+1), &
  & opDat5Local(1) &
  & )
END DO
END SUBROUTINE
SUBROUTINE getdt_ale_zeul_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5

type ( op_arg ) , DIMENSION(5) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat3Local
INTEGER(kind=4) :: opDat3Cardinality

real(8), POINTER, DIMENSION(:) :: opDat4Local
INTEGER(kind=4) :: opDat4Cardinality

real(8), POINTER, DIMENSION(:) :: opDat5Local
INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4) :: sliceStart
INTEGER(kind=4) :: sliceEnd
REAL(kind=4) :: dataTransfer

real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost5

INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 5

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5

returnSetKernelTiming = setKernelTime(46 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)


  numberOfThreads = omp_get_max_threads()

  opSetCore => set%setPtr

  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
  opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg3%data,opDat3Local,(/opDat3Cardinality/))
  CALL c_f_pointer(opArg4%data,opDat4Local,(/opDat4Cardinality/))
  CALL c_f_pointer(opArg5%data,opDat5Local, (/opArg5%dim/))

  allocate( reductionArrayHost5(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost5((i1 - 1) * ((1-1)/64+1)*64 + i2) = opDat5Local(i2)
    END DO
  END DO

  !$OMP PARALLEL DO private (sliceStart,sliceEnd,i1,threadID)
  DO i1 = 0, numberOfThreads-1, 1
    sliceStart = opSetCore%size * i1 / numberOfThreads
    sliceEnd = opSetCore%size * (i1 + 1) / numberOfThreads
    threadID = omp_get_thread_num()
! kernel call
    CALL op_wrap_getdt_ale_zeul( &
    & opDat1Local, &
    & opDat2Local, &
    & opDat3Local, &
    & opDat4Local, &
    & reductionArrayHost5(threadID * ((1-1)/64+1)*64 + 1), &
    & sliceStart, sliceEnd)
  END DO
  !$OMP END PARALLEL DO
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat5Local = MIN(opDat5Local, reductionArrayHost5((i1 - 1) * ((1-1)/64+1)*64 + 1))
  END DO

  deallocate( reductionArrayHost5 )

  CALL op_mpi_reduce_double(opArg5,opArg5%data)

  call op_timers_core(endTime)

  dataTransfer = 0.0
  dataTransfer = dataTransfer + opArg1%size * getSetSizeFromOpArg(opArg1)
  dataTransfer = dataTransfer + opArg2%size * getSetSizeFromOpArg(opArg2)
  dataTransfer = dataTransfer + opArg3%size * getSetSizeFromOpArg(opArg3)
  dataTransfer = dataTransfer + opArg4%size * getSetSizeFromOpArg(opArg4)
  dataTransfer = dataTransfer + opArg5%size * 2.d0
  returnSetKernelTiming = setKernelTime(46 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, dataTransfer, 0.00000_4, 1)
END SUBROUTINE
END MODULE