!
! auto-generated by op2.py
!

MODULE GETDT_DIV_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! getdt_divvariable declarations

INTEGER(kind=4) :: direct_stride_OP2CONSTANT
!$acc declare create(direct_stride_OP2CONSTANT)

#define OP2_SOA(var,dim,stride) var((dim-1)*stride+1)

CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getdt_div
SUBROUTINE getdt_div_gpu(elu,elv,a1,a3,b1,b3,elvol,w2_s,w2)
!$acc routine seq

    USE kinds_mod,ONLY: rlk,ink
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: a1,a3,b1,b3,elvol
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: elu,elv
    REAL(KIND=rlk), INTENT(INOUT) :: w2,w2_s
!    INTEGER(KIND=ink), INTENT(IN) :: iel
!    INTEGER(KIND=ink), INTENT(INOUT) :: ii

    REAL(KIND=rlk) :: w1

    w1=elu(1)*(-b3+b1)+elv(1)*( a3-a1)+   &
&        elu(2)*( b3+b1)+elv(2)*(-a3-a1)+   &
&        elu(3)*( b3-b1)+elv(3)*(-a3+a1)+   &
&        elu(4)*(-b3-b1)+elv(4)*( a3+a1)
    w1=ABS(w1)/elvol
    w2_s=w1
    IF (w1.GT.w2) THEN
      w2=w1
    ENDIF

  END SUBROUTINE getdt_div_gpu


SUBROUTINE op_wrap_getdt_div( &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat4Local, &
& opDat5Local, &
& opDat6Local, &
& opDat7Local, &
& opDat8Local, &
& opDat9Local, &
& bottom,top)
implicit none
real(8) opDat1Local(*)
real(8) opDat2Local(*)
real(8) opDat3Local(1,*)
real(8) opDat4Local(1,*)
real(8) opDat5Local(1,*)
real(8) opDat6Local(1,*)
real(8) opDat7Local(1,*)
real(8) opDat8Local(1,*)
real(8) opDat9Local

INTEGER(kind=4) bottom,top,i1,i2


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat2Local) &
!$acc& deviceptr(opDat3Local) &
!$acc& deviceptr(opDat4Local) &
!$acc& deviceptr(opDat5Local) &
!$acc& deviceptr(opDat6Local) &
!$acc& deviceptr(opDat7Local) &
!$acc& deviceptr(opDat8Local) &
!$acc& reduction(max:opDat9Local) 
DO i1 = bottom, top-1, 1
! kernel call
  CALL getdt_div_gpu( &
  & opDat1Local(i1+1), &
  & opDat2Local(i1+1), &
  & opDat3Local(1,i1+1), &
  & opDat4Local(1,i1+1), &
  & opDat5Local(1,i1+1), &
  & opDat6Local(1,i1+1), &
  & opDat7Local(1,i1+1), &
  & opDat8Local(1,i1+1), &
  & opDat9Local &
  & )
END DO

END SUBROUTINE
SUBROUTINE getdt_div_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7, &
& opArg8, &
& opArg9 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7
type ( op_arg ) , INTENT(IN) :: opArg8
type ( op_arg ) , INTENT(IN) :: opArg9

type ( op_arg ) , DIMENSION(9) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat3Local
INTEGER(kind=4) :: opDat3Cardinality

real(8), POINTER, DIMENSION(:) :: opDat4Local
INTEGER(kind=4) :: opDat4Cardinality

real(8), POINTER, DIMENSION(:) :: opDat5Local
INTEGER(kind=4) :: opDat5Cardinality

real(8), POINTER, DIMENSION(:) :: opDat6Local
INTEGER(kind=4) :: opDat6Cardinality

real(8), POINTER, DIMENSION(:) :: opDat7Local
INTEGER(kind=4) :: opDat7Cardinality

real(8), POINTER, DIMENSION(:) :: opDat8Local
INTEGER(kind=4) :: opDat8Cardinality

real(8), POINTER, DIMENSION(:) :: opDat9Local
INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: sliceStart
INTEGER(kind=4) :: sliceEnd
REAL(kind=4) :: dataTransfer

real(8), ALLOCATABLE, DIMENSION(:) :: opDat9LocalReduction

INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 9

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7
opArgArray(8) = opArg8
opArgArray(9) = opArg9

returnSetKernelTiming = setKernelTime(44 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
IF ((calledTimes.EQ.0).OR.(direct_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg1))) THEN
  direct_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg1)
  !$acc update device(direct_stride_OP2CONSTANT)
END IF
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
opDat8Cardinality = opArg8%dim * getSetSizeFromOpArg(opArg8)
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg2%data_d,opDat2Local,(/opDat2Cardinality/))
CALL c_f_pointer(opArg3%data_d,opDat3Local,(/opDat3Cardinality/))
CALL c_f_pointer(opArg4%data_d,opDat4Local,(/opDat4Cardinality/))
CALL c_f_pointer(opArg5%data_d,opDat5Local,(/opDat5Cardinality/))
CALL c_f_pointer(opArg6%data_d,opDat6Local,(/opDat6Cardinality/))
CALL c_f_pointer(opArg7%data_d,opDat7Local,(/opDat7Cardinality/))
CALL c_f_pointer(opArg8%data_d,opDat8Local,(/opDat8Cardinality/))
CALL c_f_pointer(opArg9%data,opDat9Local, (/opArg9%dim/))
allocate(opDat9LocalReduction(opArg9%dim)) 
opDat9LocalReduction = opDat9Local


sliceStart = 0
sliceEnd = opSetCore%size
CALL op_wrap_getdt_div( &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat4Local, &
& opDat5Local, &
& opDat6Local, &
& opDat7Local, &
& opDat8Local, &
& opDat9LocalReduction(1), &
& sliceStart, sliceEnd)
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF
opDat9Local = opDat9LocalReduction

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

deallocate( opDat9LocalReduction )

CALL op_mpi_reduce_double(opArg9,opArg9%data)

call op_timers_core(endTime)

dataTransfer = 0.0
dataTransfer = dataTransfer + opArg1%size * getSetSizeFromOpArg(opArg1)
dataTransfer = dataTransfer + opArg2%size * getSetSizeFromOpArg(opArg2)
dataTransfer = dataTransfer + opArg3%size * getSetSizeFromOpArg(opArg3)
dataTransfer = dataTransfer + opArg4%size * getSetSizeFromOpArg(opArg4)
dataTransfer = dataTransfer + opArg5%size * getSetSizeFromOpArg(opArg5)
dataTransfer = dataTransfer + opArg6%size * getSetSizeFromOpArg(opArg6)
dataTransfer = dataTransfer + opArg7%size * getSetSizeFromOpArg(opArg7)
dataTransfer = dataTransfer + opArg8%size * getSetSizeFromOpArg(opArg8)
dataTransfer = dataTransfer + opArg9%size * 2.d0
returnSetKernelTiming = setKernelTime(44 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, dataTransfer, 0.00000_4, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE