!
! auto-generated by op2.py
!

MODULE GETFORCE_VISC_MODULE
USE OP2_CONSTANTS
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


! getforce_viscvariable declarations

INTEGER(kind=4) :: direct_stride_OP2CONSTANT
!$acc declare create(direct_stride_OP2CONSTANT)

#define OP2_SOA(var,dim,stride) var((dim-1)*stride+1)

CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getforce_visc
SUBROUTINE getforce_visc_gpu(elfx,elfy,qx,qy)
!$acc routine seq

    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(4), INTENT(INOUT) :: elfx,elfy
    REAL(KIND=rlk), DIMENSION(4), INTENT(IN) :: qx,qy

    INTEGER(KIND=ink) :: jj,jp

    DO jj=1,N_SHAPE
      jp=jj+1_ink
      IF (jp.GT.4_ink) jp=1_ink
      OP2_SOA(elfx,jj, direct_stride_OP2CONSTANT)=OP2_SOA(elfx,jj, direct_stride_OP2CONSTANT)+OP2_SOA(qx,jj, direct_stride_OP2CONSTANT)
      OP2_SOA(elfx,jp, direct_stride_OP2CONSTANT)=OP2_SOA(elfx,jp, direct_stride_OP2CONSTANT)-OP2_SOA(qx,jj, direct_stride_OP2CONSTANT)
      OP2_SOA(elfy,jj, direct_stride_OP2CONSTANT)=OP2_SOA(elfy,jj, direct_stride_OP2CONSTANT)+OP2_SOA(qy,jj, direct_stride_OP2CONSTANT)
      OP2_SOA(elfy,jp, direct_stride_OP2CONSTANT)=OP2_SOA(elfy,jp, direct_stride_OP2CONSTANT)-OP2_SOA(qy,jj, direct_stride_OP2CONSTANT)
    ENDDO

  END SUBROUTINE getforce_visc_gpu


SUBROUTINE op_wrap_getforce_visc( &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat4Local, &
& bottom,top)
implicit none
real(8) opDat1Local(*)
real(8) opDat2Local(*)
real(8) opDat3Local(*)
real(8) opDat4Local(*)

INTEGER(kind=4) bottom,top,i1,i2


!$acc parallel loop independent gang vector &
!$acc& deviceptr(opDat1Local) &
!$acc& deviceptr(opDat2Local) &
!$acc& deviceptr(opDat3Local) &
!$acc& deviceptr(opDat4Local) 
DO i1 = bottom, top-1, 1
! kernel call
  CALL getforce_visc_gpu( &
  & opDat1Local(i1+1), &
  & opDat2Local(i1+1), &
  & opDat3Local(i1+1), &
  & opDat4Local(i1+1) &
  & )
END DO

END SUBROUTINE
SUBROUTINE getforce_visc_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4

type ( op_arg ) , DIMENSION(4) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat3Local
INTEGER(kind=4) :: opDat3Cardinality

real(8), POINTER, DIMENSION(:) :: opDat4Local
INTEGER(kind=4) :: opDat4Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4), SAVE :: calledTimes=0
INTEGER(kind=4) :: sliceStart
INTEGER(kind=4) :: sliceEnd
REAL(kind=4) :: dataTransfer


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 4

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4

returnSetKernelTiming = setKernelTime(51 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000_4,0.00000_4, 0)
IF ((calledTimes.EQ.0).OR.(direct_stride_OP2CONSTANT.NE.getSetSizeFromOpArg(opArg1))) THEN
  direct_stride_OP2CONSTANT = getSetSizeFromOpArg(opArg1)
  !$acc update device(direct_stride_OP2CONSTANT)
END IF
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges_cuda(set%setCPtr,numberOfOpDats,opArgArray)

opSetCore => set%setPtr

opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
CALL c_f_pointer(opArg1%data_d,opDat1Local,(/opDat1Cardinality/))
CALL c_f_pointer(opArg2%data_d,opDat2Local,(/opDat2Cardinality/))
CALL c_f_pointer(opArg3%data_d,opDat3Local,(/opDat3Cardinality/))
CALL c_f_pointer(opArg4%data_d,opDat4Local,(/opDat4Cardinality/))


sliceStart = 0
sliceEnd = opSetCore%size
CALL op_wrap_getforce_visc( &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat4Local, &
& sliceStart, sliceEnd)
IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
  CALL op_mpi_wait_all_cuda(numberOfOpDats,opArgArray)
END IF

CALL op_mpi_set_dirtybit_cuda(numberOfOpDats,opArgArray)

call op_timers_core(endTime)

dataTransfer = 0.0
dataTransfer = dataTransfer + opArg1%size * getSetSizeFromOpArg(opArg1) * 2.d0
dataTransfer = dataTransfer + opArg2%size * getSetSizeFromOpArg(opArg2) * 2.d0
dataTransfer = dataTransfer + opArg3%size * getSetSizeFromOpArg(opArg3)
dataTransfer = dataTransfer + opArg4%size * getSetSizeFromOpArg(opArg4)
returnSetKernelTiming = setKernelTime(51 , userSubroutine//C_NULL_CHAR, &
& endTime-startTime, dataTransfer, 0.00000_4, 1)
calledTimes = calledTimes + 1
END SUBROUTINE
END MODULE