#
# !Crown Copyright 2014 AWE.
# !
# ! This file is part of Bookleaf.
# !
# ! Bookleaf is free software: you can redistribute it and/or modify it under
# ! the terms of the GNU General Public License as published by the
# ! Free Software Foundation, either version 3 of the License, or (at your option)
# ! any later version.
# !
# ! Bookleaf is distributed in the hope that it will be useful, but
# ! WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# ! FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# ! details.
# !
# ! You should have received a copy of the GNU General Public License along with
# ! Bookleaf. If not, see http://www.gnu.org/licenses/.
#
#
# Object list

ifdef PARMETIS_INSTALL_PATH
PARMETIS_LINK = -L$(PARMETIS_INSTALL_PATH)/lib -lparmetis -lmetis
endif
ifdef PTSCOTCH_INSTALL_PATH
PTSCOTCH_LINK = -L$(PTSCOTCH_INSTALL_PATH)/lib/ -lptscotch -lptscotcherr
endif


ifndef OPTARGET
OBJ = getacc.o       \
      getacc_kernels.o       \
      getdt.o        \
      getdt_kernels.o        \
      getein.o       \
      getein_kernels.o       \
      getforce.o     \
      getforce_kernels.o     \
      hydro.o        \
      lagstep.o      \
      lagstep_kernels.o      \
      main.o
OP2_LIB = -lop2_for_seq -lop2_hdf5 -L$(HDF5_INSTALL_PATH)/lib -lhdf5
else
ifeq ($(OPTARGET),meshgen)
OBJ = main_gen.o
OP2_LIB = -lop2_for_seq -lop2_hdf5 -L$(HDF5_INSTALL_PATH)/lib -lhdf5
else
OBJ = getacc_op.o       \
      getdt_op.o        \
      getein_op.o       \
      getforce_op.o     \
      hydro.o        \
      lagstep_op.o      \
      main.o
ifeq ($(OPTARGET),genseq)
OBJ += $(shell find . -maxdepth 1 -name "*_seqkernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
OP2_LIB = -lop2_for_seq -lop2_hdf5 -L$(HDF5_INSTALL_PATH)/lib -lhdf5
endif
ifeq ($(OPTARGET),openmp)
OBJ += $(shell find . -maxdepth 1 -name "*_kernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
OP2_LIB = -lop2_for_openmp -lop2_hdf5 -L$(HDF5_INSTALL_PATH)/lib -lhdf5
endif
ifeq ($(OPTARGET),cuda)
OBJ += cudaConfigurationParams.o data.o
OBJ += $(shell find . -maxdepth 1 -name "*_gpukernel.CUF" | sed s/\\.CUF/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
OP2_LIB = -lop2_for_cuda -Mcuda=cuda6.0,cc35 -lcuda -lop2_hdf5 -L$(HDF5_INSTALL_PATH)/lib -lhdf5
endif
ifeq ($(OPTARGET),mpi)
OBJ += $(shell find . -maxdepth 1 -name "*_seqkernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
OP2_LIB = -lop2_for_mpi -L$(HDF5_INSTALL_PATH)/lib -lhdf5 -lz -pgcpplibs -lstdc++  $(PARMETIS_LINK) $(PTSCOTCH_LINK)
endif
ifeq ($(OPTARGET),mpi_openmp)
OBJ += $(shell find . -maxdepth 1 -name "*_kernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
OP2_LIB = -lop2_for_mpi -L$(HDF5_INSTALL_PATH)/lib -lhdf5 -lz -pgcpplibs -lstdc++ $(PARMETIS_LINK) $(PTSCOTCH_LINK)
endif
ifeq ($(OPTARGET),mpi_cuda)
OBJ += cudaConfigurationParams.o data.o
OBJ += $(shell find . -maxdepth 1 -name "*_gpukernel.CUF" | sed s/\\.CUF/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
OP2_LIB = -lop2_for_mpi_cuda -Mcuda=cuda6.0,cc35 -lcuda -L$(HDF5_INSTALL_PATH)/lib -lhdf5 -lz -pgcpplibs -lstdc++ $(PARMETIS_LINK) $(PTSCOTCH_LINK)
endif
endif
endif
