getpc_kernels.o: data.o 
getq_kernels.o: data.o 
sod.o: data.o sod_kernels.o 
getforce_kernels.o: data.o 
getsp.o: t3_util.o data.o 
getdt.o: t3_util.o utilities.o data.o geometry.o t3_collect.o error.o \
	getdt_kernels.o 
t3_schedule.o: t3_util.o t3_register.o t3_types.o t3_decomposition.o \
	t3_keys.o 
getforce.o: getforce_kernels.o getsp.o gethg.o t3_util.o data.o 
gethg.o: t3_util.o data.o 
getacc_kernels.o: data.o 
geometry_kernels.o: data.o 
lagstep_kernels.o: data.o 
getein.o: t3_util.o getein_kernels.o data.o 
banner.o: 
write_kernels.o: data.o 
write.o: write_kernels.o t3_util.o mesh.o data.o t3_collect.o 
t3_util.o: t3_types.o data.o 
init.o: t3_util.o init_kernels.o common_kernels.o utilities.o getpc.o \
	data.o geometry.o error.o 
t3_register.o: t3_util.o t3_types.o 
getacc.o: getacc_kernels.o t3_util.o common_kernels.o utilities.o \
	comm.o data.o 
getq.o: getq_kernels.o t3_util.o common_kernels.o comm.o data.o 
main.o: write.o t3_util.o mesh.o comm.o data.o timers.o error.o 
t3_types.o: 
hydro.o: getdt.o t3_util.o lagstep.o data.o 
init_kernels.o: data.o 
halt.o: write.o t3_util.o data.o timers.o typhon.o 
common_kernels.o: data.o 
t3_decomposition.o: t3_util.o t3_types.o 
read.o: utilities.o data.o error.o 
utilities.o: common_kernels.o data.o 
getpc.o: getpc_kernels.o t3_util.o data.o eos.o 
mesh.o: utilities.o data.o error.o 
comm.o: t3_util.o data.o error.o typhon.o 
getein_kernels.o: data.o 
t3_exchange.o: t3_schedule.o t3_util.o t3_register.o t3_types.o t3_decomposition.o \
	t3_keys.o 
t3_keys.o: t3_util.o t3_register.o t3_types.o t3_decomposition.o t3_collect.o 
lagstep.o: getforce.o lagstep_kernels.o getein.o t3_util.o getacc.o \
	getq.o common_kernels.o utilities.o getpc.o data.o geometry.o 
data.o: 
t3_quantity.o: t3_util.o t3_register.o t3_types.o 
geometry.o: geometry_kernels.o t3_util.o utilities.o data.o error.o 
eos.o: data.o 
t3_collect.o: t3_types.o 
timers.o: t3_util.o data.o 
sod_kernels.o: data.o 
error.o: data.o 
typhon.o: t3_util.o t3_register.o t3_types.o t3_decomposition.o t3_exchange.o \
	t3_keys.o t3_quantity.o 
getdt_kernels.o: data.o 
