getpc_kernels.o: data.o 
getq_kernels.o: data.o 
ale_advectors.o: ale_advectors_kernels.o data.o common_kernels.o 
sod.o: sod_kernels.o data.o 
getforce_kernels.o: data.o 
getsp.o: data.o 
getacc.o: getacc_kernels.o data.o common_kernels.o utilities.o 
getforce.o: getforce_kernels.o getsp.o gethg.o data.o 
gethg.o: data.o 
sod_kernels.o: data.o 
getacc_kernels.o: data.o 
geometry_kernels.o: data.o 
ale_getfvol.o: data.o common_kernels.o ale_getfvol_kernels.o timers.o 
alestep.o: ale_getfvol.o ale_getmesh.o data.o ale_advect.o error.o \
	ale_update.o 
lagstep_kernels.o: data.o 
ale_advectors_kernels.o: data.o 
getein.o: data.o getein_kernels.o 
ale_getmesh.o: data.o ale_getmesh_kernels.o 
ale_update_kernels.o: data.o 
data.o: 
write_kernels.o: data.o 
gethg_kernels.o: data.o 
write.o: data.o write_kernels.o mesh.o 
init.o: data.o init_kernels.o common_kernels.o utilities.o getpc.o \
	geometry.o error.o 
getsp_kernels.o: data.o 
getdt.o: data.o utilities.o geometry.o error.o getdt_kernels.o 
getq.o: getq_kernels.o data.o common_kernels.o 
main.o: data.o write.o mesh.o timers.o error.o 
hydro.o: alestep.o data.o getdt.o lagstep.o 
init_kernels.o: data.o 
halt.o: data.o write.o timers.o 
common_kernels.o: data.o 
read.o: data.o utilities.o error.o 
utilities.o: data.o common_kernels.o 
getpc.o: getpc_kernels.o data.o eos.o 
mesh.o: data.o utilities.o error.o 
getein_kernels.o: data.o 
ale_advect_kernels.o: data.o 
lagstep.o: getacc.o getforce.o lagstep_kernels.o getein.o data.o getq.o \
	common_kernels.o utilities.o getpc.o geometry.o 
banner.o: 
ale_getfvol_kernels.o: data.o 
ale_advect.o: ale_advectors.o data.o common_kernels.o utilities.o \
	ale_advect_kernels.o 
geometry.o: geometry_kernels.o data.o utilities.o error.o 
eos.o: data.o 
timers.o: data.o 
ale_getmesh_kernels.o: data.o 
error.o: data.o 
getdt_kernels.o: data.o 
ale_update.o: ale_update_kernels.o data.o getpc.o geometry.o 
