!
! auto-generated by op2.py
!

MODULE WRITE_REGVALUES_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: write_regvalues
SUBROUTINE write_regvalues(elvol,elmass,ein,pre, &
&               rho,cnmass,cnwt,ndu1,ndu2,ndu3,ndu4,ndv1, &
&               ndv2,ndv3,ndv4,reg_vol,reg_ie, reg_pre, &
&       reg_pmx,reg_pmn,reg_mass,reg_ke, reg_dmx,reg_dmn, &
&       tot_mom_u,tot_mom_v,ireg,myreg)

    USE kinds_mod,ONLY: rlk,ink
    USE parameters_mod,ONLY: N_SHAPE
    USE reals_mod,    ONLY: dencut

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: elvol,elmass,ein,pre, &
&               rho,ndu1,ndu2,ndu3,ndu4,ndv1,ndv2,ndv3,ndv4
    REAL(KIND=rlk), INTENT(INOUT) :: reg_vol,reg_ie, reg_pre, &
&       reg_pmx,reg_pmn,reg_mass,reg_ke, reg_dmx,reg_dmn, &
&       tot_mom_u, tot_mom_v
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: cnwt,cnmass
    INTEGER(KIND=ink), INTENT(IN) :: ireg,myreg
    REAL(KIND=rlk) :: c1,w2,w3,w4
    REAL(KIND=rlk), DIMENSION(N_SHAPE) :: ndua, ndva
    INTEGER(KIND=ink) :: ii

    IF (ireg.EQ.(myreg+1)) THEN
      ndua(1) = ndu1
      ndua(2) = ndu2
      ndua(3) = ndu3
      ndua(4) = ndu4
      ndva(1) = ndv1
      ndva(2) = ndv2
      ndva(3) = ndv3
      ndva(4) = ndv4


      ! Condition
      c1=dencut*elvol
      ! Scatter element contributions to region
      reg_vol=reg_vol+elvol
      IF (elmass.GT.c1) THEN
        w2=elmass
        reg_mass=reg_mass+w2
        w3=ein
        w3=w3*w2
        reg_ie=reg_ie+w3
        w4=pre
        w3=w2*w4
        reg_pre=reg_pre+w3
        IF (w4.GT.reg_pmx) reg_pmx=w4
        IF (w4.LT.reg_pmn) reg_pmn=w4
        w4=rho
        IF (w4.GT.reg_dmx) reg_dmx=w4
        IF (w4.LT.reg_dmn) reg_dmn=w4
      ENDIF
      DO ii=1,N_SHAPE
        w2=ndua(ii)
        w3=ndva(ii)
        IF (elmass.GT.c1) THEN
          reg_ke=0.5_rlk*cnmass(ii)*(w2*w2+w3*w3)+reg_ke
        ENDIF
        w4=rho*cnwt(ii)
        tot_mom_u=tot_mom_u+w2*w4
        tot_mom_v=tot_mom_v+w3*w4
      ENDDO
    ENDIF

  END SUBROUTINE write_regvalues


SUBROUTINE op_wrap_write_regvalues( &
& opDat8Local, &
& opDat12Local, &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat4Local, &
& opDat5Local, &
& opDat6Local, &
& opDat7Local, &
& opDat16Local, &
& opDat17Local, &
& opDat18Local, &
& opDat19Local, &
& opDat20Local, &
& opDat21Local, &
& opDat22Local, &
& opDat23Local, &
& opDat24Local, &
& opDat25Local, &
& opDat26Local, &
& opDat27Local, &
& opDat28Local, &
& opDat8Map, &
& opDat8MapDim, &
& bottom,top)
real(8) opDat8Local(1,*)
real(8) opDat12Local(1,*)
real(8) opDat1Local(1,*)
real(8) opDat2Local(1,*)
real(8) opDat3Local(1,*)
real(8) opDat4Local(1,*)
real(8) opDat5Local(1,*)
real(8) opDat6Local(4,*)
real(8) opDat7Local(4,*)
real(8) opDat16Local(1)
real(8) opDat17Local(1)
real(8) opDat18Local(1)
real(8) opDat19Local(1)
real(8) opDat20Local(1)
real(8) opDat21Local(1)
real(8) opDat22Local(1)
real(8) opDat23Local(1)
real(8) opDat24Local(1)
real(8) opDat25Local(1)
real(8) opDat26Local(1)
integer(4) opDat27Local(1)
integer(4) opDat28Local(1,*)
INTEGER(kind=4) opDat8Map(*)
INTEGER(kind=4) opDat8MapDim
INTEGER(kind=4) bottom,top,i1
INTEGER(kind=4) map8idx, map9idx, map10idx, map11idx

DO i1 = bottom, top-1, 1
  map8idx = opDat8Map(1 + i1 * opDat8MapDim + 0)+1
  map9idx = opDat8Map(1 + i1 * opDat8MapDim + 1)+1
  map10idx = opDat8Map(1 + i1 * opDat8MapDim + 2)+1
  map11idx = opDat8Map(1 + i1 * opDat8MapDim + 3)+1
! kernel call
CALL write_regvalues( &
  & opDat1Local(1,i1+1), &
  & opDat2Local(1,i1+1), &
  & opDat3Local(1,i1+1), &
  & opDat4Local(1,i1+1), &
  & opDat5Local(1,i1+1), &
  & opDat6Local(1,i1+1), &
  & opDat7Local(1,i1+1), &
  & opDat8Local(1,map8idx), &
  & opDat8Local(1,map9idx), &
  & opDat8Local(1,map10idx), &
  & opDat8Local(1,map11idx), &
  & opDat12Local(1,map8idx), &
  & opDat12Local(1,map9idx), &
  & opDat12Local(1,map10idx), &
  & opDat12Local(1,map11idx), &
  & opDat16Local(1), &
  & opDat17Local(1), &
  & opDat18Local(1), &
  & opDat19Local(1), &
  & opDat20Local(1), &
  & opDat21Local(1), &
  & opDat22Local(1), &
  & opDat23Local(1), &
  & opDat24Local(1), &
  & opDat25Local(1), &
  & opDat26Local(1), &
  & opDat27Local(1), &
  & opDat28Local(1,i1+1) &
  & )
END DO
END SUBROUTINE
SUBROUTINE write_regvalues_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7, &
& opArg8, &
& opArg9, &
& opArg10, &
& opArg11, &
& opArg12, &
& opArg13, &
& opArg14, &
& opArg15, &
& opArg16, &
& opArg17, &
& opArg18, &
& opArg19, &
& opArg20, &
& opArg21, &
& opArg22, &
& opArg23, &
& opArg24, &
& opArg25, &
& opArg26, &
& opArg27, &
& opArg28 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7
type ( op_arg ) , INTENT(IN) :: opArg8
type ( op_arg ) , INTENT(IN) :: opArg9
type ( op_arg ) , INTENT(IN) :: opArg10
type ( op_arg ) , INTENT(IN) :: opArg11
type ( op_arg ) , INTENT(IN) :: opArg12
type ( op_arg ) , INTENT(IN) :: opArg13
type ( op_arg ) , INTENT(IN) :: opArg14
type ( op_arg ) , INTENT(IN) :: opArg15
type ( op_arg ) , INTENT(IN) :: opArg16
type ( op_arg ) , INTENT(IN) :: opArg17
type ( op_arg ) , INTENT(IN) :: opArg18
type ( op_arg ) , INTENT(IN) :: opArg19
type ( op_arg ) , INTENT(IN) :: opArg20
type ( op_arg ) , INTENT(IN) :: opArg21
type ( op_arg ) , INTENT(IN) :: opArg22
type ( op_arg ) , INTENT(IN) :: opArg23
type ( op_arg ) , INTENT(IN) :: opArg24
type ( op_arg ) , INTENT(IN) :: opArg25
type ( op_arg ) , INTENT(IN) :: opArg26
type ( op_arg ) , INTENT(IN) :: opArg27
type ( op_arg ) , INTENT(IN) :: opArg28

type ( op_arg ) , DIMENSION(28) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat8Map
INTEGER(kind=4) :: opDat8MapDim
real(8), POINTER, DIMENSION(:) :: opDat8Local
INTEGER(kind=4) :: opDat8Cardinality

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat12Map
INTEGER(kind=4) :: opDat12MapDim
real(8), POINTER, DIMENSION(:) :: opDat12Local
INTEGER(kind=4) :: opDat12Cardinality

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat3Local
INTEGER(kind=4) :: opDat3Cardinality

real(8), POINTER, DIMENSION(:) :: opDat4Local
INTEGER(kind=4) :: opDat4Cardinality

real(8), POINTER, DIMENSION(:) :: opDat5Local
INTEGER(kind=4) :: opDat5Cardinality

real(8), POINTER, DIMENSION(:) :: opDat6Local
INTEGER(kind=4) :: opDat6Cardinality

real(8), POINTER, DIMENSION(:) :: opDat7Local
INTEGER(kind=4) :: opDat7Cardinality

real(8), POINTER, DIMENSION(:) :: opDat16Local
real(8), POINTER, DIMENSION(:) :: opDat17Local
real(8), POINTER, DIMENSION(:) :: opDat18Local
real(8), POINTER, DIMENSION(:) :: opDat19Local
real(8), POINTER, DIMENSION(:) :: opDat20Local
real(8), POINTER, DIMENSION(:) :: opDat21Local
real(8), POINTER, DIMENSION(:) :: opDat22Local
real(8), POINTER, DIMENSION(:) :: opDat23Local
real(8), POINTER, DIMENSION(:) :: opDat24Local
real(8), POINTER, DIMENSION(:) :: opDat25Local
real(8), POINTER, DIMENSION(:) :: opDat26Local
integer(4), POINTER, DIMENSION(:) :: opDat27Local
integer(4), POINTER, DIMENSION(:) :: opDat28Local
INTEGER(kind=4) :: opDat28Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
LOGICAL :: firstTime_write_regvalues = .TRUE.
type ( c_ptr )  :: planRet_write_regvalues
type ( op_plan ) , POINTER :: actualPlan_write_regvalues
INTEGER(kind=4), POINTER, DIMENSION(:) :: ncolblk_write_regvalues
INTEGER(kind=4), POINTER, DIMENSION(:) :: blkmap_write_regvalues
INTEGER(kind=4), POINTER, DIMENSION(:) :: nelems_write_regvalues
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_write_regvalues
INTEGER(kind=4), DIMENSION(1:28) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: blockOffset
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b

real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost16
real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost17
real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost18
real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost19
real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost20
real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost21
real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost22
real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost23
real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost24
real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost25
real(8), DIMENSION(:), ALLOCATABLE :: reductionArrayHost26

INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 28

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7
opArgArray(8) = opArg8
opArgArray(9) = opArg9
opArgArray(10) = opArg10
opArgArray(11) = opArg11
opArgArray(12) = opArg12
opArgArray(13) = opArg13
opArgArray(14) = opArg14
opArgArray(15) = opArg15
opArgArray(16) = opArg16
opArgArray(17) = opArg17
opArgArray(18) = opArg18
opArgArray(19) = opArg19
opArgArray(20) = opArg20
opArgArray(21) = opArg21
opArgArray(22) = opArg22
opArgArray(23) = opArg23
opArgArray(24) = opArg24
opArgArray(25) = opArg25
opArgArray(26) = opArg26
opArgArray(27) = opArg27
opArgArray(28) = opArg28

returnSetKernelTiming = setKernelTime(28 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000,0.00000, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  partitionSize = 0

  numberOfThreads = omp_get_max_threads()
  indirectionDescriptorArray(1) = -1
  indirectionDescriptorArray(2) = -1
  indirectionDescriptorArray(3) = -1
  indirectionDescriptorArray(4) = -1
  indirectionDescriptorArray(5) = -1
  indirectionDescriptorArray(6) = -1
  indirectionDescriptorArray(7) = -1
  indirectionDescriptorArray(8) = 0
  indirectionDescriptorArray(9) = 0
  indirectionDescriptorArray(10) = 0
  indirectionDescriptorArray(11) = 0
  indirectionDescriptorArray(12) = 1
  indirectionDescriptorArray(13) = 1
  indirectionDescriptorArray(14) = 1
  indirectionDescriptorArray(15) = 1
  indirectionDescriptorArray(16) = -1
  indirectionDescriptorArray(17) = -1
  indirectionDescriptorArray(18) = -1
  indirectionDescriptorArray(19) = -1
  indirectionDescriptorArray(20) = -1
  indirectionDescriptorArray(21) = -1
  indirectionDescriptorArray(22) = -1
  indirectionDescriptorArray(23) = -1
  indirectionDescriptorArray(24) = -1
  indirectionDescriptorArray(25) = -1
  indirectionDescriptorArray(26) = -1
  indirectionDescriptorArray(27) = -1
  indirectionDescriptorArray(28) = -1

  numberOfIndirectOpDats = 2

  planRet_write_regvalues = FortranPlanCaller( &
  & userSubroutine//C_NULL_CHAR, &
  & set%setCPtr, &
  & partitionSize, &
  & numberOfOpDats, &
  & opArgArray, &
  & numberOfIndirectOpDats, &
  & indirectionDescriptorArray,2)

  CALL c_f_pointer(planRet_write_regvalues,actualPlan_write_regvalues)
  CALL c_f_pointer(actualPlan_write_regvalues%ncolblk,ncolblk_write_regvalues,(/actualPlan_write_regvalues%ncolors_core/))
  CALL c_f_pointer(actualPlan_write_regvalues%blkmap,blkmap_write_regvalues,(/actualPlan_write_regvalues%nblocks/))
  CALL c_f_pointer(actualPlan_write_regvalues%offset,offset_write_regvalues,(/actualPlan_write_regvalues%nblocks/))
  CALL c_f_pointer(actualPlan_write_regvalues%nelems,nelems_write_regvalues,(/actualPlan_write_regvalues%nblocks/))

  opSetCore => set%setPtr

  opDat8Cardinality = opArg8%dim * getSetSizeFromOpArg(opArg8)
  opDat8MapDim = getMapDimFromOpArg(opArg8)
  opDat12Cardinality = opArg12%dim * getSetSizeFromOpArg(opArg12)
  opDat12MapDim = getMapDimFromOpArg(opArg12)
  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
  opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
  opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
  opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
  opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
  opDat28Cardinality = opArg28%dim * getSetSizeFromOpArg(opArg28)
  CALL c_f_pointer(opArg8%data,opDat8Local,(/opDat8Cardinality/))
  CALL c_f_pointer(opArg8%map_data,opDat8Map,(/opSetCore%size*opDat8MapDim/))
  CALL c_f_pointer(opArg12%data,opDat12Local,(/opDat12Cardinality/))
  CALL c_f_pointer(opArg12%map_data,opDat12Map,(/opSetCore%size*opDat12MapDim/))
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg3%data,opDat3Local,(/opDat3Cardinality/))
  CALL c_f_pointer(opArg4%data,opDat4Local,(/opDat4Cardinality/))
  CALL c_f_pointer(opArg5%data,opDat5Local,(/opDat5Cardinality/))
  CALL c_f_pointer(opArg6%data,opDat6Local,(/opDat6Cardinality/))
  CALL c_f_pointer(opArg7%data,opDat7Local,(/opDat7Cardinality/))
  CALL c_f_pointer(opArg16%data,opDat16Local, (/opArg16%dim/))
  CALL c_f_pointer(opArg17%data,opDat17Local, (/opArg17%dim/))
  CALL c_f_pointer(opArg18%data,opDat18Local, (/opArg18%dim/))
  CALL c_f_pointer(opArg19%data,opDat19Local, (/opArg19%dim/))
  CALL c_f_pointer(opArg20%data,opDat20Local, (/opArg20%dim/))
  CALL c_f_pointer(opArg21%data,opDat21Local, (/opArg21%dim/))
  CALL c_f_pointer(opArg22%data,opDat22Local, (/opArg22%dim/))
  CALL c_f_pointer(opArg23%data,opDat23Local, (/opArg23%dim/))
  CALL c_f_pointer(opArg24%data,opDat24Local, (/opArg24%dim/))
  CALL c_f_pointer(opArg25%data,opDat25Local, (/opArg25%dim/))
  CALL c_f_pointer(opArg26%data,opDat26Local, (/opArg26%dim/))
  CALL c_f_pointer(opArg27%data,opDat27Local, (/opArg27%dim/))
  CALL c_f_pointer(opArg28%data,opDat28Local,(/opDat28Cardinality/))

  allocate( reductionArrayHost16(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost16((i1 - 1) * ((1-1)/64+1)*64 + i2) = 0
    END DO
  END DO
  allocate( reductionArrayHost17(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost17((i1 - 1) * ((1-1)/64+1)*64 + i2) = 0
    END DO
  END DO
  allocate( reductionArrayHost18(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost18((i1 - 1) * ((1-1)/64+1)*64 + i2) = 0
    END DO
  END DO
  allocate( reductionArrayHost19(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost19((i1 - 1) * ((1-1)/64+1)*64 + i2) = opDat19Local(i2)
    END DO
  END DO
  allocate( reductionArrayHost20(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost20((i1 - 1) * ((1-1)/64+1)*64 + i2) = opDat20Local(i2)
    END DO
  END DO
  allocate( reductionArrayHost21(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost21((i1 - 1) * ((1-1)/64+1)*64 + i2) = 0
    END DO
  END DO
  allocate( reductionArrayHost22(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost22((i1 - 1) * ((1-1)/64+1)*64 + i2) = 0
    END DO
  END DO
  allocate( reductionArrayHost23(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost23((i1 - 1) * ((1-1)/64+1)*64 + i2) = opDat23Local(i2)
    END DO
  END DO
  allocate( reductionArrayHost24(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost24((i1 - 1) * ((1-1)/64+1)*64 + i2) = opDat24Local(i2)
    END DO
  END DO
  allocate( reductionArrayHost25(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost25((i1 - 1) * ((1-1)/64+1)*64 + i2) = 0
    END DO
  END DO
  allocate( reductionArrayHost26(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost26((i1 - 1) * ((1-1)/64+1)*64 + i2) = 0
    END DO
  END DO

  blockOffset = 0

  DO i1 = 0, actualPlan_write_regvalues%ncolors-1, 1
    IF (i1 .EQ. actualPlan_write_regvalues%ncolors_core) THEN
      CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
    END IF

    nblocks = ncolblk_write_regvalues(i1 + 1)
    !$OMP PARALLEL DO private (threadID, blockID, nelem, offset_b)
    DO i2 = 0, nblocks-1, 1
      threadID = omp_get_thread_num()
      blockID = blkmap_write_regvalues(i2+blockOffset+1)
      nelem = nelems_write_regvalues(blockID+1)
      offset_b = offset_write_regvalues(blockID+1)
      CALL op_wrap_write_regvalues( &
      & opDat8Local, &
      & opDat12Local, &
      & opDat1Local, &
      & opDat2Local, &
      & opDat3Local, &
      & opDat4Local, &
      & opDat5Local, &
      & opDat6Local, &
      & opDat7Local, &
      & reductionArrayHost16(threadID * ((1-1)/64+1)*64 + 1), &
      & reductionArrayHost17(threadID * ((1-1)/64+1)*64 + 1), &
      & reductionArrayHost18(threadID * ((1-1)/64+1)*64 + 1), &
      & reductionArrayHost19(threadID * ((1-1)/64+1)*64 + 1), &
      & reductionArrayHost20(threadID * ((1-1)/64+1)*64 + 1), &
      & reductionArrayHost21(threadID * ((1-1)/64+1)*64 + 1), &
      & reductionArrayHost22(threadID * ((1-1)/64+1)*64 + 1), &
      & reductionArrayHost23(threadID * ((1-1)/64+1)*64 + 1), &
      & reductionArrayHost24(threadID * ((1-1)/64+1)*64 + 1), &
      & reductionArrayHost25(threadID * ((1-1)/64+1)*64 + 1), &
      & reductionArrayHost26(threadID * ((1-1)/64+1)*64 + 1), &
      & opDat27Local, &
      & opDat28Local, &
      & opDat8Map, &
      & opDat8MapDim, &
      & offset_b, offset_b+nelem)
    END DO
    !$OMP END PARALLEL DO
    blockOffset = blockOffset + nblocks
  END DO
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat16Local = opDat16Local + reductionArrayHost16((i1 - 1) * ((1-1)/64+1)*64 + 1)
  END DO

  deallocate( reductionArrayHost16 )

  CALL op_mpi_reduce_double(opArg16,opArg16%data)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat17Local = opDat17Local + reductionArrayHost17((i1 - 1) * ((1-1)/64+1)*64 + 1)
  END DO

  deallocate( reductionArrayHost17 )

  CALL op_mpi_reduce_double(opArg17,opArg17%data)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat18Local = opDat18Local + reductionArrayHost18((i1 - 1) * ((1-1)/64+1)*64 + 1)
  END DO

  deallocate( reductionArrayHost18 )

  CALL op_mpi_reduce_double(opArg18,opArg18%data)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat19Local = MAX(opDat19Local, reductionArrayHost19((i1 - 1) * ((1-1)/64+1)*64 + 1))
  END DO

  deallocate( reductionArrayHost19 )

  CALL op_mpi_reduce_double(opArg19,opArg19%data)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat20Local = MIN(opDat20Local, reductionArrayHost20((i1 - 1) * ((1-1)/64+1)*64 + 1))
  END DO

  deallocate( reductionArrayHost20 )

  CALL op_mpi_reduce_double(opArg20,opArg20%data)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat21Local = opDat21Local + reductionArrayHost21((i1 - 1) * ((1-1)/64+1)*64 + 1)
  END DO

  deallocate( reductionArrayHost21 )

  CALL op_mpi_reduce_double(opArg21,opArg21%data)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat22Local = opDat22Local + reductionArrayHost22((i1 - 1) * ((1-1)/64+1)*64 + 1)
  END DO

  deallocate( reductionArrayHost22 )

  CALL op_mpi_reduce_double(opArg22,opArg22%data)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat23Local = MAX(opDat23Local, reductionArrayHost23((i1 - 1) * ((1-1)/64+1)*64 + 1))
  END DO

  deallocate( reductionArrayHost23 )

  CALL op_mpi_reduce_double(opArg23,opArg23%data)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat24Local = MIN(opDat24Local, reductionArrayHost24((i1 - 1) * ((1-1)/64+1)*64 + 1))
  END DO

  deallocate( reductionArrayHost24 )

  CALL op_mpi_reduce_double(opArg24,opArg24%data)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat25Local = opDat25Local + reductionArrayHost25((i1 - 1) * ((1-1)/64+1)*64 + 1)
  END DO

  deallocate( reductionArrayHost25 )

  CALL op_mpi_reduce_double(opArg25,opArg25%data)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat26Local = opDat26Local + reductionArrayHost26((i1 - 1) * ((1-1)/64+1)*64 + 1)
  END DO

  deallocate( reductionArrayHost26 )

  CALL op_mpi_reduce_double(opArg26,opArg26%data)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(28 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, actualPlan_write_regvalues%transfer,actualPlan_write_regvalues%transfer2, 1)
END SUBROUTINE
END MODULE